INSERT INTO dbo.Developers
(Id, Game, Console, Developer, Country)
VALUES(
	(1,'A Bugs Life','PS1','TT Games','England'),
	(2,'Bishi Bashi Special','PS1','Konami','Japan'),
	(3,'Buzz Lightyear of Star Command','PS1','TT Games','England'),
	(4,'Cho Aniki','PS1','Masaya','Japan'),
	(5,'Colin McRae Rally','PS1','Codemasters','England'),
	(6,'Crash Bandicoot','PS1','Naughty Dog','USA'),
	(7,'Crash Bandicoot 2','PS1','Naughty Dog','USA'),
	(8,'Crash Bandicoot 3','PS1','Naughty Dog','USA'),
	(9,'Crash Bash','PS1','Eurocom Entertainment Software','England'),
	(10,'Crash Team Racing','PS1','Naughty Dog','USA'),
	(11,'Destruction Derby','PS1','Reflections Interactive','England'),
	(12,'Driver','PS1','Reflections Interactive','England'),
	(13,'Fear Effect','PS1','Kronos Digital Entertainment','USA'),
	(14,'Fear Effect 2: Retro Helix','PS1','Kronos Digital Entertainment','USA'),
	(15,'Final Fantasy IX','PS1','Square Enix','Japan'),
	(16,'Final Fantasy V','PS1','Square Enix','Japan'),
	(17,'Final Fantasy VI','PS1','Square Enix','Japan'),
	(18,'Final Fantasy VII','PS1','Square Enix','Japan'),
	(19,'Final Fantasy VIII','PS1','Square Enix','Japan'),
	(20,'Gex','PS1','Crystal Dynamics','USA'),
	(21,'Gex 3D: Enter the Gecko','PS1','Crystal Dynamics','USA'),
	(22,'Gex: Deep Cover Gecko','PS1','Crystal Dynamics','USA'),
	(23,'Hercules','PS1','Eurocom Entertainment Software','England'),
	(24,'Hogs of War','PS1','Infogrames Sheffield','England'),
	(25,'Jumping Flash','PS1','Team Asobi','Japan'),
	(26,'Klonoa: Door to Phantomile','PS1','Bandai Namco Studios','Japan'),
	(27,'Kula World',PS1,Game Design Sweden AB,Sweden),
	(28,'Medievil',PS1,Guerrilla Cambridge,England),
	(29,'Metal Gear Solid',PS1,Kojima Productions,Japan),
	(30,'Monsters Inc Scare Island',PS1,Artificial Mind and Movement,Canada),
	(31,'Motor Toon Grand Prix 2',PS1,Polyphony Digital,Japan),
	(32,'Oddworld: Abes Exoddus',PS1,Oddworld Inhabitants,USA),
	(33,'Oddworld: Abes Oddysee',PS1,Oddworld Inhabitants,USA),
	(34,'PONG',PS1,Supersonic Software,England),
	(35,'Rally Cross',PS1,989 Studios,USA),
	(36,'Rayman',PS1,Ubisoft Montpellier,France),
	(37,'Rayman 2',PS1,Ubisoft Shanghai,China),
	(38,'Resident Evil 2',PS1,Capcom,Japan),
	(39,'Resident Evil 3: Nemesis',PS1,Capcom,Japan),
	(40,'Resident Evil: Directors Cut',PS1,Capcom,Japan),
	(41,'Sheep Dog n Wolf',PS1,Infogrames Lyon House,France),
	(42,'Silent Hill',PS1,Konami,Japan),
	(43,'Spyro 2: Gateway to Glimmer',PS1,Insomniac Games,USA),
	(44,'Spyro 3: Year of the Dragon',PS1,Insomniac Games,USA),
	(45,'Spyro the Dragon',PS1,Insomniac Games,USA),
	(46,'Suikoden',PS1,Konami,Japan),
	(47,'Suikoden II',PS1,Konami,Japan),
	(48,'Syphon Filter',PS1,Bend Studio,USA),
	(49,'Tekken',PS1,Bandai Namco Studios,Japan),
	(50,'Tekken 2',PS1,Bandai Namco Studios,Japan),
	(51,'Theme Hospital',PS1,Krisalis Software,England),
	(52,'Tomb Raider',PS1,Core Design,England),
	(53,'Tomb Raider II',PS1,Core Design,England),
	(54,'Tomb Raider III',PS1,Core Design,England),
	(55,'Tomb Raider: Chronicles',PS1,Core Design,England),
	(56,'Tomb Raider: The Last Revelation',PS1,Core Design,England),
	(57,'Tomba',PS1,Whoopee Camp,Japan),
	(58,'Tomba 2!: The Evil Swine Return',PS1,Whoopee Camp,Japan),
	(59,'Toy Story 2',PS1,TT Games,England),
	(60,'Toy Story Racer',PS1,TT Games,England),
	(61,'Twisted Metal',PS1,SingleTrac,USA),
	(62,'UmJammer Lammy',PS1,NanaOn-Sha,Japan),
	(63,'Vib-Ribbon',PS1,NanaOn-Sha,Japan),
	(64,'Wipeout',PS1,Psygnosis,England),
	(65,'WWF! Smackdown 2: Know Your Role',PS1,Yukes,Japan)
	);