INSERT INTO playstation.dbo.Origins (Id,Game,Console,Developer,Country)
VALUES
   (97,'Alice: Madness Returns','PS3','Spicy Horse','China'),
   (98,'Angry Birds Trilogy','PS3','Rovio Entertainment','Finland'),
   (99,'Army of Two','PS3','EA Montreal','Canada'),
   (100,'Bang Bang Racing','PS3','Playbox','Hungary'),
   (101,'Battlefield 3','PS3','DICE','Sweden'),
   (102,'Bayonetta','PS3','PlatinumGames','Japan'),
   (103,'Beat Hazard Ultra','PS3','Cold Beam Games','England'),
   (104,'Bentley`s Hackpack','PS3','Sanzaru Games','USA'),
   (105,'Beyond Good and Evil HD','PS3','Ubisoft Montpellier','France'),
   (106,'Blur','PS3','Bizarre Creations','England'),
   (107,'Brink','PS3','Splash Damage','England'),
   (108,'Buzz! Quiz World','PS3','Relentless Software','England'),
   (109,'Call of Duty: Modern Warfare 2 (2009)','PS3','Infinity Ward','USA'),
   (110,'Crazy Machines Elements','PS3','FAKT Software','Germany'),
   (111,'Daytona USA','PS3','Sega','Japan'),
   (112,'Dead Rising 2','PS3','Capcom Vancouver','Canada'),
   (113,'Dead Space (2008)','PS3','EA Redwood Shores','USA'),
   (114,'Deus Ex: Human Revolution','PS3','Eidos Montreal','Canada'),
   (115,'Dishonored','PS3','Arkane Studios','France'),
   (116,'DJ Hero','PS3','Ubisoft Leamington','England'),
   (117,'DJ Hero 2','PS3','Ubisoft Leamington','England'),
   (118,'Duke Nukem Forever','PS3','3D Realms','Denmark'),
   (119,'Earthworm Jim HD','PS3','Gameloft','France'),
   (120,'F.E.A.R','PS3','Monolith Productions','USA'),
   (121,'F1 Race Stars','PS3','Codemasters','England'),
   (122,'Family Guy: Back to the Multiverse','PS3','Heavy Iron Studios','USA'),
   (123,'Far Cry 2','PS3','Ubisoft Montreal','Canada'),
   (124,'Far Cry Classic','PS3','Crytek','Germany'),
   (125,'Fat Princess','PS3','Titan Studios','USA'),
   (126,'FIFA Street (2012)','PS3','EA Vancouver','Canada'),
   (127,'Fight Night Champion','PS3','EA Vancouver','Canada'),
   (128,'Final Exam','PS3','Mighty Rocket Studio','France'),
   (129,'Final Fantasy XIII','PS3','Square Enix','Japan'),
   (130,'Girl Fight','PS3','Kung Fu Factory','USA'),
   (131,'God of War (2005)','PS3','Santa Monica Studio','USA'),
   (132,'God of War II (2007)','PS3','Santa Monica Studio','USA'),
   (133,'Gran Turismo 5','PS3','Polyphony Digital','Japan'),
   (134,'Grand Theft Auto IV: The Complete Collection','PS3','Rockstar North','Scotland'),
   (135,'Hitman: Absolution','PS3','IO Interactive','Denmark'),
   (136,'ICO Classics HD','PS3','Team Asobi','Japan'),
   (137,'inFamous','PS3','Sucker Punch Productions','USA'),
   (138,'inFamous 2','PS3','Sucker Punch Productions','USA'),
   (139,'inFamous: Festival of Blood','PS3','Sucker Punch Productions','USA'),
   (140,'Jet Car Stunts','PS3','Grip Games','Czech Republic'),
   (141,'Joe Danger 2: The Movie','PS3','Hello Games','England'),
   (142,'Kane and Lynch: Dead Men','PS3','IO Interactive','Denmark'),
   (143,'Kane and Lynch 2: Dog Days','PS3','IO Interactive','Denmark'),
   (144,'Killer is Dead','PS3','Grasshopper Manufacture','Japan'),
   (145,'Killzone','PS3','Guerrilla Games','Netherlands'),
   (146,'LA Noire','PS3','Team Bondi','Australia'),
   (147,'Lemmings (2007)','PS3','Team17','England'),
   (148,'LittleBigPlanet','PS3','Media Molecule','England'),
   (149,'LittleBigPlanet 2','PS3','Media Molecule','England'),
   (150,'LittleBigPlanet Karting','PS3','United Front Games','Canada'),
   (151,'Lollipop Chainsaw','PS3','Grasshopper Manufacture','Japan'),
   (152,'Lone Survivor: The Director`s Cut','PS3','Superflat Games','England'),
   (153,'Mafia II','PS3','2K Czech','Czech Republic'),
   (154,'Malicious','PS3','Alvion','Japan'),
   (155,'Mensa Academy','PS3','Silverball Studios','England'),
   (156,'Metal Gear Solid: Peace Walker','PS3','Kojima Productions','Japan'),
   (157,'Metal Gear Solid 2: Sons of Liberty','PS3','Kojima Productions','Japan'),
   (158,'Metal Gear Solid 3: Snake Eater','PS3','Kojima Productions','Japan'),
   (159,'Metal Gear Solid 4: Guns of the Patriots','PS3','Kojima Productions','Japan'),
   (160,'Modnation Racers','PS3','United Front Games','Canada'),
   (161,'Mortal Kombat (2011)','PS3','NetherRealm Studios','USA'),
   (162,'Mortal Kombat Arcade Kollection','PS3','NetherRealm Studios','USA'),
   (163,'Motorstorm Apocalypse','PS3','Evolution Studios','England'),
   (164,'Motorstorm: Pacific Rift','PS3','Evolution Studios','England'),
   (165,'Motorstorm RC','PS3','Evolution Studios','England'),
   (166,'Naughty Bear','PS3','Artificial Mind and Movement','Canada'),
   (167,'Need for Speed: Most Wanted (2012)','PS3','Criterion Games','England'),
   (168,'Need for Speed: Shift','PS3','Slightly Mad Studios','England'),
   (169,'Need for Speed: The Run','PS3','EA Black Box','Canada'),
   (170,'Oddworld: Munch`s Oddysee','PS3','Oddworld Inhabitants','USA'),
   (171,'Oddworld: Stranger`s Wrath','PS3','Oddworld Inhabitants','USA'),
   (172,'PAYDAY: The Heist','PS3','Overkill Software','Sweden'),
   (173,'PlayStation All Stars Battle Royale','PS3','Superbot Entertainment','USA'),
   (174,'PlayStation Move Heroes','PS3','Nihilistic Software','USA'),
   (175,'Prince of Persia: The Sands of Time','PS3','Ubisoft Montreal','Canada'),
   (176,'Prince of Persia: The Two Thrones','PS3','Ubisoft Montreal','Canada'),
   (177,'Prince of Persia: Warrior Within','PS3','Ubisoft Montreal','Canada'),
   (178,'Pro Evolution Soccer 2010','PS3','Konami','Japan'),
   (179,'Quantum Conundrum','PS3','Airtight Games','USA'),
   (180,'Ratchet: Gladiator','PS3','Insomniac Games','USA'),
   (181,'Ratchet & Clank (2002)','PS3','Insomniac Games','USA'),
   (182,'Ratchet & Clank 2','PS3','Insomniac Games','USA'),
   (183,'Ratchet & Clank 3','PS3','Insomniac Games','USA'),
   (184,'Ratchet & Clank: A Crack in Time','PS3','Insomniac Games','USA'),
   (185,'Ratchet & Clank: Nexus','PS3','Insomniac Games','USA'),
   (186,'Ratchet & Clank: QForce','PS3','Insomniac Games','USA'),
   (187,'Ratchet & Clank: Quest for Booty','PS3','Insomniac Games','USA'),
   (188,'Ratchet & Clank: Tools of Destruction','PS3','Insomniac Games','USA'),
   (189,'Rayman 3 HD','PS3','Ubisoft Montpellier','France'),
   (190,'Rayman Origins','PS3','Ubisoft Montpellier','France'),
   (191,'Red Dead Redemption','PS3','Rockstar San Diego','USA'),
   (192,'Resistance: Fall of Man','PS3','Insomniac Games','USA'),
   (193,'Saints Row 2','PS3','Volition','USA'),
   (194,'Sam and Max Season 3: The Devil`s Playhouse','PS3','Telltale Games','USA'),
   (195,'Shadow of the Colossus Classics HD','PS3','Team Asobi','Japan'),
   (196,'Silent Hill HD Collection','PS3','Konami','Japan'),
   (197,'Siren Blood Curse','PS3','Team Asobi','Japan'),
   (198,'Skate 2','PS3','EA Black Box','Canada'),
   (199,'Sly 2: Band of Thieves','PS3','Sucker Punch Productions','USA'),
   (200,'Sly 3: Honour Among Thieves','PS3','Sucker Punch Productions','USA'),
   (201,'Sly Cooper and the Thievius Raccoonus','PS3','Sucker Punch Productions','USA'),
   (202,'Sonic Generations','PS3','Sega','Japan'),
   (203,'Spec Ops: The Line','PS3','Yager Development','Germany'),
   (204,'Streets of Rage 2','PS3','Sega','Japan'),
   (205,'Super Rub a Dub','PS3','Sumo Digital','England'),
   (206,'Superfrog HD','PS3','Team17','England'),
   (207,'Syndicate','PS3','Starbreeze Studios','Sweden'),
   (208,'Tales of Grace f','PS3','Bandai Namco Studios','Japan'),
   (209,'Tales of Xillia','PS3','Bandai Namco Studios','Japan'),
   (210,'Tekken 5: Dark Resurrection','PS3','Bandai Namco Studios','Japan'),
   (211,'Tekken Revolution','PS3','Bandai Namco Studios','Japan'),
   (212,'The Amazing Spider-Man','PS3','Beenox','Canada'),
   (213,'The Baconing','PS3','Hothead Games','Canada'),
   (214,'The Cave','PS3','Double Fine Productions','USA'),
   (215,'The Cube','PS3','Funbox Media','England'),
   (216,'The Darkness','PS3','Starbreeze Studios','Sweden'),
   (217,'The Darkness 2','PS3','Digital Extremes','Canada'),
   (218,'The House of the Dead: Overkill','PS3','Sega','Japan'),
   (219,'The Secret of Monkey Island: Special Edition','PS3','LucasArts','USA'),
   (220,'The Simpsons Arcade Game','PS3','Konami','Japan'),
   (221,'The Simpsons Game','PS3','EA Redwood Shores','USA'),
   (222,'The Sims 3','PS3','Maxis','USA'),
   (223,'The Sims 3: Pets','PS3','Maxis','USA'),
   (224,'Tiger Woods PGA Tour 11','PS3','EA Tiburon','USA'),
   (225,'ToeJam and Earl (1991)','PS3','Johnson Voorsanger Productions','USA'),
   (226,'ToeJam and Earl: Panic on Funkotron','PS3','Johnson Voorsanger Productions','USA'),
   (227,'Tokyo Jungle','PS3','Team Asobi','Japan'),
   (228,'Tony Hawk`s Pro Skater HD','PS3','Robomodo','USA'),
   (229,'Twisted Metal (2012)','PS3','Eat Sleep Play','USA'),
   (230,'UFC 2009 Undisputed','PS3','Yuke`s','Japan'),
   (231,'Velocity Ultra','PS3','FuturLab','England'),
   (232,'When Vikings Attack','PS3','Clever Beans','England'),
   (233,'XCOM Enemy Unknown','PS3','Firaxis Games','USA'),
   (234,'Yakuza: Dead Souls','PS3','Ryu Ga Gotoku','Japan'),
   (235,'Zombie Tycoon II: Brainhov`s Revenge','PS3','Frima Studio','Canada');