-- CREATE DATABASE
-- CREATE DATABASE psdb

-- CREATE TABLES
CREATE TABLE dates
(
	id SMALLINT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	game VARCHAR(90) NOT NULL,
	console VARCHAR(4) NOT NULL,
	release_date DATE NOT NULL,
	purchase_date DATE NOT NULL,
	start_date DATE NULL,
	finish_date DATE NULL
)

CREATE TABLE finances
(
	id SMALLINT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	game VARCHAR(90) NOT NULL,
	console VARCHAR(4) NOT NULL,
	full_price SMALLMONEY NOT NULL,
	paid_price SMALLMONEY NOT NULL,
	savings SMALLMONEY NOT NULL,
	hours INT NOT NULL,
	value SMALLMONEY NOT NULL
)

CREATE TABLE origins
(
	id SMALLINT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	game VARCHAR(90) NOT NULL,
	console VARCHAR(4) NOT NULL,
	developer VARCHAR(60) NOT NULL,
	country VARCHAR(20) NOT NULL
)