SELECT * FROM origins

-- 23RD MAY 2025 (ID 1083 - 1086)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Just Crow Things','PS4','Unbound Creations','USA'),
	('Techno Banter','PS5','Dexai Arts','Germany'),
	('Undying','PS5','Vanimals','China'),
	('Medievil 2','PS1','Guerrilla Cambridge (SCE Studio Cambridge)','England')

-- 18TH MAR 2025 (ID 1079 - 1082)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Dead Island','PS3','Techland','Poland'),
	('Football Manager 2024','PS5','Sports Interactive','England'),
	('Headliner: NoviNews','PS4','Unbound Creations','USA'),
	('Killer Frequency','PS4','Team17','England')

-- 14TH MAR 2025 (ID 1078)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Witchcrafty','VITA','PigeonDev','Russia')

-- 10TH MAR 2025 (ID 1077)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Little Goody Two Shoes','PS5','AstralShiftPro','Portugal')

-- 3RD & 4TH MAR 2025 (ID 1062 - 1076)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Crime Boss: Rockay City','PS5','Ingame Studios','Czech Republic'),
	('Sonic Colours: Ultimate','PS4','SEGA','Japan'),
	('Teenage Mutant Ninja Turtles (NES 1989) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles (Arcade 1989) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles II: The Arcade Game (1990) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles: Fall of the Foot Clan (1990) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles: Turtles in Time (Arcade 1991) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles II: Back from the Sewers (1991) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles III: The Manhattan Project (1992) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles IV: Turtles in Time (1992) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles: The Hyperstone Heist (1992) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles III: Radical Rescue (1993) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles: Tournament Fighters (SNES 1993) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles: Tournament Fighters (SEGA 1993) (The Cowabunga Collection)','PS4','Konami','Japan'),
	('Teenage Mutant Ninja Turtles: Tournament Fighters (NES 1994) (The Cowabunga Collection)','PS4','Konami','Japan')

-- 19TH FEB 2025 (ID 1061)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('The Talos Principle','PS4','Croteam','Croatia')

-- 12TH FEB 2025 (ID 1058 - 1060)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Serious Sam: The First Encounter','PS4','Croteam','Croatia'),
	('Serious Sam: The Second Encounter','PS4','Croteam','Croatia'),
	('Serious Sam 3: BFE','PS3','Croteam','Croatia')

-- 5TH FEB 2025 (ID 1055 - 1057)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('High on Life','PS4','Squanch Games','USA'),
	('Pac-Man World: Re-Pac','PS4','Now Production','Japan'),
	('Dr Fetus Mean Meat Machine','PS4','Team Meat','USA')

-- 1ST FEB 2025 (ID 1052 - 1054)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('TY the Tasmanian Tiger 2: Bush Rescue','PS2','Krome Studios','Australia'),
	('Disney Epic Mickey: Rebrushed','PS4','Purple Lamp Studios','Austria'),
	('Need for Speed Hot Pursuit','PS3','Criterion Games','England')

-- 31ST DEC 2024 (ID 1048 - 1051)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('God of War: Ragnarok','PS4','Santa Monica Studio','USA'),
	('TY the Tasmanian Tiger','PS2','Krome Studios','Australia'),
	('The Holy Gosh Darn','PS4','Perfectly Paranormal','Norway'),
	('Like a Dragon: Pirate Yakuza in Hawaii','PS5','Ryu Ga Gotoku Studio','Japan')

-- 7TH NOV 2024 (ID 1042 - 1047)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Doki Doki Literature Club Plus!','PS4','Team Salvato','USA'),
	('Hot Wheels Unleashed 2 - Turbocharged','PS4','Milestone','Italy'),
	('Parcel Corps','PS5','Billy Goat Entertainment Ltd','Northern Ireland'),
	('South Park: Snow Day!','PS5','Question Games','USA'),
	('Squirrel with a Gun','PS5','Dee Dee Creations','USA'),
	('Tekken 8','PS5','Bandai Namco Studios','Japan')

-- 21ST OCT 2024 (ID 1037 - 1041)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Palworld','PS5','Pocket Pair','Japan'),
	('SteamWorld Build','PS4','Image & Form','Sweden'),
	('Timesplitters','PS2','Free Radical Design','England'),
	('Timesplitters 2','PS2','Free Radical Design','England'),
	('Timesplitters: Future Perfect','PS2','Free Radical Design','England')

-- 2ND OCT 2024 (ID 1036)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('WWE 2K24','PS4','Visual Concepts','USA')

-- 10TH SEPT 2024 (ID 1035)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Gravity Rush','VITA','Team Asobi (Japan Studio)','Japan')

-- INITIAL DATA ENTRY (ID 1 - 1034)
-- Entered in order of console generation: PS1, PS2, PSP, PS3, VITA, PS4, VR and PS5 GAMES

-- PS1
INSERT INTO origins
(game, console, developer, country)
VALUES
	('A Bugs Life','PS1','TT Games (Travellers Tales)','England'),
	('Beyblade: Let It Rip!','PS1','Crave','Japan'),
	('Bishi Bashi Special','PS1','Konami','Japan'),
	('Buzz Lightyear of Star Command','PS1','TT Games (Travellers Tales)','England'),
	('Castlevania: Symphony of the Night','PS1','Konami','Japan'),
	('Cho Aniki','PS1','Masaya','Japan'),
	('Colin McRae Rally','PS1','Codemasters','England'),
	('Crash Bandicoot (1996)','PS1','Naughty Dog','USA'),
	('Crash Bandicoot 2: Cortex Strikes Back (1997)','PS1','Naughty Dog','USA'),
	('Crash Bandicoot 3: Warped (1998)','PS1','Naughty Dog','USA'),
	('Crash Team Racing (1999)','PS1','Naughty Dog','USA'),
	('Crash Bash','PS1','Eurocom Entertainment Software','England'),
	('Destruction Derby','PS1','Ubisoft Reflections (Reflections Interactive)','England'),
	('DOOM (1993)','PS1','id Software','USA'),
	('DOOM II: Hell on Earth','PS1','id Software','USA'),
	('Driver','PS1','Ubisoft Reflections (Reflections Interactive)','England'),
	('Duke Nukem 3D','PS1','3D Realms','Denmark'),
	('Fear Effect','PS1','Kronos Digital Entertainment','USA'),
	('Fear Effect 2: Retro Helix','PS1','Kronos Digital Entertainment','USA'),
	('Final Fantasy V','PS1','Square Enix (Squaresoft)','Japan'),
	('Final Fantasy VI','PS1','Square Enix (Squaresoft)','Japan'),
	('Final Fantasy VII (1997)','PS1','Square Enix (Squaresoft)','Japan'),
	('Final Fantasy VIII','PS1','Square Enix (Squaresoft)','Japan'),
	('Final Fantasy IX','PS1','Square Enix (Squaresoft)','Japan'),
	('Gex','PS1','Crystal Dynamics','USA'),
	('Gex: Enter the Gecko','PS1','Crystal Dynamics','USA'),
	('Gex 3: Deep Cover Gecko','PS1','Crystal Dynamics','USA'),
	('Hercules','PS1','Eurocom Entertainment Software','England'),
	('Hogs of War','PS1','Infogrames Sheffield House (Gremlin Interactive)','England'),
	('Jumping Flash!','PS1','Exact (EXcellent Application Create Team)','Japan'),
	('Klonoa: Door to Phantomile (1997)','PS1','Bandai Namco Studios','Japan'),
	('Kula World','PS1','Game Design Sweden AB','Sweden'),
	('Medievil (1998)','PS1','Guerrilla Cambridge (SCE Studio Cambridge)','England'),
	('Metal Gear Solid','PS1','Konami','Japan'),
	('Monsters Inc Scare Island','PS1','Behaviour Interactive (Artificial Mind and Movement)','Canada'),
	('Mortal Kombat 3','PS1','Midway','USA'),
	('Motor Toon Grand Prix 2','PS1','Polyphony Digital (Polys Entertainment)','Japan'),
	('Oddworld: Abes Oddysee (1997)','PS1','Oddworld Inhabitants','USA'),
	('Oddworld: Abes Exoddus (1998)','PS1','Oddworld Inhabitants','USA'),
	('PaRappa the Rapper','PS1','NanaOn-Sha','Japan'),
	('Pong: The Next Level','PS1','Supersonic Software','England'),
	('Rally Cross','PS1','Sony Interactive Studios America (989 Studios)','USA'),
	('Rayman','PS1','Ubisoft Montpellier','France'),
	('Rayman 2: The Great Escape','PS1','Ubisoft Shanghai','China'),
	('Resident Evil: Directors Cut (1997)','PS1','Capcom','Japan'),
	('Resident Evil 2 (1998)','PS1','Capcom','Japan'),
	('Resident Evil 3: Nemesis (1999)','PS1','Capcom','Japan'),
	('Sheep Dog n Wolf','PS1','Atari SA (Infogrames Lyon House)','France'),
	('Silent Hill','PS1','Konami (Team Silent)','Japan'),
	('Spyro the Dragon (1998)','PS1','Insomniac Games','USA'),
	('Spyro 2: Gateway to Glimmer (1999)','PS1','Insomniac Games','USA'),
	('Spyro 3: Year of the Dragon (2000)','PS1','Insomniac Games','USA'),
	('Super Street Fighter II Turbo: The Ultimate Championship (1994)','PS1','Capcom','Japan'),
	('Street Fighter Alpha: Warriors Dreams (1995)','PS1','Capcom','Japan'),
	('Street Fighter Alpha 2 (1996)','PS1','Capcom','Japan'),
	('Street Fighter Alpha 3 (1998)','PS1','Capcom','Japan'),
	('Suikoden','PS1','Konami','Japan'),
	('Suikoden II','PS1','Konami','Japan'),
	('Syphon Filter','PS1','Bend Studio (Eidetic)','USA'),
	('Tekken','PS1','Bandai Namco Studios','Japan'),
	('Tekken 2','PS1','Bandai Namco Studios','Japan'),
	('Theme Hospital','PS1','Krisalis Software','England'),
	('Tomb Raider (1996)','PS1','Rebellion Developments (Core Design)','England'),
	('Tomb Raider II','PS1','Rebellion Developments (Core Design)','England'),
	('Tomb Raider III','PS1','Rebellion Developments (Core Design)','England'),
	('Tomb Raider: The Last Revelation','PS1','Rebellion Developments (Core Design)','England'),
	('Tomb Raider: Chronicles','PS1','Rebellion Developments (Core Design)','England'),
	('Tombi!','PS1','Whoopee Camp','Japan'),
	('Tombi 2!: The Evil Swine Return','PS1','Whoopee Camp','Japan'),
	('Toy Story 2: Buzz Lightyear to the Rescue!','PS1','TT Games (Travellers Tales)','England'),
	('Toy Story Racer','PS1','TT Games (Travellers Tales)','England'),
	('Twisted Metal (1995)','PS1','SingleTrac','USA'),
	('Um Jammer Lammy','PS1','NanaOn-Sha','Japan'),
	('Vib-Ribbon','PS1','NanaOn-Sha','Japan'),
	('Wipeout (1995)','PS1','Studio Liverpool (Psygnosis)','England'),
	('WWF! Smackdown 2: Know Your Role','PS1','Yukes','Japan')

-- PS2
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Ape Escape 2','PS2','Team Asobi (Japan Studio)','Japan'),
	('Beyond Good and Evil','PS2','Ubisoft Montpellier','France'),
	('Bloodrayne','PS2','Terminal Reality','USA'),
	('Bloodrayne 2','PS2','Terminal Reality','USA'),
	('Canis Canem Edit (Bully)','PS2','Rockstar Vancouver','Canada'),
	('Cel Damage','PS2','Pseudo Interactive','Canada'),
	('Crazy Taxi','PS2','SEGA (Hitmaker)','Japan'),
	('Dark Cloud','PS2','Level-5','Japan'),
	('Dark Chronicle (Dark Cloud 2)','PS2','Level-5','Japan'),
	('Destroy All Humans! (2005)','PS2','Pandemic Studios','USA'),
	('Destroy All Humans! 2 (2006)','PS2','Pandemic Studios','USA'),
	('Deus Ex','PS2','Ion Storm','USA'),
	('Devil May Cry','PS2','Capcom','Japan'),
	('Devil May Cry 2','PS2','Capcom','Japan'),
	('Devil May Cry 3: Dantes Awakening','PS2','Capcom','Japan'),
	('DJ Hero','PS2','Ubisoft Leamington (FreeStyleGames and Exient Entertainment)','England'),
	('Fahrenheit (Indigo Prophecy)','PS2','Quantic Dream','France'),
	('Final Fantasy X','PS2','Square Enix (Squaresoft)','Japan'),
	('Final Fantasy X-2','PS2','Square Enix','Japan'),
	('God of War (2005)','PS2','Santa Monica Studio','USA'),
	('God of War II','PS2','Santa Monica Studio','USA'),
	('Grand Theft Auto III (2001)','PS2','Rockstar North (DMA Design)','Scotland'),
	('Grand Theft Auto: Vice City (2002)','PS2','Rockstar North','Scotland'),
	('Grand Theft Auto: San Andreas','PS2','Rockstar North','Scotland'),
	('Harvest Moon: A Wonderful Life','PS2','Marvelous Interactive','Japan'),
	('Ico','PS2','Team Asobi (Japan Studio Team Ico)','Japan'),
	('Jak and Daxter: The Precursor Legacy','PS2','Naughty Dog','USA'),
	('Jak II','PS2','Naughty Dog','USA'),
	('Jak 3','PS2','Naughty Dog','USA'),
	('Jak X: Combat Racing','PS2','Naughty Dog','USA'),
	('Killzone','PS2','Guerrilla Games','Netherlands'),
	('Kingdom Hearts','PS2','Square Enix (Squaresoft)','Japan'),
	('Kingdom Hearts II','PS2','Square Enix','Japan'),
	('Klonoa 2: Lunateas Veil (2001)','PS2','Bandai Namco Studios','Japan'),
	('LEGO Indiana Jones: The Original Adventures','PS2','TT Games (Travellers Tales)','England'),
	('LEGO Batman: The Videogame','PS2','TT Games (Travellers Tales)','England'),
	('Manhunt','PS2','Rockstar North','Scotland'),
	('Max Payne','PS2','Remedy Entertainment','Finland'),
	('Metal Gear Solid 2: Sons of Liberty','PS2','Konami','Japan'),
	('Metal Gear Solid 3: Snake Eater','PS2','Konami','Japan'),
	('Okami','PS2','Clover Studio','Japan'),
	('PaRappa the Rapper 2','PS2','NanaOn-Sha','Japan'),
	('Primal','PS2','Guerrilla Cambridge (SCE Studio Cambridge)','England'),
	('Prince of Persia: The Sands of Time','PS2','Ubisoft Montreal','Canada'),
	('Prince of Persia: Warrior Within','PS2','Ubisoft Montreal','Canada'),
	('Prince of Persia: The Two Thrones','PS2','Ubisoft Montreal','Canada'),
	('Psychonauts','PS2','Double Fine Productions','USA'),
	('Ratchet & Clank (2002)','PS2','Insomniac Games','USA'),
	('Ratchet & Clank 2','PS2','Insomniac Games','USA'),
	('Ratchet & Clank 3','PS2','Insomniac Games','USA'),
	('Ratchet: Gladiator','PS2','Insomniac Games','USA'),
	('Rayman 3: Hoodlum Havoc','PS2','Ubisoft Montpellier','France'),
	('Red Dead Revolver','PS2','Rockstar San Diego','USA'),
	('Resident Evil: Code Veronica X','PS2','Capcom','Japan'),
	('Resident Evil 4 (2005)','PS2','Capcom','Japan'),
	('Shadow of the Colossus','PS2','Team Asobi (Japan Studio Team Ico)','Japan'),
	('Silent Hill 2','PS2','Konami (Team Silent)','Japan'),
	('Silent Hill 3','PS2','Konami (Team Silent)','Japan'),
	('Sly Raccoon','PS2','Sucker Punch Productions','USA'),
	('Sly 2: Band of Thieves','PS2','Sucker Punch Productions','USA'),
	('Sly 3: Honour Among Thieves','PS2','Sucker Punch Productions','USA'),
	('Sonic Heroes','PS2','SEGA (Sonic Team)','Japan'),
	('Stuntman: Ignition','PS2','Paradigm Entertainment','USA'),
	('Super Monkey Ball Adventure','PS2','TT Games (Travellers Tales)','England'),
	('The Simpsons Game','PS2','EA Redwood Shores','USA'),
	('The Sims','PS2','Maxis','USA'),
	('The Sims 2','PS2','Maxis','USA'),
	('The Warriors','PS2','Rockstar Toronto','Canada'),
	('Tomb Raider: Legend','PS2','Crystal Dynamics','USA'),
	('Tomb Raider: Anniversary','PS2','Crystal Dynamics (Buzz Monkey Software)','USA'),
	('Twisted Metal: Black','PS2','Incognito Entertainment','USA')

-- PSP
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Ape Escape: On the Loose','PSP','Team Asobi (Japan Studio)','Japan'),
	('Burnout Legends','PSP','Criterion Games','England'),
	('Castlevania: Rondo of Blood (The Dracula X Chronicles)','PSP','Konami','Japan'),
	('Crazy Taxi 2','PSP','SEGA (Hitmaker)','Japan'),
	('Daxter','PSP','Ready At Dawn Studios','USA'),
	('Dead or Alive Paradise (Dead or Alive Xtreme 2)','PSP','Team Ninja','Japan'),
	('Everybodys Golf 2','PSP','Clap Hanz','Japan'),
	('Final Fantasy (2008)','PSP','Square Enix','Japan'),
	('Final Fantasy II (2008)','PSP','Square Enix','Japan'),
	('Final Fantasy III (2006)','PSP','Square Enix','Japan'),
	('Final Fantasy IV: The Complete Collection','PSP','Square Enix','Japan'),
	('Grand Theft Auto: Liberty City Stories','PSP','Rockstar Leeds','England'),
	('Grand Theft Auto: Vice City Stories','PSP','Rockstar Leeds','England'),
	('Grand Theft Auto: Chinatown Wars','PSP','Rockstar Leeds','England'),
	('Jak and Daxter: The Lost Frontier','PSP','High Impact Games','USA'),
	('Jetpack Joyride','PSP','Halfbrick Studios','Australia'),
	('Kingdom Hearts Birth by Sleep and Re: Coded (HD 2.5 Remix)','PSP','Square Enix','Japan'),
	('LEGO Star Wars III: The Clone Wars','PSP','TT Games (Travellers Tales)','England'),
	('LEGO Pirates of the Caribbean: The Video Game','PSP','TT Games (Travellers Tales)','England'),
	('Lemmings (2006)','PSP','Team17','England'),
	('LocoRoco','PSP','Team Asobi (Japan Studio)','Japan'),
	('Metal Gear Solid: Peace Walker','PSP','Konami','Japan'),
	('Prinny: Can I Really Be The Hero?','PSP','Nippon Ichi Software','Japan'),
	('Ratchet & Clank: Size Matters','PSP','High Impact Games','USA'),
	('Resistance: Retribution','PSP','Bend Studio','USA'),
	('Tekken 5: Dark Resurrection','PSP','Bandai Namco Studios (Eighting)','Japan'),
	('Wipeout Pulse','PSP','Studio Liverpool (Psygnosis)','England')

-- PS3
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Action Henk','PS3','RageSquid','Netherlands'),
	('Alice: Madness Returns','PS3','Spicy Horse','China'),
	('Angry Birds Classic (2009)','PS3','Rovio Entertainment (Housemarque)','Finland'),
	('Angry Birds Seasons (2010)','PS3','Rovio Entertainment (Housemarque)','Finland'),
	('Angry Birds Rio (2011)','PS3','Rovio Entertainment (Housemarque)','Finland'),
	('Another World: 20th Anniversary','PS3','Delphine Software International (DSI Interplay)','France'),
	('Army of Two','PS3','EA Montreal','Canada'),
	('Back to the Future: The Telltale Game','PS3','Telltale Games','USA'),
	('Badland','PS3','HypeHype (Frogmind)','Finland'),
	('Bang Bang Racing','PS3','Playbox (Digital Reality)','Hungary'),
	('Batman: Arkham Asylum','PS3','Rocksteady Studios','England'),
	('Batman: Arkham City','PS3','Rocksteady Studios','England'),
	('Battlefield 3','PS3','EA DICE (Digital Illusions CE)','Sweden'),
	('Bayonetta','PS3','PlatinumGames','Japan'),
	('Beat Hazard Ultra','PS3','Cold Beam Games','England'),
	('Bentleys Hackpack','PS3','Sanzaru Games','USA'),
	('Beyond Two Souls','PS3','Quantic Dream','France'),
	('BioShock','PS3','2K Boston (Irrational Games)','USA'),
	('BioShock 2','PS3','2K Marin','USA'),
	('BioShock Infinite','PS3','2K Boston (Irrational Games)','USA'),
	('Blur','PS3','Bizarre Creations','England'),
	('Borderlands','PS3','Gearbox Software','USA'),
	('Borderlands: The Pre-Sequel','PS3','2K Australia','Australia'),
	('Borderlands 2','PS3','Gearbox Software','USA'),
	('Brink','PS3','Splash Damage','England'),
	('Brothers: A Tale of Two Sons (2013)','PS3','Starbreeze Studios','Sweden'),
	('Burnout Paradise','PS3','Criterion Games','England'),
	('Buzz!: Quiz World','PS3','Relentless Software','England'),
	('Call of Duty: Modern Warfare 2','PS3','Infinity Ward','USA'),
	('Castle Crashers','PS3','The Behemoth','USA'),
	('Catherine','PS3','Atlus','Japan'),
	('Child of Light','PS3','Ubisoft Montreal','Canada'),
	('Cosmophony','PS3','Bento Studio','France'),
	('CounterSpy','PS3','Dynamighty','USA'),
	('Crazy Machines Elements','PS3','FAKT Software','Germany'),
	('Dark Souls','PS3','FromSoftware','Japan'),
	('Dark Souls II','PS3','FromSoftware','Japan'),
	('Daytona USA','PS3','SEGA','Japan'),
	('Dead or Alive 5','PS3','Team Ninja','Japan'),
	('Dead Rising 2','PS3','Capcom Vancouver (Blue Castle Games)','Canada'),
	('Dead Space (2008)','PS3','Visceral Games (EA Redwood Shores)','USA'),
	('Deadpool','PS3','High Moon Studios','USA'),
	('Deathmatch Village','PS3','Bloober Team','Poland'),
	('DeathSpank: The Baconing','PS3','Hothead Games','Canada'),
	('Deus Ex: Human Revolution','PS3','Eidos Montreal','Canada'),
	('Devil May Cry 4','PS3','Capcom','Japan'),
	('Dishonored','PS3','Arkane Studios','France'),
	('DJ Hero 2','PS3','Ubisoft Leamington (FreeStyleGames and Exient Entertainment)','England'),
	('Doki-Doki Universe','PS3','HumaNature Studios','USA'),
	('Duke Nukem Forever','PS3','Gearbox Software','USA'),
	('Earthworm Jim HD','PS3','Gameloft','France'),
	('F.E.A.R (First Encounter Assault Recon)','PS3','Monolith Productions','USA'),
	('F1 Race Stars','PS3','Codemasters Birmingham','England'),
	('Family Guy: Back to the Multiverse','PS3','Heavy Iron Studios','USA'),
	('Far Cry Classic','PS3','Crytek','Germany'),
	('Far Cry 2','PS3','Ubisoft Montreal','Canada'),
	('Far Cry 3','PS3','Ubisoft Montreal','Canada'),
	('Far Cry 4','PS3','Ubisoft Montreal','Canada'),
	('Fat Princess','PS3','Titan Studios','USA'),
	('FEZ','PS3','Polytron Corporation','Canada'),
	('FIFA 16','PS3','EA Vancouver','Canada'),
	('FIFA 17','PS3','EA Vancouver','Canada'),
	('FIFA 18','PS3','EA Vancouver','Canada'),
	('FIFA 19','PS3','EA Vancouver','Canada'),
	('FIFA Street (2012)','PS3','EA Vancouver','Canada'),
	('Fight Night Champion','PS3','EA Vancouver','Canada'),
	('Final Exam','PS3','Mighty Rocket Studio','France'),
	('Final Fantasy XIII','PS3','Square Enix','Japan'),
	('flOw','PS3','Thatgamecompany','USA'),
	('Flower','PS3','Thatgamecompany','USA'),
	('Geometry Wars 3: Dimensions Evolved','PS3','Lucid Games','England'),
	('Girl Fight','PS3','Kung Fu Factory','USA'),
	('Goat Simulator','PS3','Coffee Stain Studios','Sweden'),
	('God of War III','PS3','Santa Monica Studio','USA'),
	('Gran Turismo 5','PS3','Polyphony Digital','Japan'),
	('Grand Theft Auto IV','PS3','Rockstar North','Scotland'),
	('Grand Theft Auto V','PS3','Rockstar North','Scotland'),
	('Gravity Crash','PS3','Just Add Water','England'),
	('Heavy Rain','PS3','Quantic Dream','France'),
	('Hitman: Absolution','PS3','IO Interactive','Denmark'),
	('Hohokum','PS3','Honeyslug','England'),
	('Hotline Miami','PS3','Dennaton Games','Sweden'),
	('Hotline Miami 2: Wrong Number','PS3','Dennaton Games','Sweden'),
	('inFamous','PS3','Sucker Punch Productions','USA'),
	('inFamous 2','PS3','Sucker Punch Productions','USA'),
	('inFamous: Festival of Blood','PS3','Sucker Punch Productions','USA'),
	('Injustice: Gods Among Us','PS3','NetherRealm Studios','USA'),
	('Jet Car Stunts','PS3','Grip Games','Czech Republic'),
	('Jet Set Radio','PS3','SEGA','Japan'),
	('Joe Danger 2: The Movie','PS3','Hello Games','England'),
	('Journey','PS3','Thatgamecompany','USA'),
	('Kane and Lynch: Dead Men','PS3','IO Interactive','Denmark'),
	('Kane and Lynch 2: Dog Days','PS3','IO Interactive','Denmark'),
	('Killer Is Dead','PS3','Grasshopper Manufacture','Japan'),
	('Kingdom Hearts Re: Chain of Memories and 358/2 Days','PS3','Square Enix','Japan'),
	('Kingdoms of Amalur: Reckoning','PS3','Big Huge Games','USA'),
	('LA Noire','PS3','Team Bondi','Australia'),
	('LEGO Batman 2: DC Super Heroes','PS3','TT Games','England'),
	('LEGO Harry Potter Collection: Years 1-4','PS3','TT Games','England'),
	('LEGO Harry Potter Collection: Years 5-7','PS3','TT Games','England'),
	('LEGO Marvel Super Heroes','PS3','TT Games','England'),
	('LEGO The Hobbit','PS3','TT Games','England'),
	('Life is Strange','PS3','Dontnod Entertainment','France'),
	('Like a Dragon 3 (Yakuza 3)','PS3','SEGA','Japan'),
	('Like a Dragon 4 (Yakuza 4)','PS3','SEGA','Japan'),
	('Like a Dragon 5 (Yakuza 5)','PS3','Ryu Ga Gotoku Studio','Japan'),
	('LittleBigPlanet','PS3','Media Molecule','England'),
	('LittleBigPlanet 2','PS3','Media Molecule','England'),
	('LittleBigPlanet 3','PS3','Sumo Digital','England'),
	('LittleBigPlanet Karting','PS3','United Front Games','Canada'),
	('Lollipop Chainsaw','PS3','Grasshopper Manufacture','Japan'),
	('Lone Survivor','PS3','Superflat Games','England'),
	('Mafia II','PS3','Hangar 13 (2K Czech)','USA'),
	('Malicious','PS3','Alvion','Japan'),
	('Mass Effect','PS3','BioWare','Canada'),
	('Mass Effect 2','PS3','BioWare','Canada'),
	('Mass Effect 3','PS3','BioWare','Canada'),
	('Metal Gear Solid 4: Guns of the Patriots','PS3','Konami','Japan'),
	('Metal Gear Solid V: The Phantom Pain','PS3','Konami','Japan'),
	('Metro: Last Light','PS3','4A Games','Ukraine'),
	('Minecraft','PS3','Mojang Studios','Sweden'),
	('ModNation Racers','PS3','United Front Games','Canada'),
	('Monopoly Deal (Monopoly Family Fun Pack)','PS3','Asobo Studio','France'),
	('Monopoly Plus (Monopoly Family Fun Pack)','PS3','Asobo Studio','France'),
	('Mortal Kombat (1992)','PS3','Midway','USA'),
	('Mortal Kombat II','PS3','Midway','USA'),
	('Mortal Kombat (2011)','PS3','NetherRealm Studios','USA'),
	('MotorStorm: Pacific Rift','PS3','Evolution Studios','England'),
	('Motorstorm: Apocalypse','PS3','Evolution Studios','England'),
	('MotorStorm: RC','PS3','Evolution Studios','England'),
	('Naughty Bear','PS3','Behaviour Interactive (Artificial Mind and Movement)','Canada'),
	('Need for Speed: Shift','PS3','Slightly Mad Studios','England'),
	('Need for Speed: The Run','PS3','EA Black Box','Canada'),
	('Need for Speed: Most Wanted (2012)','PS3','Criterion Games','England'),
	('Ni No Kuni: Wrath of the White Witch','PS3','Level-5','Japan'),
	('Nitroplus Blasterz: Heroines Infinite Duel','PS3','Team Arcana (Examu)','Japan'),
	('Oddworld: Munchs Oddysee','PS3','Oddworld Inhabitants','USA'),
	('Oddworld: Strangers Wrath','PS3','Oddworld Inhabitants','USA'),
	('One Piece: Unlimited World Red','PS3','Ganbarion','Japan'),
	('Payday: The Heist','PS3','Overkill Software','Sweden'),
	('Persona 5','PS3','Atlus','Japan'),
	('PixelJunk Shooter','PS3','Q-Games','Japan'),
	('PlayStation All-Stars Battle Royale','PS3','Superbot Entertainment','USA'),
	('PlayStation Move Heroes','PS3','Nihilistic Software','USA'),
	('Pro Evolution Soccer 2010','PS3','Konami','Japan'),
	('Prototype','PS3','Radical Entertainment','Canada'),
	('Prototype 2','PS3','Radical Entertainment','Canada'),
	('Pumped BMX+','PS3','Yeah Us!','England'),
	('Putty Squad','PS3','System 3 Software','England'),
	('Quantum Conundrum','PS3','Airtight Games','USA'),
	('Ratchet & Clank (Future): Tools of Destruction','PS3','Insomniac Games','USA'),
	('Ratchet & Clank (Future): Quest for Booty','PS3','Insomniac Games','USA'),
	('Ratchet & Clank (Future): A Crack in Time','PS3','Insomniac Games','USA'),
	('Ratchet & Clank: QForce (Full Frontal Assault)','PS3','Insomniac Games','USA'),
	('Ratchet & Clank: (Into The) Nexus','PS3','Insomniac Games','USA'),
	('Rayman Origins','PS3','Ubisoft Montpellier','France'),
	('Rayman Legends','PS3','Ubisoft Montpellier','France'),
	('Red Dead Redemption','PS3','Rockstar San Diego','USA'),
	('Resident Evil 0 (Zero)','PS3','Capcom','Japan'),
	('Resident Evil (2002)','PS3','Capcom','Japan'),
	('Resident Evil 5','PS3','Capcom','Japan'),
	('Resident Evil: Revelations','PS3','Capcom','Japan'),
	('Resident Evil 6','PS3','Capcom','Japan'),
	('Resident Evil: Revelations 2','PS3','Capcom','Japan'),
	('Resistance: Fall of Man','PS3','Insomniac Games','USA'),
	('Retro City Rampage','PS3','Vblank Entertainment','Canada'),
	('Rocketbirds: Hardboiled Chicken','PS3','Ratloop','USA'),
	('Rogue Legacy','PS3','Cellar Door Games','Canada'),
	('Saints Row 2','PS3','Deep Silver Volition','USA'),
	('Saints Row: The Third','PS3','Deep Silver Volition','USA'),
	('Saints Row IV: Re-Elected','PS3','Deep Silver Volition','USA'),
	('Saints Row IV: Gat out of Hell','PS3','Deep Silver Volition','USA'),
	('Sam & Max Season 2: Beyond Time and Space TTG','PS3','Telltale Games','USA'),
	('Sam & Max Season 3: The Devils Playhouse TTG','PS3','Telltale Games','USA'),
	('Scott Pilgrim vs The World: The Game','PS3','Ubisoft Montreal','Canada'),
	('Shovel Knight: Treasure Trove','PS3','Yacht Club Games','USA'),
	('Siren: Blood Curse','PS3','Team Asobi (Japan Studio)','Japan'),
	('Skate 2','PS3','EA Black Box','Canada'),
	('Sleeping Dogs','PS3','United Front Games','Canada'),
	('Slender: The Arrival','PS3','Blue Isle Studios','Canada'),
	('Sly Cooper: Thieves in Time','PS3','Sanzaru Games','USA'),
	('Sniper Elite V2','PS3','Rebellion Developments','England'),
	('Sonic CD (1993)','PS3','SEGA (Sonic Team)','Japan'),
	('Sonic Generations','PS3','SEGA (Sonic Team)','Japan'),
	('Sound Shapes','PS3','Queasy Games','Canada'),
	('South Park: The Stick of Truth','PS3','Obsidian Entertainment','USA'),
	('Spec Ops: The Line','PS3','Yager Development','Germany'),
	('Spelunky','PS3','Mossmouth LLC','USA'),
	('Stealth Inc: A Clone in the Dark','PS3','Curve Studios','England'),
	('Stealth Inc 2: A Game of Clones','PS3','Curve Studios','England'),
	('Street Fighter X Tekken','PS3','Capcom','Japan'),
	('Streets of Rage 2','PS3','SEGA','Japan'),
	('Super Rub a Dub','PS3','Sumo Digital','England'),
	('Super Stardust HD','PS3','Housemarque','Finland'),
	('Superfrog HD','PS3','Team17','England'),
	('Syndicate','PS3','Starbreeze Studios','Sweden'),
	('Tales from the Borderlands','PS3','Telltale Games','USA'),
	('Tales of Graces f','PS3','Bandai Namco Studios','Japan'),
	('Tales of Xillia','PS3','Bandai Namco Studios','Japan'),
	('Tekken Revolution','PS3','Bandai Namco Studios','Japan'),
	('Tennis in the Face','PS3','10tons','Finland'),
	('Terraria','PS3','Re-Logic','USA'),
	('The Amazing Spider-Man','PS3','Beenox','Canada'),
	('The Cave','PS3','Double Fine Productions','USA'),
	('The Cube','PS3','Funbox Media','England'),
	('The Darkness','PS3','Starbreeze Studios','Sweden'),
	('The Darkness II','PS3','Digital Extremes','Canada'),
	('The Evil Within','PS3','Tango Gameworks','Japan'),
	('The House of the Dead: Overkill','PS3','SEGA','Japan'),
	('The Last of Us','PS3','Naughty Dog','USA'),
	('The Secret of Monkey Island','PS3','LucasArts','USA'),
	('The Simpsons Arcade Game','PS3','Konami','Japan'),
	('The Sims 3','PS3','Maxis','USA'),
	('The Sims 3: Pets','PS3','Maxis','USA'),
	('The Swapper','PS3','Facepalm Games','Finland'),
	('The Unfinished Swan','PS3','Giant Sparrow','USA'),
	('The Walking Dead: Season 1 TTG','PS3','Telltale Games','USA'),
	('The Walking Dead: Season 2 TTG','PS3','Telltale Games','USA'),
	('The Wolf Among Us Season 1 TTG','PS3','Telltale Games','USA'),
	('Thomas Was Alone','PS3','Bithell Games','England'),
	('Tiger Woods PGA Tour 11','PS3','EA Tiburon','USA'),
	('Titan Attacks!','PS3','Puppy Games','England'),
	('ToeJam and Earl','PS3','Johnson Voorsanger Productions','USA'),
	('ToeJam and Earl in Panic on Funkotron','PS3','Johnson Voorsanger Productions','USA'),
	('Tokyo Jungle','PS3','Team Asobi (Japan Studio)','Japan'),
	('Tomb Raider (2013)','PS3','Crystal Dynamics','USA'),
	('Tony Hawks Pro Skater HD','PS3','Robomodo','USA'),
	('Trine','PS3','Frozenbyte','Finland'),
	('Trine 2','PS3','Frozenbyte','Finland'),
	('Twisted Metal (2012)','PS3','Eat Sleep Play','USA'),
	('UFC 2009 Undisputed','PS3','Yukes','Japan'),
	('Ultratron','PS3','Puppy Games','England'),
	('Uncharted: Drakes Fortune','PS3','Naughty Dog','USA'),
	('Uncharted 2: Among Thieves','PS3','Naughty Dog','USA'),
	('Uncharted 3: Drakes Deception','PS3','Naughty Dog','USA'),
	('UNO','PS3','Ubisoft Chengdu','China'),
	('Virtua Fighter 5','PS3','SEGA','Japan'),
	('Watch Dogs','PS3','Ubisoft Montreal','Canada'),
	('When Vikings Attack','PS3','Clever Beans','England'),
	('Wipeout HD (2008)','PS3','Studio Liverpool','England'),
	('Wolfenstein: The New Order','PS3','MachineGames','Sweden'),
	('Worms Revolution Extreme','PS3','Team17','England'),
	('XCOM: Enemy Unknown','PS3','Firaxis Games','USA'),
	('Yakuza: Dead Souls','PS3','SEGA','Japan'),
	('Yu-Gi-Oh! Millennium Duels','PS3','Other Ocean Interactive','Canada'),
	('Zombie Tycoon 2: Brainhovs Revenge','PS3','Frima Studio','Canada')

-- VITA
INSERT INTO origins
(game, console, developer, country)
VALUES
	('A Boy and His Blob','VITA','WayForward Technologies Inc','USA'),
	('Active Soccer 2 DX','VITA','The Fox Software','Italy'),
	('Bridge Constructor','VITA','ClockStone Studios','Austria'),
	('Broken Age','VITA','Double Fine Productions','USA'),
	('Claire','VITA','Hailstorm Games','USA'),
	('Color Slayer','VITA','The Domaginarium','El Salvador'),
	('Crazy Market','VITA','The Game Atelier','France'),
	('Day of the Tentacle: Remastered','VITA','LucasArts','USA'),
	('Downwell','VITA','Moppin (Ojiro Fumoto)','Japan'),
	('Escape Plan','VITA','Fun Bits Interactive','USA'),
	('Fat Princess: Piece of Cake','VITA','One Loop Games','USA'),
	('Flame Over','VITA','Laughing Jackal Ltd','England'),
	('Football Manager Classic 2014','VITA','Sports Interactive','England'),
	('forma.8','VITA','MixedBag','Italy'),
	('Futuridium EP Deluxe','VITA','MixedBag','Italy'),
	('Get Off My Lawn!','VITA','Digital Leisure Inc','Canada'),
	('Grim Fandango: Remastered','VITA','LucasArts','USA'),
	('Gunslugs','VITA','Abstraction Games','Netherlands'),
	('Hatoful Boyfriend','VITA','Mediatonic','England'),
	('Home: A Unique Horror Adventure','VITA','Benjamin Rivers Inc','Canada'),
	('Minutes','VITA','Red Phantom Games','England'),
	('ModNation Racers: Road Trip','VITA','San Diego Studio','USA'),
	('Ninja Senki DX','VITA','Tribute Games (Jonathan Lavigne)','Canada'),
	('No Heroes Allowed: No Puzzles Either!','VITA','ACQUIRE Corp','Japan'),
	('OlliOlli','VITA','Roll7','England'),
	('OlliOlli 2: Welcome to Olliwood','VITA','Roll7','England'),
	('Paint Park Plus','VITA','Sony Interactive Entertainment','Japan'),
	('Pic-a-Pix Color','VITA','Lightwood Games','England'),
	('PlayStation VITA Pets','VITA','Spiral House','England'),
	('Poltergeist: A Pixelated Horror','VITA','Glitchy Pixel','Colombia'),
	('Quell Memento','VITA','Fallen Tree Games','England'),
	('Rally Copters','VITA','Depth First Games','USA'),
	('Risk of Rain','VITA','Hopoo Games','USA'),
	('Rock Boshers DX: Directors Cut','VITA','Tikipod','England'),
	('Rocketbirds 2: Evolution','VITA','Ratloop Asia','Singapore'),
	('Silent Hill: Book of Memories','VITA','WayForward Technologies Inc','USA'),
	('Skeleton Rider','VITA','iSquared Games','England'),
	('Slain: Back From Hell','VITA','Wolf Brew Games','USA'),
	('Spy Chameleon','VITA','Unfinished Pixel','Spain'),
	('Spy Hunter (2012)','VITA','TT Games','England'),
	('SteamWorld Dig','VITA','Image & Form','Sweden'),
	('SteamWorld Heist','VITA','Image & Form','Sweden'),
	('SteamWorld Dig 2','VITA','Image & Form','Sweden'),
	('Sunflowers','VITA','The Game Atelier','France'),
	('Super Meat Boy','VITA','Team Meat','USA'),
	('Superbeat: Xonic','VITA','Nurijoy','Korea Republic'),
	('Surge Deluxe','VITA','FuturLab','England'),
	('Switch Galaxy Ultra','VITA','Atomicom','England'),
	('Syrup and the Ultimate Sweet','VITA','NomNomNami','USA'),
	('Table Football','VITA','Sony Interactive Entertainment','Japan'),
	('Table Top Racing','VITA','Playrise Digital Ltd','England'),
	('The Binding of Isaac: Rebirth','VITA','Nicalis','USA'),
	('Touch my Katamari','VITA','Bandai Namco Studios','Japan'),
	('Touhou Double Focus','VITA','Aqua Style','Japan'),
	('Twin Robots: Ultimate Edition','VITA','Thinice Games','Spain'),
	('TxK','VITA','Llamasoft','England'),
	('Uncanny Valley','VITA','Cowardly Creations','USA'),
	('Uncharted: Golden Abyss','VITA','Bend Studio','USA'),
	('Uncharted: Fight for Fortune','VITA','Bend Studio','USA'),
	('Undertale','VITA','Toby Fox','USA'),
	('Velocity Ultra','VITA','FuturLab','England'),
	('Velocity 2X','VITA','FuturLab','England'),
	('Wanderjahr','VITA','Workyrie Game Studio','Japan'),
	('Welcome Park','VITA','Sony Interactive Entertainment','Japan'),
	('Wipeout 2048 (2012)','VITA','Studio Liverpool','England'),
	('Xenoraid','VITA','10tons','Finland'),
	('Yomawari: Midnight Shadows','VITA','Nippon Ichi Software','Japan'),
	('Yomawari: Night Alone','VITA','Nippon Ichi Software','Japan'),
	('Zero Escape: Virtues Last Reward','VITA','Spike Chunsoft','Japan')

-- PS4 (A-Z)
INSERT INTO origins
(game, console, developer, country)
VALUES
	('60 Seconds! Reatomized','PS4','Robot Gentleman','Poland'),
	('101 Ways To Die','PS4','Four Door Lemon','England'),
	('A Plague Tale: Innocence','PS4','Asobo Studio','France'),
	('Absolute Drift','PS4','Funselektor Labs Inc','Canada'),
	('Abzu','PS4','Giant Squid Studios','USA'),
	('Aladdin (Disney Classic Games)','PS4','Digital Eclipse','USA'),
	('Alan Wake','PS4','Remedy Entertainment','Finland'),
	('Aliens: Fireteam Elite','PS4','Cold Iron Studios','USA'),
	('Amnesia: The Dark Descent','PS4','Frictional Games','Sweden'),
	('Amnesia: A Machine for Pigs','PS4','The Chinese Room','England'),
	('Amplitude','PS4','Harmonix Music Systems','USA'),
	('Apex Legends','PS4','Respawn Entertainment','USA'),
	('ARK: Survival Evolved','PS4','Studio Wildcard','USA'),
	('Armello','PS4','League of Geeks','Australia'),
	('Armikrog','PS4','Pencil Test Studios','USA'),
	('Art of Balance','PS4','Shin`en Multimedia','Germany'),
	('Art of Rally','PS4','Funselektor Labs Inc','Canada'),
	('Assassins Creed Valhalla','PS4','Ubisoft Montreal','Canada'),
	('Assault Android Cactus','PS4','Witch Beam','Australia'),
	('Aven Colony','PS4','Mothership Entertainment','USA'),
	('AWAY: The Survival Series','PS4','Breaking Walls','Canada'),
	('Axiom Verge 2','PS4','Thomas Happ Games','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Batman: The Telltale Series (Season 1)','PS4','Telltale Games','USA'),
	('Batman: The Enemy Within (Season 2 Telltale)','PS4','Telltale Games','USA'),
	('Batman: Arkham Knight','PS4','Rocksteady Studios','England'),
	('Battlefield 1','PS4','EA DICE','Sweden'),
	('Battlefield 2042','PS4','EA DICE','Sweden'),
	('Bear with Me','PS4','Exordium Games','Croatia'),
	('Beat Cop','PS4','Pixel Crow','Poland'),
	('Beyond Eyes','PS4','Tiger & Squid','Netherlands'),
	('Bio Inc Redemption','PS4','DryGin Studios','Canada'),
	('Biomutant','PS4','Experiment 101','Sweden'),
	('Blacksad: Under the Skin','PS4','Pendulo Studios','Spain'),
	('Blazing Beaks','PS4','Applava','Lithuania'),
	('Blood Bowl 2','PS4','Cyanide','France'),
	('Bloodborne','PS4','FromSoftware','Japan'),
	('Borderlands 3','PS4','Gearbox Software','USA'),
	('Breaking Enigma','PS4','Alphanu Game Studios','England'),
	('Broforce','PS4','Free Lives','South Africa'),
	('Bud Spencer & Terence Hill - Slaps And Beans','PS4','Trinity Team','Italy'),
	('Bugsnax','PS4','Young Horses','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Call of Duty: Black Ops Cold War','PS4','Treyarch','USA'),
	('Call of Duty: Black Ops III','PS4','Treyarch','USA'),
	('Cant Drive This','PS4','Pixel Maniacs','Germany'),
	('Captain Tsubasa: Rise of New Champions','PS4','Tamsoft','Japan'),
	('Celeste','PS4','Maddy Makes Games','Canada'),
	('Chicken Police: Paint It Red!','PS4','The Wild Gentlemen','Hungary'),
	('Chicory: A Colorful Tale','PS4','Wishes Unlimited (Greg Lobanov)','USA'),
	('Chime Sharp','PS4','Twistplay','England'),
	('Chip n Dale Rescue Rangers (1990): The Disney Afternoon Collection','PS4','Capcom','Japan'),
	('Chip n Dale Rescue Rangers 2 (1994): The Disney Afternoon Collection','PS4','Capcom','Japan'),
	('Cities: Skylines','PS4','Colossal Order','Finland'),
	('Cloudpunk','PS4','Ion Lands','Germany'),
	('Clustertruck','PS4','Landfall Games','Sweden'),
	('Code Vein','PS4','Bandai Namco Studios','Japan'),
	('Coffee Talk','PS4','Toge Productions','Indonesia'),
	('Coffee Talk Episode 2: Hibiscus and Butterfly','PS4','Toge Productions','Indonesia'),
	('Concept Destruction','PS4','Thinice Games','Spain'),
	('Concrete Genie','PS4','Pixelopus','USA'),
	('Crash Bandicoot: N Sane Trilogy (2017)','PS4','Vicarious Visions','USA'),
	('Crash Bandicoot 2: N Sane Trilogy (2017)','PS4','Vicarious Visions','USA'),
	('Crash Bandicoot 3: N Sane Trilogy (2017)','PS4','Vicarious Visions','USA'),
	('Crash Bandicoot 4: Its About Time','PS4','Toys For Bob','USA'),
	('Crash Team Racing Nitro-Fueled','PS4','Beenox','Canada'),
	('Croixleur Sigma','PS4','souvenir circ','Japan'),
	('Cult of the Lamb','PS4','Massive Monster','Australia'),
	('Curse of the Dead Gods','PS4','Passtech Games','France'),
	('Cyberpunk 2077','PS4','CD Projekt Red','Poland')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Danger Zone','PS4','Three Fields Entertainment','England'),
	('Dangerous Driving','PS4','Three Fields Entertainment','England'),
	('Dangerous Golf','PS4','Three Fields Entertainment','England'),
	('Dark Souls III','PS4','FromSoftware','Japan'),
	('Darkwing Duck (1992): The Disney Afternoon Collection','PS4','Capcom','Japan'),
	('Days Gone','PS4','Bend Studio','USA'),
	('de Blob','PS4','Blue Tongue Entertainment','Australia'),
	('Dead End Job','PS4','Ant Workshop','Scotland'),
	('Dead Island: Retro Revenge','PS4','Empty Clip Studios','USA'),
	('Dead Island 2','PS4','Dambuster Studios (Deep Silver)','England'),
	('Dead Rising','PS4','Capcom','Japan'),
	('Death Squared','PS4','SMG Studio','Australia'),
	('Deaths Door','PS4','Acid Nerve','England'),
	('DEEEER Simulator','PS4','Gibier Games','Japan'),
	('Deep Rock Galactic','PS4','Ghost Ship Games','Denmark'),
	('Descenders','PS4','RageSquid','Netherlands'),
	('Destiny 2','PS4','Bungie','USA'),
	('Destroy All Humans! (2020)','PS4','Black Forest Games','Germany'),
	('Detroit: Become Human','PS4','Quantic Dream','France'),
	('Devil May Cry 5','PS4','Capcom','Japan'),
	('Dex','PS4','Dreadlocks Ltd','Czech Republic'),
	('Digimon World: Next Order','PS4','B.B. Studio','Japan'),
	('DIRT 5','PS4','Codemasters','England'),
	('Discovery','PS4','Noowanda','Germany'),
	('Disney Dreamlight Valley','PS4','Gameloft Montreal','Canada'),
	('Dont Starve','PS4','Klei Entertainment','Canada'),
	('Donut County','PS4','Ben Esposito','USA'),
	('DOOM 64','PS4','Midway Games','USA'),
	('Doraemon: Story of Seasons','PS4','Brownies (Marvelous Interactive)','Japan'),
	('DreamBall','PS4','Rampage Game Studios','Spain'),
	('Dreams','PS4','Media Molecule','England'),
	('DuckTales (1989): The Disney Afternoon Collection','PS4','Capcom','Japan'),
	('DuckTales 2 (1993): The Disney Afternoon Collection','PS4','Capcom','Japan'),
	('Dungeon Munchies','PS4','maJAJa','Taiwan')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('EA Sports FC 24','PS4','EA Vancouver','Canada'),
	('EA Sports UFC 4','PS4','EA Vancouver','Canada'),
	('Elden Ring','PS4','FromSoftware','Japan'),
	('Empire of Sin','PS4','Romero Games','Republic of Ireland'),
	('Ender Lilies: Quietus of the Knights','PS4','Adglobe Live Wire','Japan'),
	('Endling: Extinction is Forever','PS4','Herobeat Studios','Spain'),
	('Enter the Gungeon','PS4','Dodge Roll','USA'),
	('Entwined','PS4','Pixelopus','USA'),
	('Everybodys Golf (2017)','PS4','Clap Hanz','Japan'),
	('Evil Inside','PS4','JanduSoft','Spain'),
	('Exit the Gungeon','PS4','Dodge Roll','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('F1 2021','PS4','Codemasters','England'),
	('F1 23','PS4','Codemasters','England'),
	('F1 Manager 2022','PS4','Frontier Developments','England'),
	('Fall Guys: Ultimate Knockout','PS4','Mediatonic','England'),
	('Fallout 4','PS4','Bethesda Game Studios','USA'),
	('Fallout Shelter','PS4','Bethesda Game Studios','USA'),
	('Far Cry: Primal','PS4','Ubisoft Montreal','Canada'),
	('Far Cry 5','PS4','Ubisoft Montreal','Canada'),
	('Far Cry: New Dawn','PS4','Ubisoft Montreal','Canada'),
	('Far Cry 6','PS4','Ubisoft Toronto','Canada'),
	('Farming Simulator 22','PS4','GIANTS Software','Switzerland'),
	('Fat Princess Adventures','PS4','Fun Bits Interactive','USA'),
	('FIFA 20','PS4','EA Vancouver','Canada'),
	('FIFA 21','PS4','EA Vancouver','Canada'),
	('FIFA 22','PS4','EA Vancouver','Canada'),
	('FIFA 23','PS4','EA Vancouver','Canada'),
	('Final Fantasy VII (2020)','PS4','Square Enix','Japan'),
	('Final Fantasy XV','PS4','Square Enix','Japan'),
	('First Class Trouble','PS4','Invisible Walls','Denmark'),
	('Five Dates','PS4','Wales Interactive','Wales'),
	('Flashback: Remastered Edition','PS4','Delphine Software International','France'),
	('Flockers','PS4','Team17','England'),
	('Formula Retro Racing','PS4','Repixel8','England'),
	('Fortnite','PS4','Epic Games','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Game of Thrones: A Telltale Games Series','PS4','Telltale Games','USA'),
	('Generation Zero','PS4','Systemic Reaction','Sweden'),
	('Genshin Impact','PS4','miHoYo','China'),
	('Ghost Blade HD','PS4','Hucast Games','Germany'),
	('Ghost of Tsushima','PS4','Sucker Punch Productions','USA'),
	('Ghostbusters','PS4','FireForge Games','USA'),
	('Ghostrunner','PS4','Slipgate Ironworks','Denmark'),
	('God of War (2018)','PS4','Santa Monica Studio','USA'),
	('Godlike Burger','PS4','Liquid Pug','Belarus'),
	('Going Under','PS4','Aggro Crab','USA'),
	('Good Dog Bad Dog','PS4','Play-Em','USA'),
	('Granblue Fantasy: Versus','PS4','Arc System Works','Japan'),
	('Grand Ages: Medieval','PS4','Gaming Minds Studios','Germany'),
	('GRID Legends','PS4','Codemasters','England'),
	('Grindstone','PS4','Capybara Games','Canada')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Harry Potter: Quidditch Champions','PS4','Unbroken Studios','USA'),
	('Harvest Moon: Light of Hope','PS4','Tabot Inc','Japan'),
	('Heart&Slash','PS4','aheartfulofgames','Spain'),
	('Heavenly Bodies','PS4','2pt Interactive','Australia'),
	('Helldivers','PS4','Arrowhead Game Studios','Sweden'),
	('Hitman 2','PS4','IO Interactive','Denmark'),
	('Hollow Knight','PS4','Team Cherry','Australia'),
	('Holy Potatoes! A Weapon Shop?!','PS4','Daylight Studios','Singapore'),
	('Holy Potatoes! Were in Space?!','PS4','Daylight Studios','Singapore'),
	('Holy Potatoes! What the Hell?!','PS4','Daylight Studios','Singapore'),
	('HoPiKo','PS4','Laser Dog','England'),
	('Horizon Zero Dawn','PS4','Guerrilla Games','Netherlands'),
	('Horizon Forbidden West','PS4','Guerrilla Games','Netherlands'),
	('Hot Wheels Unleashed','PS4','Milestone','Italy'),
	('Hue','PS4','Fiddlesticks','England'),
	('Human: Fall Flat','PS4','No Brakes Games','Lithuania')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('I am Bread','PS4','Bossa Studios','England'),
	('In Rays of the Light','PS4','Sergey Noskov','Russia'),
	('inFamous Second Son','PS4','Sucker Punch Productions','USA'),
	('inFamous First Light','PS4','Sucker Punch Productions','USA'),
	('Infliction: Extended Cut','PS4','Caustic Reality','Australia'),
	('Injustice 2','PS4','NetherRealm Studios','USA'),
	('Iris and the Giant','PS4','Louis Rigaud','France'),
	('It Takes Two','PS4','Hazelight Studios','Sweden')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Jazzpunk: Directors Cut','PS4','Necrophone Games','Canada'),
	('Judgment','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Jurassic World Evolution 2','PS4','Frontier Developments','England'),
	('Just Die Already','PS4','DoubleMoose Games','Sweden')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Kandagawa Jet Girls','PS4','Honey Parade Games','Japan'),
	('Katamari Damacy','PS4','Bandai Namco Studios','Japan'),
	('Kena: Bridge of Spirits','PS4','Ember Lab','USA'),
	('Kerbal Space Program','PS4','Squad','Mexico'),
	('Kingdom Hearts 3D: Dream Drop Distance and Back Cover (HD 2.8 Final Chapter Prologue)','PS4','Square Enix','Japan'),
	('Kingdom Hearts 0.2 Birth by Sleep - A Fragmentary Passage (HD 2.8 Final Chapter Prologue)','PS4','Square Enix','Japan'),
	('Kingdom Hearts III','PS4','Square Enix','Japan'),
	('Klonoa: Door to Phantomile (2008)','PS4','Paon','Japan'),
	('Knack','PS4','Team Asobi (Japan Studio)','Japan'),
	('Knack 2','PS4','Team Asobi (Japan Studio)','Japan'),
	('Knockout City','PS4','Velan Studios','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('LA Cops','PS4','Modern Dream','England'),
	('LEGO 2K Drive','PS4','Visual Concepts','USA'),
	('LEGO City Undercover','PS4','TT Games (Travellers Tales)','England'),
	('LEGO DC Super-Villains','PS4','TT Games (Travellers Tales)','England'),
	('LEGO Star Wars: The Skywalker Saga','PS4','TT Games (Travellers Tales)','England'),
	('Leisure Suit Larry - Wet Dreams Dont Dry','PS4','CrazyBunch','Germany'),
	('Leisure Suit Larry - Wet Dreams Dry Twice','PS4','CrazyBunch','Germany'),
	('Lichtspeer','PS4','Lichthund','Poland'),
	('Like a Dragon (Yakuza 0)','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon Kiwami (Yakuza Kiwami)','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon: Ishin','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon Kiwami 2 (Yakuza Kiwami 2)','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon 6 (Yakuza 6: The Song of Life)','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon 7 (Yakuza 7)','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon Gaiden: The Man Who Erased His Name','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Like a Dragon: Infinite Wealth','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Little Nightmares','PS4','Tarsier Studios','Sweden'),
	('Little Nightmares II','PS4','Tarsier Studios','Sweden'),
	('Lost Judgment','PS4','Ryu Ga Gotoku Studio','Japan'),
	('Lovers in a Dangerous Spacetime','PS4','Asteroid Base','Canada'),
	('LUMO','PS4','Triple Eh? Ltd','Wales')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Mafia: Definitive Edition (2020)','PS4','Hangar 13 (2K Czech)','USA'),
	('Mafia III','PS4','Hangar 13 (2K Czech)','USA'),
	('Maneater','PS4','Tripwire Interactive','USA'),
	('Manual Samuel','PS4','Perfectly Paranormal','Norway'),
	('Maquette','PS4','Graceful Decay','USA'),
	('Marvels Guardians of the Galaxy: The Telltale Series','PS4','Telltale Games','USA'),
	('Marvels Spider-Man','PS4','Insomniac Games','USA'),
	('Marvels Spider-Man: Miles Morales','PS4','Insomniac Games','USA'),
	('MediEvil (2019)','PS4','Other Ocean Emeryville','USA'),
	('Meet Your Maker','PS4','Behaviour Interactive (Artificial Mind and Movement)','Canada'),
	('Mega Man (Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man 2 (Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man 3 (Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man 4 (Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man 5 (Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man 6 (Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man 7 (Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man 8 (Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man 9 (Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man 10 (Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man X (X Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man X2 (X Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man X3 (X Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man X4 (X Legacy Collection)','PS4','Capcom','Japan'),
	('Mega Man X5 (X Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man X6 (X Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man X7 (X Legacy Collection 2)','PS4','Capcom','Japan'),
	('Mega Man X8 (X Legacy Collection 2)','PS4','Capcom','Japan'),
	('Metro 2033','PS4','4A Games','Ukraine'),
	('Metro Exodus','PS4','4A Games','Ukraine'),
	('Micro Machines World Series','PS4','Codemasters','England'),
	('Minecraft Dungeons','PS4','Mojang Studios','Sweden'),
	('Minecraft Legends','PS4','Mojang Studios','Sweden'),
	('MLB The Show 24','PS4','San Diego Studio','USA'),
	('My Monopoly (Monopoly Family Fun Pack)','PS4','Asobo Studio','France'),
	('Monster Hunter: World','PS4','Capcom','Japan'),
	('Monster Prom: XXL','PS4','Beautiful Glitch','Spain'),
	('Moonshine Inc','PS4','Klabater','Poland'),
	('Mortal Kombat X','PS4','NetherRealm Studios','USA'),
	('Mortal Shell','PS4','Cold Symmetry','USA'),
	('Mother Russia Bleeds','PS4','Le Cartel Studio','France'),
	('Music Racer: Ultimate','PS4','Sometimes You','Russia')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('NBA 2K23','PS4','Visual Concepts','USA'),
	('Need for Speed Heat','PS4','EA Gothenburg (Ghost Games)','Sweden'),
	('Neon Chrome','PS4','10tons','Finland'),
	('Neon Drive','PS4','Fraoula','Slovenia'),
	('New Tales from the Borderlands','PS4','Gearbox Quebec','Canada'),
	('NHL 24','PS4','EA Vancouver','Canada'),
	('Ni No Kuni II: Revenant Kingdom','PS4','Level-5','Japan'),
	('Nickelodeon All-Star Brawl','PS4','Ludosity','Sweden'),
	('Night Book','PS4','Wales Interactive','Wales'),
	('Nioh 2','PS4','Team Ninja','Japan'),
	('No Mans Sky','PS4','Hello Games','England'),
	('Nobody Saves The World','PS4','Drinkbox Studios','Canada'),
	('Nour: Play With Your Food','PS4','Terrifying Jellyfish','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Octodad: Dadliest Catch','PS4','Young Horses','USA'),
	('Oddworld: New n Tasty','PS4','Just Add Water','England'),
	('Oddworld: Soulstorm (2021)','PS4','Oddworld Inhabitants','USA'),
	('OlliOlli World','PS4','Roll7','England'),
	('One Escape','PS4','BUG-Studio','Russia'),
	('Outbreak: Epidemic','PS4','Dead Drop Studios LLC','USA'),
	('Outlast','PS4','Red Barrels','Canada'),
	('Overcooked','PS4','Ghost Town Games','England'),
	('Overcooked 2','PS4','Ghost Town Games','England'),
	('Ovivo','PS4','IzHard','Russia'),
	('Oxenfree','PS4','Night School Studio','USA'),
	('Oxenfree II: Lost Signals','PS4','Night School Studio','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('PAC-MAN 256','PS4','Hipster Whale','Australia'),
	('Party Hard','PS4','Pinokl Games','Ukraine'),
	('Party Hard 2','PS4','Pinokl Games','Ukraine'),
	('Persona 5 Strikers','PS4','Omega Force','Japan'),
	('PGA Tour 2K21','PS4','HB Studios','Canada'),
	('Planet Coaster','PS4','Frontier Developments','England'),
	('Plants vs Zombies: Battle for Neighborville','PS4','PopCap Games','USA'),
	('Please Dont Touch Anything','PS4','Four Quarters','Russia'),
	('Polybius','PS4','Llamasoft','England'),
	('PONG Quest','PS4','Chequered Ink Ltd','England'),
	('Postal Redux','PS4','Running With Scissors','USA'),
	('Postal 4: No Regerts','PS4','Running with Scissors','USA'),
	('Potion Permit','PS4','MassHive Media','Indonesia'),
	('PowerWash Simulator','PS4','FuturLab','England'),
	('Psychonauts 2','PS4','Double Fine Productions','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Quake','PS4','id Software','USA'),
	('Quest of Dungeons','PS4','Upfall Studios','Portugal')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Ratchet & Clank (2016)','PS4','Insomniac Games','USA'),
	('Red Dead Redemption 2','PS4','Rockstar San Diego','USA'),
	('Resident Evil 2 (2019)','PS4','Capcom','Japan'),
	('Resident Evil 3 (2020)','PS4','Capcom','Japan'),
	('Resident Evil 4 (2023)','PS4','Capcom','Japan'),
	('Resident Evil VII: Biohazard','PS4','Capcom','Japan'),
	('Resident Evil: Resistance','PS4','Capcom','Japan'),
	('Resident Evil: Re:Verse','PS4','Capcom','Japan'),
	('Resident Evil Village','PS4','Capcom','Japan'),
	('RESOGUN','PS4','Housemarque','Finland'),
	('Riptide GP: Renegade','PS4','Vector Unit','USA'),
	('Rise of the Tomb Raider','PS4','Crystal Dynamics','USA'),
	('Road Redemption','PS4','EQ-Games','USA'),
	('Rocket League','PS4','Psyonix','USA'),
	('Rogue Company','PS4','First Watch Games','USA'),
	('Rollercoaster Dreams','PS4','Bimboosoft','Japan'),
	('Rollerdrome','PS4','Roll7','England'),
	('Run Sausage Run!','PS4','CrazyLabs','Israel'),
	('Rustler (Grand Theft Horse)','PS4','Jutsu Games','Poland')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Sabans Mighty Morphin Power Rangers: Mega Battle','PS4','Bamtang Games','Peru'),
	('Sackboy: A Big Adventure','PS4','Sumo Digital','England'),
	('Saints Row (2022)','PS4','Deep Silver Volition','USA'),
	('Sam & Max Season 1: Save the World TTG','PS4','Telltale Games','USA'),
	('Scribblenauts Unlimited (Mega Pack)','PS4','5th Cell','USA'),
	('Scribblenauts Unmasked: A DC Comics Adventure (Mega Pack)','PS4','5th Cell','USA'),
	('Sekiro: Shadows Die Twice','PS4','FromSoftware','Japan'),
	('Shadow of the Tomb Raider','PS4','Eidos Montreal','Canada'),
	('Shantae and the Pirates Curse','PS4','WayForward Technologies Inc','USA'),
	('Shing','PS4','Mass Creation','Poland'),
	('Shovel Knight: Pocket Dungeon','PS4','Yacht Club Games','USA'),
	('Shred It','PS4','Extra Mile Studios','Scotland'),
	('Sifu','PS4','Sloclap','France'),
	('Sir Lovelot','PS4','pixel.lu','Luxembourg'),
	('Skul: The Hero Slayer','PS4','SouthPAW Games','Korea Republic'),
	('Slay the Spire','PS4','Mega Crit','USA'),
	('Sonic the Hedgehog (1991): Sonic Origins (2022)','PS4','SEGA','Japan'),
	('Sonic the Hedgehog 2 (1992): Sonic Origins (2022)','PS4','SEGA','Japan'),
	('Sonic the Hedgehog 3 & Knuckles (1994): Sonic Origins (2022)','PS4','SEGA','Japan'),
	('Sonic Mania','PS4','Christian Whitehead','Australia'),
	('SoulCalibur VI','PS4','Bandai Namco Studios','Japan'),
	('South Park: The Fractured But Whole','PS4','Ubisoft San Francisco','USA'),
	('Spacebase Startopia','PS4','Realmforge Studios','Germany'),
	('Spirit of the North','PS4','Infuse Studio','USA'),
	('SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated','PS4','Purple Lamp Studios','Austria'),
	('SpongeBob SquarePants: The Cosmic Shake','PS4','Purple Lamp Studios','Austria'),
	('Spyro the Dragon: Reignited Trilogy (2018)','PS4','Toys for Bob','USA'),
	('Spyro 2: Gateway to Glimmer: Reignited Trilogy (2018)','PS4','Toys for Bob','USA'),
	('Spyro 3: Year of the Dragon: Reignited Trilogy (2018)','PS4','Toys for Bob','USA'),
	('Star Wars Episode I: Pod Racer','PS4','LucasArts','USA'),
	('Star Wars Jedi: Fallen Order','PS4','Respawn Entertainment','USA'),
	('Stardew Valley','PS4','ConcernedApe (Eric Barone)','USA'),
	('Stikbold! A Dodgeball Adventure','PS4','Game Swing','Denmark'),
	('Stranded Deep','PS4','Beam Team Games','Australia'),
	('Stray','PS4','BlueTwelve Studio','France'),
	('Street Fighter II Turbo: Hyper Fighting (1992)','PS4','Capcom','Japan'),
	('Super Street Fighter II: The New Challengers (1993)','PS4','Capcom','Japan'),
	('Street Fighter (1987): 30th Anniversary Collection','PS4','Capcom','Japan'),
	('Street Fighter II: The World Warrior (1991): 30th Anniversary Collection','PS4','Capcom','Japan'),
	('Street Fighter II: Champion Edition (1992): 30th Anniversary Collection','PS4','Capcom','Japan'),
	('Street Fighter III: 3rd Strike - Fight for the Future (1999)','PS4','Capcom','Japan'),
	('Street Fighter III: New Generation (1997): 30th Anniversary Collection','PS4','Capcom','Japan'),
	('Street Fighter III: 2nd Impact - Giant Attack: 30th Anniversary Collection','PS4','Capcom','Japan'),
	('Subnautica','PS4','Unknown Worlds Entertainment','USA'),
	('Subnautica: Below Zero','PS4','Unknown Worlds Entertainment','USA'),
	('Sumatra: Fate of Yandi','PS4','Cloak and Dagger Games','England'),
	('Super Kickers League','PS4','Xaloc Studios','Spain'),
	('Super Monkey Ball: Banana Blitz HD','PS4','SEGA','Japan'),
	('Supermarket Shriek','PS4','Billy Goat Entertainment Ltd','Northern Ireland'),
	('Surgeon Simulator','PS4','Bossa Studios','England')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Table Top Racing: World Tour','PS4','Playrise Digital Ltd','England'),
	('Tails of Iron','PS4','Odd Bug Studios','England'),
	('TaleSpin (1991): The Disney Afternoon Collection','PS4','Capcom','Japan'),
	('Tchia','PS4','Awaceb','France'),
	('Team Sonic Racing','PS4','Sumo Digital','England'),
	('Tearaway Unfolded','PS4','Media Molecule','England'),
	('Tekken 7','PS4','Bandai Namco Studios','Japan'),
	('Tembo the Badass Elephant','PS4','Game Freak','Japan'),
	('Tennis World Tour 2','PS4','Big Ant Studios','Australia'),
	('Terminator: Resistance','PS4','Teyon','Poland'),
	('Tethered','PS4','Secret Sorcery','England'),
	('Tetris Effect','PS4','Monstars','Japan'),
	('Tetris Ultimate','PS4','SoMa Play','USA'),
	('Thats You!','PS4','Wish Studios','England'),
	('The Amazing American Circus','PS4','Juggler Games','Poland'),
	('The Bug Butcher','PS4','Awfully Nice Studios','Austria'),
	('The Callisto Protocol','PS4','Striking Distance Studios','USA'),
	('The Complex','PS4','Wales Interactive','Wales'),
	('The Crew','PS4','Ivory Tower','France'),
	('The Darkside Detective','PS4','Spooky Doorway','Republic of Ireland'),
	('The Darkside Detective Season 2: A Fumble in the Dark','PS4','Spooky Doorway','Republic of Ireland'),
	('The Escapists','PS4','Mouldy Toof Studios','England'),
	('The Flame in the Flood','PS4','The Molasses Flood','USA'),
	('The Last Guardian','PS4','Team Asobi (Japan Studio)','Japan'),
	('The Last of Us Part II','PS4','Naughty Dog','USA'),
	('The Lion King (Disney Classic Games)','PS4','Digital Eclipse','USA'),
	('The Outer Worlds','PS4','Obsidian Entertainment','USA'),
	('The Pedestrian','PS4','Skookum Arts','USA'),
	('The Persistence','PS4','Firesprite','England'),
	('The Playroom','PS4','Team Asobi (Japan Studio)','Japan'),
	('The Sims 4','PS4','Maxis','USA'),
	('The Sinking City','PS4','Frogwares','Ukraine'),
	('The Stanley Parable: Ultra Deluxe','PS4','Crows Crows Crows','Germany'),
	('The Survivalists','PS4','Mouldy Toof Studios','England'),
	('The Walking Dead Season 3 TTG','PS4','Telltale Games','USA'),
	('The Walking Dead Final Season TTG','PS4','Telltale Games','USA'),
	('The Witcher 3: Wild Hunt','PS4','CD Projekt Red','Poland'),
	('The Witness','PS4','Thekla Inc','USA'),
	('Think of the Children','PS4','Jammed Up Studios','Australia'),
	('This Is The Police','PS4','Weappy Studio','Belarus'),
	('Tiny Tinas Wonderlands','PS4','Gearbox Software','USA'),
	('ToeJam and Earl: Back in the Groove','PS4','HumaNature Studios','USA'),
	('Tony Hawk`s Pro Skater 1 (2021)','PS4','Vicarious Visions','USA'),
	('Tony Hawk`s Pro Skater 2 (2021)','PS4','Vicarious Visions','USA'),
	('Total Arcade Racing','PS4','Pretty Fly Studios','Sweden'),
	('Trackmania Turbo','PS4','Nadeo','France'),
	('Trek to Yomi','PS4','Flying Wild Hog','Poland'),
	('Trials Fusion','PS4','RedLynx','France'),
	('Tribes of Midgard','PS4','Norsfell Games','Canada'),
	('Tricky Towers','PS4','WeirdBeard','Netherlands'),
	('Trine 3: The Artifacts of Power','PS4','Frozenbyte','Finland'),
	('Tropico 5','PS4','Haemimont Games','Bulgaria'),
	('Trover Saves The Universe','PS4','Squanch Games','USA'),
	('Tunic','PS4','Isometricorp Games','Canada'),
	('Turnip Boy Commits Tax Evasion','PS4','Snoozy Kazoo','USA'),
	('Two Point Hospital','PS4','Two Point Studios','England'),
	('Two Point Campus','PS4','Two Point Studios','England'),
	('Typoman','PS4','Brainseed Factory','Germany')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Unbox: Newbies Adventure','PS4','Prospect Games','England'),
	('Uncharted 4: A Thiefs End','PS4','Naughty Dog','USA'),
	('Uncharted: The Lost Legacy','PS4','Naughty Dog','USA'),
	('Unravel','PS4','Coldwood Interactive','Sweden'),
	('Until Dawn','PS4','Supermassive Games','England'),
	('Untitled Goose Game','PS4','House House','Australia')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Viking Squad','PS4','Slick Entertainment','Canada'),
	('Volume','PS4','Bithell Games','England')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('Warframe','PS4','Digital Extremes','Canada'),
	('Watch_Dogs 2','PS4','Ubisoft Montreal','Canada'),
	('Watch_Dogs: Legion','PS4','Ubisoft Toronto','Canada'),
	('Weedcraft Inc','PS4','Vile Monarch','Poland'),
	('Weird West','PS4','WolfEye Studios','France'),
	('while true: learn( )','PS4','Luden.io','Russia'),
	('Wolfenstein: The Old Blood','PS4','MachineGames','Sweden'),
	('Wolfenstein II: The New Colossus','PS4','MachineGames','Sweden'),
	('Wolfenstein: Youngblood','PS4','MachineGames','Sweden'),
	('Wonder Boy: The Dragons Trap','PS4','Lizardcube','France'),
	('Worms Battlegrounds','PS4','Team17','England'),
	('Worms Rumble','PS4','Team17','England'),
	('Worms W.M.D','PS4','Team17','England'),
	('WRC 6','PS4','Kylotonn','France'),
	('Wreckfest','PS4','Bugbear Entertainment','Finland'),
	('WWE 2K Battlegrounds','PS4','Saber Interactive','USA')

INSERT INTO origins
(game, console, developer, country)
VALUES
	('XCOM 2','PS4','Firaxis Games','USA'),
	('Yooka-Laylee','PS4','Playtonic Games','England'),
	('Yooka-Laylee and the Impossible Lair','PS4','Playtonic Games','England'),
	('Yu-Gi-Oh! Legacy of the Duelist','PS4','Other Ocean Interactive','Canada'),
	('Zombie Zone (The Onee Chanbara)','PS4','Tamsoft','Japan'),
	('Zombie Zone 2 (The Onee Chanbara 2)','PS4','Tamsoft','Japan')

-- VR
INSERT INTO origins
(game, console, developer, country)
VALUES
	('Accounting Plus','VR','Squanch Games','USA'),
	('Animal Force','VR','ISVR','China'),
	('Apex Construct','VR','Fast Travel Games','Sweden'),
	('Apocalypse Rider','VR','VRMonkey','Brazil'),
	('Arizona Sunshine','VR','Vertigo Games','Netherlands'),
	('ASTRO BOT Rescue Mission','VR','Team Asobi (Japan Studio)','Japan'),
	('Batman: Arkham VR','VR','Rocksteady Studios','England'),
	('Beat Saber','VR','Beat Games','Czech Republic'),
	('BoxVR','VR','FitXR','USA'),
	('Budget Cuts','VR','Neat Corporation','Sweden'),
	('Carnival Games VR','VR','Cat Daddy Games','USA'),
	('Catch & Release','VR','metricminds','Germany'),
	('Coolpaintr VR','VR','Wildbit Studios','Spain'),
	('Creed: Rise to Glory','VR','Survios','USA'),
	('DOOM VFR','VR','id Software','USA'),
	('Dream Match Tennis VR','VR','Bimboosoft','Japan'),
	('Driveclub VR','VR','Evolution Studios','England'),
	('Drunkn Bar Fight','VR','The Munky','USA'),
	('Eagle Flight','VR','Ubisoft Montreal','Canada'),
	('EVE: Valkyrie - Warzone','VR','CCP Games','Iceland'),
	('Everybodys Golf VR','VR','Clap Hanz','Japan'),
	('Floor Plan','VR','Turbo Button','USA'),
	('Fruit Ninja VR','VR','Halfbrick Studios','Australia'),
	('Groundhog Day: Like Father Like Son','VR','Tequila Works','Spain'),
	('Gun Club VR','VR','The Binary Mill','Australia'),
	('Headmaster','VR','Frame Interactive','USA'),
	('Horror Bar VR','VR','VR Factory','Poland'),
	('Hotel R n R','VR','Wolf & Wood Interactive Ltd','England'),
	('Hustle Kings VR','VR','VooFoo Studios','England'),
	('I Expect You To Die','VR','Schell Games','USA'),
	('I Expect You to Die 2: The Spy and the Liar','VR','Schell Games','USA'),
	('Job Simulator: The 2050 Archives','VR','Owlchemy Labs','USA'),
	('Keep Talking and Nobody Explodes','VR','Steel Crate Games','Canada'),
	('Kingdom Hearts: VR Experience','VR','Square Enix','Japan'),
	('Knockout League','VR','Grab Games','USA'),
	('Kona VR','VR','Parabole','Canada'),
	('Lethal VR','VR','Three Fields Entertainment','England'),
	('Marvels Iron Man VR','VR','Camouflaj','USA'),
	('Mervils: A VR Adventure','VR','VitruviusVR','Canada'),
	('Moss','VR','Polyarc','USA'),
	('Penn and Teller VR','VR','Gearbox Software','USA'),
	('PlayStation VR Worlds','VR','London Studio','England'),
	('Psychonauts in the Rhombus of Ruin VR','VR','Double Fine Productions','USA'),
	('Rez Infinite VR','VR','Enhance Games','USA'),
	('Rick and Morty: Virtual Rick-ality','VR','Owlchemy Labs','USA'),
	('RIGS: Mechanized Combat League VR','VR','Guerrilla Cambridge','England'),
	('Sam and Max: This Time Its Virtual!','VR','HappyGiant','USA'),
	('Shooty Fruity','VR','nDreams','England'),
	('Sniper Elite VR','VR','Just Add Water','England'),
	('Space Pirate Trainer','VR','I-Illusions','Belgium'),
	('Sprint Vector','VR','Survios','USA'),
	('Star Trek: Bridge Crew','VR','Red Storm Entertainment','USA'),
	('Superhot VR','VR','Superhot Team','Poland'),
	('The American Dream','VR','Samurai Punk','Australia'),
	('The Elder Scrolls V: Skyrim VR','VR','Bethesda Game Studios','USA'),
	('The Guy VR','VR','Chubby Pixel','Italy'),
	('The Playroom VR','VR','Team Asobi (Japan Studio)','Japan'),
	('The Walking Dead: Saints and Sinners','VR','Skydance Interactive','USA'),
	('Tiny Trax','VR','FuturLab','England'),
	('Track Lab','VR','Little Chicken','Netherlands'),
	('Traffic Jams','VR','Little Chicken','Netherlands'),
	('Tumble VR','VR','Supermassive Games','England'),
	('Ultrawings','VR','Bit Planet Games','USA'),
	('Until Dawn: Rush of Blood','VR','Supermassive Games','England'),
	('Until You Fall','VR','WayTooManyGames','USA'),
	('VR Karts','VR','Viewpoint Games','England'),
	('VR Ping Pong','VR','Reddoll Srl','Italy'),
	('VR The Diner Duo','VR','Whirlybird Games','Sweden'),
	('Wanderer','VR','Oddboy','New Zealand'),
	('You Are Being Followed','VR','Uncommon Chocolate','Scotland')

-- PS5
INSERT INTO origins
(game, console, developer, country)
VALUES
	('A Plague Tale: Requiem','PS5','Asobo Studio','France'),
	('Animal Well','PS5','Shared Memory','USA'),
	('Astro Bot','PS5','Team Asobi (Japan Studio)','Japan'),
	('Astros Playroom','PS5','Team Asobi (Japan Studio)','Japan'),
	('Dead Space (2023)','PS5','Motive Studio','Canada'),
	('Destroy All Humans! 2: Reprobed','PS5','Black Forest Games','Germany'),
	('Final Fantasy VII: Rebirth (2024)','PS5','Square Enix','Japan'),
	('Ghostwire: Tokyo','PS5','Tango Gameworks','Japan'),
	('Goat Simulator 3','PS5','Coffee Stain Studios','Sweden'),
	('Godfall','PS5','Counterplay Games','USA'),
	('Hell Let Loose','PS5','Black Matter Games','Australia'),
	('Hogwarts Legacy','PS5','Avalanche Software','USA'),
	('Marvels Spider-Man 2','PS5','Insomniac Games','USA'),
	('Pacific Drive','PS5','Ironwood Studios','USA'),
	('Planet Zoo','PS5','Frontier Developments','England'),
	('Ratchet & Clank: Rift Apart','PS5','Insomniac Games','USA'),
	('Returnal','PS5','Housemarque','Finland'),
	('RoboCop: Rogue City','PS5','Teyon','Poland'),
	('Sable','PS5','Shedworks','England'),
	('Steelrising','PS5','Spiders','France'),
	('The Plucky Squire','PS5','All Possible Futures','England'),
	('TOEM: A Photo Adventure','PS5','Something We Made','Sweden')