-- Platinums
	SELECT * FROM platinums
	-- UPDATE TABLE SET FIELD = REPLACE(FIELD, 'OLD VALUE', 'NEW VALUE') WHERE ID = NUMBER
		-- Updating the rarity percentage for platinum games at the beginning of each year (2025 onwards)
			UPDATE platinums SET rarity = REPLACE(rarity, 17.5, 6.7) WHERE ID = 1
			UPDATE platinums SET rarity = REPLACE(rarity, 8.5, 6.7) WHERE ID = 2
			UPDATE platinums SET rarity = REPLACE(rarity, 39.6, 6.7) WHERE ID = 3
			UPDATE platinums SET rarity = REPLACE(rarity, 45.8, 6.7) WHERE ID = 4
			UPDATE platinums SET rarity = REPLACE(rarity, 20.9, 6.7) WHERE ID = 5
			UPDATE platinums SET rarity = REPLACE(rarity, 19.1, 6.7) WHERE ID = 6
			UPDATE platinums SET rarity = REPLACE(rarity, 16.4, 6.7) WHERE ID = 7
			UPDATE platinums SET rarity = REPLACE(rarity, 23.7, 6.7) WHERE ID = 8
			UPDATE platinums SET rarity = REPLACE(rarity, 3.3, 6.7) WHERE ID = 9
			UPDATE platinums SET rarity = REPLACE(rarity, 2.7, 6.7) WHERE ID = 10
			UPDATE platinums SET rarity = REPLACE(rarity, 7.9, 6.7) WHERE ID = 11
			UPDATE platinums SET rarity = REPLACE(rarity, 5.7, 6.7) WHERE ID = 12
			UPDATE platinums SET rarity = REPLACE(rarity, 5.6, 6.7) WHERE ID = 13
			UPDATE platinums SET rarity = REPLACE(rarity, 8.5, 6.7) WHERE ID = 14
			UPDATE platinums SET rarity = REPLACE(rarity, 3.3, 6.7) WHERE ID = 15
			UPDATE platinums SET rarity = REPLACE(rarity, 0.4, 6.7) WHERE ID = 16
			UPDATE platinums SET rarity = REPLACE(rarity, 94.6, 6.7) WHERE ID = 17
			UPDATE platinums SET rarity = REPLACE(rarity, 18.3, 6.7) WHERE ID = 18
			UPDATE platinums SET rarity = REPLACE(rarity, 4.7, 6.7) WHERE ID = 19
			UPDATE platinums SET rarity = REPLACE(rarity, 1.6, 6.7) WHERE ID = 20
			UPDATE platinums SET rarity = REPLACE(rarity, 2.9, 6.7) WHERE ID = 21
			UPDATE platinums SET rarity = REPLACE(rarity, 2.8, 6.7) WHERE ID = 22
			UPDATE platinums SET rarity = REPLACE(rarity, 0.4, 6.7) WHERE ID = 23
			UPDATE platinums SET rarity = REPLACE(rarity, 1.9, 6.7) WHERE ID = 24
			UPDATE platinums SET rarity = REPLACE(rarity, 3.1, 6.7) WHERE ID = 25
			UPDATE platinums SET rarity = REPLACE(rarity, 0.8, 6.7) WHERE ID = 26
			UPDATE platinums SET rarity = REPLACE(rarity, 4.7, 6.7) WHERE ID = 27
			UPDATE platinums SET rarity = REPLACE(rarity, 0.6, 6.7) WHERE ID = 28
			UPDATE platinums SET rarity = REPLACE(rarity, 3.8, 6.7) WHERE ID = 29
			UPDATE platinums SET rarity = REPLACE(rarity, 0.7, 6.7) WHERE ID = 30
			UPDATE platinums SET rarity = REPLACE(rarity, 2.3, 6.7) WHERE ID = 31
			UPDATE platinums SET rarity = REPLACE(rarity, 0.6, 6.7) WHERE ID = 32
			UPDATE platinums SET rarity = REPLACE(rarity, 7.6, 6.7) WHERE ID = 33
			UPDATE platinums SET rarity = REPLACE(rarity, 2.4, 6.7) WHERE ID = 34
			UPDATE platinums SET rarity = REPLACE(rarity, 0.9, 6.7) WHERE ID = 35
			UPDATE platinums SET rarity = REPLACE(rarity, 2.1, 6.7) WHERE ID = 36
			UPDATE platinums SET rarity = REPLACE(rarity, 10.4, 6.7) WHERE ID = 37
			UPDATE platinums SET rarity = REPLACE(rarity, 12.4, 6.7) WHERE ID = 38
			UPDATE platinums SET rarity = REPLACE(rarity, 1.4, 6.7) WHERE ID = 39
			UPDATE platinums SET rarity = REPLACE(rarity, 6.9, 6.7) WHERE ID = 40
			UPDATE platinums SET rarity = REPLACE(rarity, 15.9, 6.7) WHERE ID = 41
			UPDATE platinums SET rarity = REPLACE(rarity, 1.3, 6.7) WHERE ID = 42
			UPDATE platinums SET rarity = REPLACE(rarity, 6.3, 6.7) WHERE ID = 43
			UPDATE platinums SET rarity = REPLACE(rarity, 81.6, 6.7) WHERE ID = 44
			UPDATE platinums SET rarity = REPLACE(rarity, 11.2, 6.7) WHERE ID = 45
			UPDATE platinums SET rarity = REPLACE(rarity, 11.1, 6.7) WHERE ID = 46
			UPDATE platinums SET rarity = REPLACE(rarity, 55.3, 6.7) WHERE ID = 47
			UPDATE platinums SET rarity = REPLACE(rarity, 46.0, 6.7) WHERE ID = 48
			UPDATE platinums SET rarity = REPLACE(rarity, 1.1, 6.7) WHERE ID = 49
			UPDATE platinums SET rarity = REPLACE(rarity, 59.5, 6.7) WHERE ID = 50
			UPDATE platinums SET rarity = REPLACE(rarity, 5.7, 6.7) WHERE ID = 51
			UPDATE platinums SET rarity = REPLACE(rarity, 4.4, 6.7) WHERE ID = 52
			UPDATE platinums SET rarity = REPLACE(rarity, 2.0, 6.7) WHERE ID = 53
			UPDATE platinums SET rarity = REPLACE(rarity, 41.3, 6.7) WHERE ID = 54
			UPDATE platinums SET rarity = REPLACE(rarity, 1.6, 6.7) WHERE ID = 55
			UPDATE platinums SET rarity = REPLACE(rarity, 29.6, 6.7) WHERE ID = 56
			UPDATE platinums SET rarity = REPLACE(rarity, 4.7, 6.7) WHERE ID = 57
			UPDATE platinums SET rarity = REPLACE(rarity, 3.7, 6.7) WHERE ID = 58
			UPDATE platinums SET rarity = REPLACE(rarity, 65.4, 6.7) WHERE ID = 59
			UPDATE platinums SET rarity = REPLACE(rarity, 11.8, 6.7) WHERE ID = 60
			UPDATE platinums SET rarity = REPLACE(rarity, 0.8, 6.7) WHERE ID = 61
			UPDATE platinums SET rarity = REPLACE(rarity, 1.9, 6.7) WHERE ID = 62
			UPDATE platinums SET rarity = REPLACE(rarity, 6.8, 6.7) WHERE ID = 63
			UPDATE platinums SET rarity = REPLACE(rarity, 1.8, 6.7) WHERE ID = 64
			UPDATE platinums SET rarity = REPLACE(rarity, 5.9, 6.7) WHERE ID = 65
			UPDATE platinums SET rarity = REPLACE(rarity, 21.6, 6.7) WHERE ID = 66
			UPDATE platinums SET rarity = REPLACE(rarity, 0.2, 6.7) WHERE ID = 67
			UPDATE platinums SET rarity = REPLACE(rarity, 7.4, 6.7) WHERE ID = 68
			UPDATE platinums SET rarity = REPLACE(rarity, 2.8, 6.7) WHERE ID = 69
			UPDATE platinums SET rarity = REPLACE(rarity, 17.6, 6.7) WHERE ID = 70
			UPDATE platinums SET rarity = REPLACE(rarity, 3.0, 6.7) WHERE ID = 71
			UPDATE platinums SET rarity = REPLACE(rarity, 34.4, 6.7) WHERE ID = 72
			UPDATE platinums SET rarity = REPLACE(rarity, 11.4, 6.7) WHERE ID = 73
			UPDATE platinums SET rarity = REPLACE(rarity, 11.0, 6.7) WHERE ID = 74
			UPDATE platinums SET rarity = REPLACE(rarity, 16.4, 6.7) WHERE ID = 75
			UPDATE platinums SET rarity = REPLACE(rarity, 5.3, 6.7) WHERE ID = 76
			UPDATE platinums SET rarity = REPLACE(rarity, 14.0, 6.7) WHERE ID = 77
			UPDATE platinums SET rarity = REPLACE(rarity, 15.6, 6.7) WHERE ID = 78
			UPDATE platinums SET rarity = REPLACE(rarity, 0.4, 6.7) WHERE ID = 79
			UPDATE platinums SET rarity = REPLACE(rarity, 2.3, 6.7) WHERE ID = 80
			UPDATE platinums SET rarity = REPLACE(rarity, 5.1, 6.7) WHERE ID = 81
			UPDATE platinums SET rarity = REPLACE(rarity, 22.1, 6.7) WHERE ID = 82
			UPDATE platinums SET rarity = REPLACE(rarity, 1.0, 6.7) WHERE ID = 83
			UPDATE platinums SET rarity = REPLACE(rarity, 4.5, 6.7) WHERE ID = 84
			UPDATE platinums SET rarity = REPLACE(rarity, 18.6, 6.7) WHERE ID = 85
			UPDATE platinums SET rarity = REPLACE(rarity, 11.4, 6.7) WHERE ID = 86
			UPDATE platinums SET rarity = REPLACE(rarity, 6.0, 6.7) WHERE ID = 87
			UPDATE platinums SET rarity = REPLACE(rarity, 0.7, 6.7) WHERE ID = 88
			UPDATE platinums SET rarity = REPLACE(rarity, 23.5, 6.7) WHERE ID = 89
			UPDATE platinums SET rarity = REPLACE(rarity, 23.8, 6.7) WHERE ID = 90
			UPDATE platinums SET rarity = REPLACE(rarity, 11.8, 6.7) WHERE ID = 91
			UPDATE platinums SET rarity = REPLACE(rarity, 13.3, 6.7) WHERE ID = 92
			UPDATE platinums SET rarity = REPLACE(rarity, 16.0, 6.7) WHERE ID = 93
			UPDATE platinums SET rarity = REPLACE(rarity, 23.2, 6.7) WHERE ID = 94
			UPDATE platinums SET rarity = REPLACE(rarity, 58.7, 6.7) WHERE ID = 95
			UPDATE platinums SET rarity = REPLACE(rarity, 50.6, 6.7) WHERE ID = 96
			UPDATE platinums SET rarity = REPLACE(rarity, 10.8, 6.7) WHERE ID = 97
			UPDATE platinums SET rarity = REPLACE(rarity, 15.0, 6.7) WHERE ID = 98
			UPDATE platinums SET rarity = REPLACE(rarity, 19.7, 6.7) WHERE ID = 99
			UPDATE platinums SET rarity = REPLACE(rarity, 6.3, 6.7) WHERE ID = 100
			UPDATE platinums SET rarity = REPLACE(rarity, 6.0, 6.7) WHERE ID = 101
			UPDATE platinums SET rarity = REPLACE(rarity, 4.3, 6.7) WHERE ID = 102
			UPDATE platinums SET rarity = REPLACE(rarity, 3.2, 6.7) WHERE ID = 103
			UPDATE platinums SET rarity = REPLACE(rarity, 0.3, 6.7) WHERE ID = 104
			UPDATE platinums SET rarity = REPLACE(rarity, 0.9, 6.7) WHERE ID = 105
			UPDATE platinums SET rarity = REPLACE(rarity, 6.4, 6.7) WHERE ID = 106
			UPDATE platinums SET rarity = REPLACE(rarity, 5.3, 6.7) WHERE ID = 107
			UPDATE platinums SET rarity = REPLACE(rarity, 0.6, 6.7) WHERE ID = 108
			UPDATE platinums SET rarity = REPLACE(rarity, 7.7, 6.7) WHERE ID = 109
			UPDATE platinums SET rarity = REPLACE(rarity, 1.1, 6.7) WHERE ID = 110
			UPDATE platinums SET rarity = REPLACE(rarity, 2.9, 6.7) WHERE ID = 111
			UPDATE platinums SET rarity = REPLACE(rarity, 15.5, 6.7) WHERE ID = 112
			UPDATE platinums SET rarity = REPLACE(rarity, 56.1, 6.7) WHERE ID = 113
			UPDATE platinums SET rarity = REPLACE(rarity, 7.3, 6.7) WHERE ID = 114
			UPDATE platinums SET rarity = REPLACE(rarity, 4.3, 6.7) WHERE ID = 115
			UPDATE platinums SET rarity = REPLACE(rarity, 5.4, 6.7) WHERE ID = 116
			UPDATE platinums SET rarity = REPLACE(rarity, 85.5, 6.7) WHERE ID = 117
			UPDATE platinums SET rarity = REPLACE(rarity, 28.2, 6.7) WHERE ID = 118
			UPDATE platinums SET rarity = REPLACE(rarity, 17.8, 6.7) WHERE ID = 119
			UPDATE platinums SET rarity = REPLACE(rarity, 1.4, 6.7) WHERE ID = 120
			UPDATE platinums SET rarity = REPLACE(rarity, 3.2, 6.7) WHERE ID = 121
			UPDATE platinums SET rarity = REPLACE(rarity, 95.5, 6.7) WHERE ID = 122
			UPDATE platinums SET rarity = REPLACE(rarity, 8.1, 6.7) WHERE ID = 123
			UPDATE platinums SET rarity = REPLACE(rarity, 14.7, 6.7) WHERE ID = 124
			UPDATE platinums SET rarity = REPLACE(rarity, 15.6, 6.7) WHERE ID = 125
			UPDATE platinums SET rarity = REPLACE(rarity, 29.8, 6.7) WHERE ID = 126
			UPDATE platinums SET rarity = REPLACE(rarity, 29.6, 6.7) WHERE ID = 127
			UPDATE platinums SET rarity = REPLACE(rarity, 28.2, 6.7) WHERE ID = 128
			UPDATE platinums SET rarity = REPLACE(rarity, 11.7, 6.7) WHERE ID = 129
			UPDATE platinums SET rarity = REPLACE(rarity, 1.5, 6.7) WHERE ID = 130
			UPDATE platinums SET rarity = REPLACE(rarity, 4.3, 6.7) WHERE ID = 131
			UPDATE platinums SET rarity = REPLACE(rarity, 1.8, 6.7) WHERE ID = 132
			UPDATE platinums SET rarity = REPLACE(rarity, 1.3, 6.7) WHERE ID = 133
			UPDATE platinums SET rarity = REPLACE(rarity, 2.0, 6.7) WHERE ID = 134
			UPDATE platinums SET rarity = REPLACE(rarity, 1.8, 6.7) WHERE ID = 135
			UPDATE platinums SET rarity = REPLACE(rarity, 3.3, 6.7) WHERE ID = 136
			UPDATE platinums SET rarity = REPLACE(rarity, 5.5, 6.7) WHERE ID = 137
			UPDATE platinums SET rarity = REPLACE(rarity, 5.5, 6.7) WHERE ID = 138
			UPDATE platinums SET rarity = REPLACE(rarity, 4.1, 6.7) WHERE ID = 139
			UPDATE platinums SET rarity = REPLACE(rarity, 3.2, 6.7) WHERE ID = 140
			UPDATE platinums SET rarity = REPLACE(rarity, 7.7, 6.7) WHERE ID = 141
			UPDATE platinums SET rarity = REPLACE(rarity, 53.3, 6.7) WHERE ID = 142
			UPDATE platinums SET rarity = REPLACE(rarity, 0.5, 6.7) WHERE ID = 143
			UPDATE platinums SET rarity = REPLACE(rarity, 0.6, 6.7) WHERE ID = 144
			UPDATE platinums SET rarity = REPLACE(rarity, 3.8, 6.7) WHERE ID = 145
			UPDATE platinums SET rarity = REPLACE(rarity, 0.3, 6.7) WHERE ID = 146
			UPDATE platinums SET rarity = REPLACE(rarity, 12.6, 6.7) WHERE ID = 147
			UPDATE platinums SET rarity = REPLACE(rarity, 2.2, 6.7) WHERE ID = 148
			UPDATE platinums SET rarity = REPLACE(rarity, 2.7, 6.7) WHERE ID = 149
			UPDATE platinums SET rarity = REPLACE(rarity, 2.5, 6.7) WHERE ID = 150
			UPDATE platinums SET rarity = REPLACE(rarity, 2.6, 6.7) WHERE ID = 151
			UPDATE platinums SET rarity = REPLACE(rarity, 5.4, 6.7) WHERE ID = 152
			UPDATE platinums SET rarity = REPLACE(rarity, 5.8, 6.7) WHERE ID = 153
			UPDATE platinums SET rarity = REPLACE(rarity, 8.2, 6.7) WHERE ID = 154
			UPDATE platinums SET rarity = REPLACE(rarity, 3.8, 6.7) WHERE ID = 155
			UPDATE platinums SET rarity = REPLACE(rarity, 7.9, 6.7) WHERE ID = 156
			UPDATE platinums SET rarity = REPLACE(rarity, 4.0, 6.7) WHERE ID = 157
			UPDATE platinums SET rarity = REPLACE(rarity, 9.2, 6.7) WHERE ID = 158
			UPDATE platinums SET rarity = REPLACE(rarity, 2.4, 6.7) WHERE ID = 159
			UPDATE platinums SET rarity = REPLACE(rarity, 16.3, 6.7) WHERE ID = 160
			UPDATE platinums SET rarity = REPLACE(rarity, 7.5, 6.7) WHERE ID = 161
			UPDATE platinums SET rarity = REPLACE(rarity, 8.4, 6.7) WHERE ID = 162
			UPDATE platinums SET rarity = REPLACE(rarity, 12.6, 6.7) WHERE ID = 163
			UPDATE platinums SET rarity = REPLACE(rarity, 17.6, 6.7) WHERE ID = 164
			UPDATE platinums SET rarity = REPLACE(rarity, 0.3, 6.7) WHERE ID = 165
			UPDATE platinums SET rarity = REPLACE(rarity, 2.0, 6.7) WHERE ID = 166
			UPDATE platinums SET rarity = REPLACE(rarity, 5.6, 6.7) WHERE ID = 167
			UPDATE platinums SET rarity = REPLACE(rarity, 5.6, 6.7) WHERE ID = 168
			UPDATE platinums SET rarity = REPLACE(rarity, 3.3, 6.7) WHERE ID = 169
			UPDATE platinums SET rarity = REPLACE(rarity, 0.8, 6.7) WHERE ID = 170
			UPDATE platinums SET rarity = REPLACE(rarity, 0.5, 6.7) WHERE ID = 171
			UPDATE platinums SET rarity = REPLACE(rarity, 5.4, 6.7) WHERE ID = 172
			UPDATE platinums SET rarity = REPLACE(rarity, 2.6, 6.7) WHERE ID = 173
			UPDATE platinums SET rarity = REPLACE(rarity, 0.3, 6.7) WHERE ID = 174
			UPDATE platinums SET rarity = REPLACE(rarity, 14.4, 6.7) WHERE ID = 175
			UPDATE platinums SET rarity = REPLACE(rarity, 0.4, 6.7) WHERE ID = 176
			UPDATE platinums SET rarity = REPLACE(rarity, 6.2, 6.7) WHERE ID = 177
			UPDATE platinums SET rarity = REPLACE(rarity, 0.8, 6.7) WHERE ID = 178
			UPDATE platinums SET rarity = REPLACE(rarity, 2.0, 6.7) WHERE ID = 179







