INSERT INTO playstation.dbo.Origins (Id,Game,Console,Developer,Country)
VALUES
(268,'[Prototype]','PS4','Radical Entertainment','Canada'),
(269,'[Prototype 2]','PS4','Radical Entertainment','Canada'),
(270,'101 Ways To Die','PS4','Four Door Lemon','England'),
(271,'60 Seconds! Reatomized','PS4','Robot Gentleman','Poland'),
(272,'A Boy And His Blob','PS4','WayForward Technologies Inc','USA'),
(273,'Absolute Drift: Zen Edition','PS4','FlippFly','USA'),
(274,'Abzu','PS4','Giant Squid Studios','USA'),
(275,'Active Soccer 2 DX','PS4','The Fox Software','Italy'),
(276,'Amnesia: Collection','PS4','Frictional Games','Sweden'),
(277,'Amplitude','PS4','Harmonix Music Systems','USA'),
(278,'Another World','PS4','Delphine Software','France'),
(279,'Ape Escape 2','PS4','Team Asobi','Japan'),
(280,'ARK: Survival Evolved','PS4','Studio Wildcard','USA'),
(281,'Armello','PS4','League of Geeks','Australia'),
(282,'Armikrog','PS4','Pencil Test Studios','USA'),
(283,'Art Of Balance','PS4','Shin`en Multimedia','Germany'),
(284,'Assault Android Cactus','PS4','Witch Beam','Australia'),
(285,'Aven Colony','PS4','Mothership Entertainment','USA'),
(286,'Back To The Future TTG','PS4','Telltale Games','USA'),
(287,'Badland','PS4','Frogmind Games','Finland'),
(288,'Batman Season 1 TTG','PS4','Telltale Games','USA'),
(289,'Batman Season 2 TTG','PS4','Telltale Games','USA'),
(290,'Batman: Arkham Asylum','PS4','Rocksteady Studios','England'),
(291,'Batman: Arkham City','PS4','Rocksteady Studios','England'),
(292,'Batman: Arkham Knight','PS4','Rocksteady Studios','England'),
(293,'Battlefield 1: Revolution','PS4','DICE','Sweden'),
(294,'Bear With Me','PS4','Exordium Games','Croatia'),
(295,'Beat Cop','PS4','Pixel Crow','Poland'),
(296,'Beyond Eyes','PS4','Tiger & Squid','Netherlands'),
(297,'Beyond Two Souls','PS4','Quantic Dream','France'),
(298,'BioShock 1 & 2: The Collection','PS4','Blind Squirrel Games','USA'),
(299,'BioShock Infinite: The Collection','PS4','Blind Squirrel Games','USA'),
(300,'BLACKSAD: Under the Skin','PS4','Pendulo Studios','Spain'),
(301,'Blood Bowl 2','PS4','Cyanide','France'),
(302,'Bloodborne','PS4','FromSoftware','Japan'),
(303,'Borderlands: Game of the Year Edition','PS4','Gearbox Software','USA'),
(304,'Borderlands: The Handsome Collection','PS4','Gearbox Software','USA'),
(305,'Bridge Constructor','PS4','ClockStone Studios','Austria'),
(306,'Broforce','PS4','Free Lives','South Africa'),
(307,'Broken Age','PS4','Double Fine Productions','USA'),
(308,'Brothers: A Tale of Two Sons','PS4','Starbreeze Studios','Sweden'),
(309,'Canis Canem Edit (Bully)','PS4','Rockstar Vancouver','Canada'),
(310,'Burnout Paradise: Remastered','PS4','Criterion Games','England'),
(311,'Call of Duty: Black Ops III','PS4','Treyarch','USA'),
(312,'Captain Tsubasa: Rise of New Champions','PS4','Tamsoft','Japan'),
(313,'Castle Crashers: Remastered','PS4','The Behemoth','USA'),
(314,'Castlevania Requiem: Symphony of the Night and Rondo of Blood','PS4','Konami','Japan'),
(315,'Catherine: Full Body','PS4','Atlus','Japan'),
(316,'Cel Damage HD','PS4','Finish Line Games','Canada'),
(317,'Celeste','PS4','Extremely OK Games','Canada'),
(318,'Child Of Light','PS4','Ubisoft Montreal','Canada'),
(319,'Chime Sharp','PS4','Chilled Mouse','England'),
(320,'Cities: Skylines','PS4','Colossal Order','Finland'),
(321,'Claire','PS4','Hailstorm Games','USA'),
(322,'ClusterTruck','PS4','Landfall Games','Sweden'),
(323,'Code Vein','PS4','Bandai Namco Studios','Japan'),
(324,'Color Slayer','PS4','The Domaginarium','El Salvador'),
(325,'Concrete Genie','PS4','Pixelopus','USA'),
(326,'Cosmophony','PS4','Bento Studio','France'),
(327,'CounterSpy','PS4','Dynamighty','USA'),
(328,'Crash Bandicoot: N Sane Trilogy (2017)','PS4','Vicarious Visions','USA'),
(329,'Crash Team Racing: Nitro Fueled (2019)','PS4','Beenox','Canada'),
(330,'Croixleur Sigma','PS4','souvenir circ','Japan'),
(331,'Curse of the Dead Gods','PS4','Passtech Games','France'),
(332,'Danger Zone','PS4','Three Fields Entertainment','England'),
(333,'Dangerous Driving','PS4','Three Fields Entertainment','England'),
(334,'Dangerous Golf','PS4','Three Fields Entertainment','England'),
(335,'Dark Chronicle','PS4','Level-5','Japan'),
(336,'Dark Cloud','PS4','Level-5','Japan'),
(337,'Dark Souls II: Scholar of the First Sin','PS4','FromSoftware','Japan'),
(338,'Dark Souls III','PS4','FromSoftware','Japan'),
(339,'Dark Souls Remastered','PS4','FromSoftware','Japan'),
(340,'Day Of The Tentacle Remastered','PS4','LucasArts','USA'),
(341,'Days Gone','PS4','Bend Studio','USA'),
(342,'Dead End Job','PS4','Ant Workshop','Scotland'),
(343,'Dead Island: Retro Revenge','PS4','Empty Clip Studios','USA'),
(344,'Dead or Alive 5: Last Round','PS4','Team Ninja','Japan'),
(345,'Dead Rising','PS4','Capcom','Japan'),
(346,'Deadpool','PS4','High Moon Studios','USA'),
(347,'Death Squared','PS4','SMG Studio','Australia'),
(348,'DEEEER Simulator: Your Average Everyday Deer Game','PS4','Gibier Games','Japan'),
(349,'Destroy All Humans! (2005)','PS4','Pandemic Studios','USA'),
(350,'Destroy All Humans! 2 (2006)','PS4','Pandemic Studios','USA'),
(351,'Destroy All Humans! (2020)','PS4','Black Forest Games','Germany'),
(352,'Detroit: Become Human','PS4','Quantic Dream','France'),
(353,'Devil May Cry 4','PS4','Capcom','Japan'),
(354,'Devil May Cry 5','PS4','Capcom','Japan'),
(355,'Devil May Cry Trilogy HD Collection','PS4','Capcom','Japan'),
(356,'Dex','PS4','Dreadlocks Ltd','Czech Republic'),
(357,'Disney Classic Games: Aladdin & The Lion King','PS4','Digital Eclipse','USA'),
(358,'Doki-Doki Universe','PS4','HumaNature Studios','USA'),
(359,'Donut County','PS4','Ben Esposito','USA'),
(360,'DOOM (1993)','PS4','id Software','USA'),
(361,'DOOM 64','PS4','Midway Games','USA'),
(362,'DOOM II','PS4','id Software','USA'),
(363,'Downwell','PS4','Moppin','Japan'),
(364,'DreamBall','PS4','Rampage Game Studio','Spain'),
(365,'Dreams','PS4','Media Molecule','England'),
(366,'Duke Nukem 3D','PS4','Gearbox Software','USA'),
(367,'Empire of Sin: Deluxe Edition','PS4','Romero Games','Republic of Ireland'),
(368,'Enter The Gungeon','PS4','Dodge Roll','USA'),
(369,'Entwined','PS4','Pixelopus','USA'),
(370,'Escape Plan','PS4','Fun Bits Interactive','USA'),
(371,'Everybody`s Golf (2017)','PS4','Clap Hanz','Japan'),
(372,'Exit the Gungeon','PS4','Dodge Roll','USA'),
(373,'Fahrenheit (Indigo Prophecy)','PS4','Quantic Dream','France'),
(374,'Fallout 4','PS4','Bethesda Game Studios','USA'),
(375,'Far Cry 3','PS4','Ubisoft Montreal','Canada'),
(376,'Far Cry 4','PS4','Ubisoft Montreal','Canada'),
(377,'Far Cry 5','PS4','Ubisoft Montreal','Canada'),
(378,'Far Cry: New Dawn','PS4','Ubisoft Montreal','Canada'),
(379,'Far Cry: Primal','PS4','Ubisoft Montreal','Canada'),
(380,'Fat Princess Adventures','PS4','Fun Bits Interactive','USA'),
(381,'Fez','PS4','Polytron Corporation','Canada'),
(382,'FIFA 18','PS4','EA Vancouver','Canada'),
(383,'FIFA 19','PS4','EA Vancouver','Canada'),
(384,'FIFA 20','PS4','EA Vancouver','Canada'),
(385,'Final Fantasy X/X-2 HD Remaster','PS4','Square Enix','Japan'),
(386,'Final Fantasy XV: Royal Edition','PS4','Square Enix','Japan'),
(387,'Five Dates','PS4','Wales Interactive','Wales'),
(388,'Flashback','PS4','Delphine Software International','France'),
(389,'Flockers','PS4','Team17','England'),
(390,'flOw','PS4','Thatgamecompany','USA'),
(391,'Flower','PS4','Thatgamecompany','USA'),
(392,'forma.8','PS4','MixedBag','Italy'),
(393,'Formula Retro Racing','PS4','Repixel8','England'),
(394,'Futuridium','PS4','MixedBag','Italy'),
(395,'Game Of Thrones TTG','PS4','Telltale Games','USA'),
(396,'Geometry Wars 3: Dimensions Evolved','PS4','Lucid Games','England'),
(397,'Ghost Blade HD','PS4','Hucast Games','Germany'),
(398,'Ghost of Tsushima','PS4','Sucker Punch Productions','USA'),
(399,'Ghostbusters','PS4','FireForge Games','USA'),
(400,'Goat Simulator','PS4','Coffee Stain Studios','Sweden'),
(401,'God of War (2018)','PS4','Santa Monica Studio','USA'),
(402,'God of War III Remastered','PS4','Santa Monica Studio','USA'),
(403,'Good Dog Bad Dog','PS4','Play Em','USA'),
(404,'Granblue Fantasy: Versus','PS4','Arc System Works','Japan'),
(405,'Grand Ages: Medieval','PS4','Gaming Minds Studios','Germany'),
(406,'Grand Theft Auto III (2001)','PS4','Rockstar North','Scotland'),
(407,'Grand Theft Auto: San Andreas (2004)','PS4','Rockstar North','Scotland'),
(408,'Grand Theft Auto: Vice City (2002)','PS4','Rockstar North','Scotland'),
(409,'Grim Fandango Remastered','PS4','LucasArts','USA'),
(410,'Harvest Moon: A Wonderful Life','PS4','Marvelous Interactive','Japan'),
(411,'Hatoful Boyfriend','PS4','Mediatonic','England'),
(412,'Heart&Slash','PS4','aheartfulofgames','Spain'),
(413,'Heavy Rain','PS4','Quantic Dream','France'),
(414,'Helldivers','PS4','Arrowhead Game Studios','Sweden'),
(415,'Hitman 2','PS4','IO Interactive','Denmark'),
(416,'Hohokum','PS4','Honeyslug','England'),
(417,'Hollow Knight: Voidheart Edition','PS4','Team Cherry','Australia'),
(418,'Home','PS4','Benjamin Rivers Inc','Canada'),
(419,'HoPiKo','PS4','Laser Dog','England'),
(420,'Horizon Zero Dawn','PS4','Guerrilla Games','Netherlands'),
(421,'Hotline Miami','PS4','Dennaton Games','Sweden'),
(422,'Hotline Miami 2: Wrong Number','PS4','Dennaton Games','Sweden'),
(423,'Hue','PS4','Fiddlesticks','England'),
(424,'I am Bread','PS4','Bossa Studios','England'),
(425,'inFamous First Light','PS4','Sucker Punch Productions','USA'),
(426,'inFamous Second Son','PS4','Sucker Punch Productions','USA'),
(427,'Injustice: Gods Among Us','PS4','NetherRealm Studios','USA'),
(428,'Injustice 2','PS4','NetherRealm Studios','USA'),
(429,'Jak 3','PS4','Naughty Dog','USA'),
(430,'Jak and Daxter: The Precursor Legacy','PS4','Naughty Dog','USA'),
(431,'Jak II: Renegade','PS4','Naughty Dog','USA'),
(432,'Jak X: Combat Racing','PS4','Naughty Dog','USA'),
(433,'Jazzpunk: Director`s Cut','PS4','Necrophone Games','Canada'),
(434,'Jetpack Joyride','PS4','Halfbrick Studios','Australia'),
(435,'Journey','PS4','thatgamecompany','USA'),
(436,'Just Die Already','PS4','DoubleMoose Games','Sweden'),
(437,'Kandagawa Jet Girls','PS4','Honey Parade Games','Japan'),
(438,'Katamari Damacy: Reroll','PS4','Bandai Namco Studios','Japan'),
(439,'Keep Talking and Nobody Explodes','PS4','Steel Crate Games','Canada'),
(440,'Kingdom Hearts HD 1.5 & 2.5 Remix','PS4','Square Enix','Japan'),
(441,'Kingdom Hearts HD 2.8 Final Chapter Prologue','PS4','Square Enix','Japan'),
(442,'Kingdom Hearts III','PS4','Square Enix','Japan'),
(443,'Kingdoms of Amalur: Re-Reckoning','PS4','Kaiko','Germany'),
(444,'Knack','PS4','Team Asobi','Japan'),
(445,'Knack 2','PS4','Team Asobi','Japan'),
(446,'LA Cops','PS4','Modern Dream','England'),
(447,'LEGO City Undercover','PS4','TT Games','England'),
(448,'LEGO DC Super-Villains','PS4','TT Games','England'),
(449,'LEGO Harry Potter Collection','PS4','TT Games','England'),
(450,'LEGO Marvel Super-Heroes','PS4','TT Games','England'),
(451,'Leisure Suit Larry: Wet Dreams Don`t Dry','PS4','CrazyBunch','Germany'),
(452,'Leisure Suit Larry: Wet Dreams Dry Twice','PS4','CrazyBunch','Germany'),
(453,'Lichtspeer','PS4','Lichthund','Poland'),
(454,'Life Is Strange','PS4','Dontnod Entertainment','France'),
(455,'Little Nightmares','PS4','Tarsier Studios','Sweden'),
(456,'LittleBigPlanet 3','PS4','Sumo Digital','England'),
(457,'LocoRoco','PS4','Team Asobi','Japan'),
(458,'Lovers In A Dangerous Spacetime','PS4','Asteroid Base','Canada'),
(459,'LUMO','PS4','Just Add Water Ltd','England'),
(460,'Mafia: Definitive Edition (2020)','PS4','Hangar 13','USA'),
(461,'Mafia III','PS4','Hangar 13','USA'),
(462,'Manhunt','PS4','Rockstar North','Scotland'),
(463,'Manual Samuel','PS4','Perfectly Paranormal','Norway'),
(464,'Marvel`s Guardians Of The Galaxy TTG','PS4','Telltale Games','USA'),
(465,'Marvel`s Spider-Man','PS4','Insomniac Games','USA'),
(466,'Mass Effect: Legendary Edition','PS4','Bioware','Canada'),
(467,'Max Payne','PS4','Remedy Entertainment','Finland'),
(468,'MediEvil (2019)','PS4','Other Ocean Emeryville','USA'),
(469,'Mega Man Legacy Collection','PS4','Digital Eclipse','USA'),
(470,'Mega Man Legacy Collection 2','PS4','Capcom','Japan'),
(471,'Mega Man X Legacy Collection','PS4','Capcom','Japan'),
(472,'Mega Man X Legacy Collection 2','PS4','Capcom','Japan'),
(473,'Metal Gear Solid V: The Phantom Pain','PS4','Kojima Productions','Japan'),
(474,'Metro Redux','PS4','4A Games','Ukraine'),
(475,'Micro Machines World Series','PS4','Codemasters','England'),
(476,'Minecraft Dungeons','PS4','Mojang Studios','Sweden'),
(477,'Minutes','PS4','Red Phantom Games','England'),
(478,'Monopoly Family Fun Pack','PS4','Asobo Studio','France'),
(479,'Monster Hunter World: Iceborne','PS4','Capcom','Japan'),
(480,'Mortal Kombat X','PS4','NetherRealm Studios','USA'),
(481,'Mortal Shell','PS4','Cold Symmetry','USA'),
(482,'Mother Russia Bleeds','PS4','Le Cartel Studio','France'),
(483,'Need for Speed Heat','PS4','EA Gothenburg','Sweden'),
(484,'Neon Chrome','PS4','10tons','Finland'),
(485,'Neon Drive','PS4','Fraoula','Slovenia'),
(486,'Night Book','PS4','Wales Interactive','Wales'),
(487,'Ninja Senki DX','PS4','Tribute Games','Canada'),
(488,'Nitroplus Blasterz: Heroines Infinite Duel','PS4','Team Arcana','Japan'),
(489,'Octodad: Dadliest Catch','PS4','Young Horses','USA'),
(490,'Oddworld: New n Tasty','PS4','Just Add Water Ltd','England'),
(491,'Okami HD','PS4','Clover Studio','Japan'),
(492,'OlliOlli 2','PS4','Roll7','England'),
(493,'OlliOlli: Epic Combo Edition','PS4','Roll7','England'),
(494,'One Piece Unlimited World Red','PS4','Ganbarion','Japan'),
(495,'Onee Chanbara Origin','PS4','Tamsoft','Japan'),
(496,'Outbreak: Epidemic','PS4','Dead Drop Studios LLC','USA'),
(497,'Outlast','PS4','Red Barrels','Canada'),
(498,'Oxenfree','PS4','Night School Studio','USA'),
(499,'PAC-MAN 256','PS4','Hipster Whale','Australia'),
(500,'PaRappa The Rapper 2','PS4','NanaOn-Sha','Japan'),
(501,'PaRappa The Rapper Remastered','PS4','Team Asobi','Japan'),
(502,'Party Hard','PS4','Pinokl Games','Ukraine'),
(503,'Party Hard 2','PS4','Pinokl Games','Ukraine'),
(504,'Persona 5','PS4','Atlus','Japan'),
(505,'Persona 5 Strikers','PS4','Omega Force','Japan'),
(506,'PGA Tour 2K21','PS4','HB Studios','Canada'),
(507,'Pic-A-Pix Color','PS4','Lightwood Games','England'),
(508,'PixelJunk Shooter Ultimate','PS4','Double Eleven','England'),
(509,'Plants vs Zombies: Battle for Neighborville','PS4','PopCap Games','USA'),
(510,'Please Don`t Touch Anything','PS4','Four Quarters','Russia'),
(511,'Poltergeist: A Pixelated Horror','PS4','Glitchy Pixel','Colombia'),
(512,'Polybius','PS4','Llamasoft','England'),
(513,'PONG Quest','PS4','Chequered Ink Ltd','England'),
(514,'Postal Redux','PS4','Running With Scissors','USA'),
(515,'Psychonauts','PS4','Double Fine Productions','USA'),
(516,'Psychonauts 2','PS4','Double Fine Productions','USA'),
(517,'Pumped BMX+','PS4','Yeah, Us!','England'),
(518,'Putty Squad','PS4','System 3 Software','England'),
(519,'Quake','PS4','id Software','USA'),
(520,'Quest Of Dungeons','PS4','Upfall Studios','Portugal'),
(521,'Rally Copters','PS4','Depth First Games','USA'),
(522,'Ratchet & Clank (2016)','PS4','Insomniac Games','USA'),
(523,'Rayman Legends','PS4','Ubisoft Montpellier','France'),
(524,'Red Dead Redemption 2','PS4','Rockstar San Diego','USA'),
(525,'Red Dead Revolver','PS4','Rockstar San Diego','USA'),
(526,'Resident Evil 0','PS4','Capcom','Japan'),
(527,'Resident Evil (2002)','PS4','Capcom','Japan'),
(528,'Resident Evil 4 (2005)','PS4','Capcom','Japan'),
(529,'Resident Evil 5','PS4','Capcom','Japan'),
(530,'Resident Evil 6','PS4','Capcom','Japan'),
(531,'Resident Evil: Resistance','PS4','Capcom','Japan'),
(532,'Resident Evil Revelations','PS4','Capcom','Japan'),
(533,'Resident Evil Revelations 2','PS4','Capcom','Japan'),
(534,'Resident Evil: Re:Verse','PS4','Capcom','Japan'),
(535,'RESOGUN','PS4','Housemarque','Finland'),
(536,'Retro City Rampage DX','PS4','Vblank Entertainment','Canada'),
(537,'Riptide GP: Renegade','PS4','Vector Unit','USA'),
(538,'Rise Of The Tomb Raider','PS4','Crystal Dynamics','USA'),
(539,'Risk Of Rain','PS4','Hopoo Games','USA'),
(540,'Road Redemption','PS4','EQ-Games','USA'),
(541,'Rock Boshers DX: Director`s Cut','PS4','Tikipod','England'),
(542,'Rocket League','PS4','Psyonix','USA'),
(543,'Rocketbirds 2: Evolution','PS4','Ratloop Asia','Singapore'),
(544,'Rogue Legacy','PS4','Cellar Door Games','Canada'),
(545,'Rollercoaster Dreams','PS4','Bimboosoft','Japan'),
(546,'Saban`s Mighty Morphin Power Rangers: Mega Battle','PS4','Bamtang Games','Peru'),
(547,'Saints Row IV: Gat out of Hell','PS4','High Voltage Software','USA'),
(548,'Saints Row IV: Re-Elected','PS4','High Voltage Software','USA'),
(549,'Sam and Max Season 1: Save The World','PS4','Telltale Games','USA'),
(550,'Sam and Max Season 2: Beyond Time and Space','PS4','Telltale Games','USA'),
(551,'Scott Pilgrim vs The World: The Game','PS4','Ubisoft Montreal','Canada'),
(552,'Scribblenauts Mega Pack','PS4','5th Cell','USA'),
(553,'Sekiro: Shadows Die Twice','PS4','FromSoftware','Japan'),
(554,'Shovel Knight: Pocket Dungeon','PS4','Yacht Club Games','USA'),
(555,'Shovel Knight: Treasure Trove','PS4','Yacht Club Games','USA'),
(556,'ShredIt','PS4','Extra Mile Studios','Scotland'),
(557,'Slain: Back from Hell','PS4','Wolf Brew Games','USA'),
(558,'Slay the Spire','PS4','Humble Bundle','USA'),
(559,'Sleeping Dogs: Definitive Edition','PS4','United Front Games','Canada'),
(560,'Slender: The Arrival','PS4','Blue Isle Studios','Canada'),
(561,'Sniper Elite V2 Remastered','PS4','Rebellion Developments','England'),
(562,'Sonic Mania','PS4','Christian Whitehead','Australia'),
(563,'SoulCalibur VI','PS4','Bandai Namco Studios','Japan'),
(564,'Sound Shapes','PS4','Queasy Games','Canada'),
(565,'South Park: The Fractured But Whole','PS4','Ubisoft San Francisco','USA'),
(566,'South Park: The Stick of Truth','PS4','Obsidian Entertainment','USA'),
(567,'Spelunky','PS4','Mossmouth LLC','USA'),
(568,'SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated','PS4','Purple Lamp Studios','Austria'),
(569,'Spy Chameleon','PS4','Unfinished Pixel','Spain'),
(570,'Spyro Reignited Trilogy (2018)','PS4','Toys for Bob','USA'),
(571,'Star Wars Episode I: Pod Racer','PS4','LucasArts','USA'),
(572,'Stardew Valley','PS4','ConcernedApe','USA'),
(573,'Stealth Inc: A Clone In The Dark','PS4','Curve Studios','England'),
(574,'Stealth Inc 2: A Game Of Clones','PS4','Curve Studios','England'),
(575,'SteamWorld Dig','PS4','Image & Form','Sweden'),
(576,'SteamWorld Dig 2','PS4','Image & Form','Sweden'),
(577,'SteamWorld Heist','PS4','Image & Form','Sweden'),
(578,'Stikbold! A Dodgeball Adventure','PS4','Game Swing','Denmark'),
(579,'Stranded Deep','PS4','Beam Team Games','Australia'),
(580,'Street Fighter 30th Anniversary Collection','PS4','Capcom','Japan'),
(581,'Super Kickers League Ultimate','PS4','Xaloc Studios','Spain'),
(582,'Super Meat Boy!','PS4','Team Meat','USA'),
(583,'Super Monkey Ball: Banana Blitz HD','PS4','New Entertainment R&D Dept','Japan'),
(584,'Super Stardust Ultra','PS4','Housemarque','Finland'),
(585,'Superbeat: Xonic EX','PS4','Nurijoy','Korea Republic'),
(586,'Supermarket Shriek','PS4','Billy Goat Entertainment Ltd','Northern Ireland'),
(587,'Surgeon Simulator','PS4','Bossa Studios','England'),
(588,'Switch Galaxy Ultra','PS4','Atomicom','England'),
(589,'Syrup and the Ultimate Sweet','PS4','NomNomNami','USA'),
(590,'Table Top Racing: World Tour','PS4','Playrise Digital Ltd','England'),
(591,'Tales From The Borderlands','PS4','Telltale Games','USA'),
(592,'Team Sonic Racing','PS4','Sumo Digital','England'),
(593,'Tearaway Unfolded','PS4','Media Molecule','England'),
(594,'Tekken 7','PS4','Bandai Namco Studios','Japan'),
(595,'Tembo The Badass Elephant','PS4','Game Freak','Japan'),
(596,'Tennis in the Face','PS4','10tons','Finland'),
(597,'Tennis World Tour 2','PS4','Big Ant Studios','Australia'),
(598,'Terraria','PS4','Re-Logic','USA'),
(599,'Tethered','PS4','Secret Sorcery','England'),
(600,'Tetris Ultimate','PS4','SoMa Play','USA'),
(601,'That`s You!','PS4','Wish Studios','England'),
(602,'The Binding of Isaac: Rebirth','PS4','Nicalis','USA'),
(603,'The Bug Butcher','PS4','Awfully Nice Studios','Austria'),
(604,'The Complex','PS4','Wales Interactive','Wales'),
(605,'The Crew','PS4','Ivory Tower','France'),
(606,'The Disney Afternoon Collection','PS4','Digital Eclipse','USA'),
(607,'The Escapists','PS4','Mouldy Toof Studios','England'),
(608,'The Evil Within','PS4','Tango Gameworks','Japan'),
(609,'The Flame in the Flood','PS4','The Molasses Flood','USA'),
(610,'The Last Guardian','PS4','Team Asobi','Japan'),
(611,'The Last Of Us: Left Behind Remastered','PS4','Naughty Dog','USA'),
(612,'The Last of Us Part II','PS4','Naughty Dog','USA'),
(613,'The Last Of Us Remastered','PS4','Naughty Dog','USA'),
(614,'The Outer Worlds','PS4','Obsidian Entertainment','USA'),
(615,'The Sims 4','PS4','Maxis','USA'),
(616,'The Swapper','PS4','Facepalm Games','Finland'),
(617,'The Unfinished Swan','PS4','Giant Sparrow','USA'),
(618,'The Walking Dead Season 1','PS4','Telltale Games','USA'),
(619,'The Walking Dead Season 2','PS4','Telltale Games','USA'),
(620,'The Walking Dead Season 3','PS4','Telltale Games','USA'),
(621,'The Walking Dead: The Final Season','PS4','Telltale Games','USA'),
(622,'The Warriors','PS4','Rockstar Toronto','Canada'),
(623,'The Witness','PS4','Thekla Inc','USA'),
(624,'The Wolf Among Us Season 1','PS4','Telltale Games','USA'),
(625,'Think of the Children','PS4','Jammed Up Studios','Australia'),
(626,'This Is The Police','PS4','Weappy Studio','Belarus'),
(627,'Thomas Was Alone','PS4','Mike Bithell','England'),
(628,'Tiny Tina`s Assault on Dragon Keep: A Wonderlands One-Shot Adventure','PS4','Gearbox Software','USA'),
(629,'Titan Attacks!','PS4','Puppy Games','England'),
(630,'ToeJam & Earl: Back In The Groove (2019)','PS4','HumaNature Studios','USA'),
(631,'Touhou Double Focus','PS4','Aqua Style','Japan'),
(632,'Trials Fusion: The Awesome MAX Edition','PS4','RedLynx','France'),
(633,'Tribes of Midgard','PS4','Norsfell Games','Canada'),
(634,'Tricky Towers','PS4','WeirdBeard','Netherlands'),
(635,'Trine 2: Complete Story','PS4','Frozenbyte','Finland'),
(636,'Trine 3: The Artifacts Of Power','PS4','Frozenbyte','Finland'),
(637,'Trine: Enchanted Edition','PS4','Frozenbyte','Finland'),
(638,'Tropico 5','PS4','Haemimont Games','Bulgaria'),
(639,'Trover Saves The Universe','PS4','Squanch Games','USA'),
(640,'Twisted Metal: Black','PS4','Incognito Entertainment','USA'),
(641,'Two Point Hospital','PS4','Two Point Studios','England'),
(642,'Typoman','PS4','Brainseed Factory','Germany'),
(643,'UFC 4','PS4','EA Vancouver','Canada'),
(644,'Ultratron','PS4','Puppy Games','England'),
(645,'Unbox: Newbie`s Adventure','PS4','Prospect Games','England'),
(646,'Uncanny Valley','PS4','Cowardly Creations','USA'),
(647,'Uncharted: Drake`s Fortune','PS4','Naughty Dog','USA'),
(648,'Uncharted: The Lost Legacy','PS4','Naughty Dog','USA'),
(649,'Uncharted 2: Among Thieves','PS4','Naughty Dog','USA'),
(650,'Uncharted 3: Drake`s Deception','PS4','Naughty Dog','USA'),
(651,'Uncharted 4: A Thief`s End','PS4','Naughty Dog','USA'),
(652,'Undertale','PS4','tobyfox','USA'),
(653,'UNO','PS4','Ubisoft Chengdu','China'),
(654,'Unravel','PS4','Coldwood Interactive','Sweden'),
(655,'Until Dawn','PS4','Supermassive Games','England'),
(656,'Untitled Goose Game','PS4','House House','Australia'),
(657,'Velocity 2X','PS4','FuturLab','England'),
(658,'Viking Squad','PS4','Slick Entertainment','Canada'),
(659,'Virtua Fighter 5: Ultimate Showdown','PS4','Sega','Japan'),
(660,'Volume','PS4','Mike Bithell','England'),
(661,'Watch Dogs','PS4','Ubisoft Montreal','Canada'),
(662,'Watch Dogs 2','PS4','Ubisoft Montreal','Canada'),
(663,'while true: learn( )','PS4','Luden.io','Russia'),
(664,'Wipeout Omega Collection','PS4','XDev','England'),
(665,'Worms Battlegrounds','PS4','Team17','England'),
(666,'Worms WMD','PS4','Team17','England'),
(667,'WRC 6','PS4','Kylotonn','France'),
(668,'WWE 2K Battlegrounds','PS4','Saber Interactive','USA'),
(669,'XCOM 2','PS4','Firaxis Games','USA'),
(670,'Xenoraid','PS4','10tons','Finland'),
(671,'Yakuza 0','PS4','Ryu Ga Gotoku Studio','Japan'),
(672,'Yakuza 3 Remastered','PS4','Ryu Ga Gotoku Studio','Japan'),
(673,'Yakuza 4 Remastered','PS4','Ryu Ga Gotoku Studio','Japan'),
(674,'Yakuza 5 Remastered','PS4','Ryu Ga Gotoku Studio','Japan'),
(675,'Yakuza 6: The Song of Life','PS4','Ryu Ga Gotoku Studio','Japan'),
(676,'Yakuza Kiwami','PS4','Ryu Ga Gotoku Studio','Japan'),
(677,'Yakuza Kiwami 2','PS4','Ryu Ga Gotoku Studio','Japan'),
(678,'Yomawari: Midnight Shadows','PS4','Nippon Ichi Software','Japan'),
(679,'Yooka-Laylee','PS4','Playtonic Games','England'),
(680,'Yooka-Laylee and the Impossible Lair','PS4','Playtonic Games','England'),
(681,'Yu-Gi-Oh! Legacy of the Duelist','PS4','Other Ocean Interactive','Canada');