INSERT INTO playstation.dbo.Origins (Id,Game,Console,Developer,Country)
VALUES
(755,'A Plague Tale: Innocence','PS5','Asobo Studio','France'),
(756,'Apex Legends','PS5','Respawn Entertainment','USA'),
(757,'Art of Rally','PS5','Funselektor Labs Inc','Canada'),
(758,'Assassin`s Creed Valhalla: Ultimate Edition','PS5','Ubisoft Montreal','Canada'),
(759,'Astro`s Playroom','PS5','Team Asobi','Japan'),
(760,'AWAY: The Survival Series','PS5','Breaking Walls','Canada'),
(761,'Axiom Verge 2','PS5','Thomas Happ Games','USA'),
(762,'Battlefield 2042','PS5','EA DICE','Sweden'),
(763,'Biomutant','PS5','Experiment 101','Sweden'),
(764,'BloodRayne: ReVamped','PS5','Terminal Reality','USA'),
(765,'BloodRayne 2: ReVamped','PS5','Terminal Reality','USA'),
(766,'Borderlands 3','PS5','Gearbox Software','USA'),
(767,'Bugsnax','PS5','Young Horses','USA'),
(768,'Can`t Drive This','PS5','Pixel Maniacs','Germany'),
(769,'Chicken Police: Paint It Red','PS5','The Wild Gentlemen','Hungary'),
(770,'Chicory: A Colorful Tale','PS5','Greg Lobanov','USA'),
(771,'Cloudpunk','PS5','Ion Lands','Germany'),
(772,'Concept Destruction','PS5','Thinice Games','Spain'),
(773,'Crash Bandicoot 4: It`s About Time','PS5','Toys For Bob','USA'),
(774,'Cult of the Lamb','PS5','Massive Monster','Australia'),
(775,'Cyberpunk 2077','PS5','CD Projekt Red','Poland'),
(776,'Deep Rock Galactic','PS5','Ghost Ship Games','Denmark'),
(777,'Destiny 2','PS5','Bungie','USA'),
(778,'Destroy All Humans 2: Reprobed (2022)','PS5','Black Forest Games','Germany'),
(779,'DIRT 5','PS5','Codemasters','England'),
(780,'Disney Dreamlight Valley','PS5','Gameloft','France'),
(781,'Evil Inside','PS5','JanduSoft SL','Spain'),
(782,'F1 2021','PS5','Codemasters','England'),
(783,'F1 Manager','PS5','Frontier Developments','England'),
(784,'Fall Guys: Ultimate Knockout','PS5','Mediatonic','England'),
(785,'Far Cry 6: Gold Edition','PS5','Ubisoft Toronto','Canada'),
(786,'FIFA 21','PS5','EA Vancouver','Canada'),
(787,'FIFA 22','PS5','EA Vancouver','Canada'),
(788,'Final Fantasy VII (2021)','PS5','Square Enix','Japan'),
(789,'First Class Trouble','PS5','Invisible Walls','Denmark'),
(790,'Fortnite','PS5','Epic Games','USA'),
(791,'Genshin Impact','PS5','miHoYo','China'),
(792,'Ghostrunner','PS5','Slipgate Ironworks','Denmark'),
(793,'Ghostwire: Tokyo','PS5','Tango Gameworks','Japan'),
(794,'Godfall','PS5','Counterplay Games','USA'),
(795,'Grand Theft Auto V','PS5','Rockstar North','Scotland'),
(796,'Heavenly Bodies','PS5','2pt Interactive','Australia'),
(797,'Hell Let Loose','PS5','Black Matter Games','Australia'),
(798,'Hogwarts Legacy','PS5','Avalanche Software','USA'),
(799,'Horizon Forbidden West','PS5','Guerrilla Games','Netherlands'),
(800,'Hot Wheels Unleashed','PS5','Milestone','Italy'),
(801,'Human Fall Flat','PS5','No Brakes Games','Lithuania'),
(802,'In Rays of the Light','PS5','Sergey Noskov','Russia'),
(803,'Infliction: Extended Cut','PS5','Caustic Reality','Australia'),
(804,'It Takes Two','PS5','Hazelight Studios','Sweden'),
(805,'Judgment','PS5','Ryu Ga Gotoku','Japan'),
(806,'Kena: Bridge of Spirits','PS5','Ember Lab','USA'),
(807,'Kerbal Space Program: Enhanced Edition','PS5','Squad','Mexico'),
(808,'Klonoa Phantasy Reverie Series (2022)','PS5','Bandai Namco Studios','Japan'),
(809,'Knockout City','PS5','Velan Studios','USA'),
(810,'Maneater','PS5','Tripwire Interactive','USA'),
(811,'Maquette','PS5','Graceful Decay','USA'),
(812,'Marvel`s Spider-Man: Miles Morales','PS5','Insomniac Games','USA'),
(813,'Metro Exodus','PS5','4A Games','Ukraine'),
(814,'Nickelodeon All Stars Brawl','PS5','Ludosity','Sweden'),
(815,'Nioh 2','PS5','Team Ninja','Japan'),
(816,'No Man`s Sky','PS5','Hello Games','England'),
(817,'Oddworld: Soulstorm (2021)','PS5','Oddworld Inhabitants','USA'),
(818,'OlliOlli World','PS5','Roll7','England'),
(819,'One Escape','PS5','BUG-Studio','Russia'),
(820,'Overcooked: All You Can Eat Edition','PS5','Ghost Town Games','England'),
(821,'Ovivo','PS5','IzHard','Russia'),
(822,'Planet Coaster','PS5','Frontier Developments','England'),
(823,'Potion Permit','PS5','MassHive Media','Indonesia'),
(824,'Ratchet & Clank: Rift Apart','PS5','Insomniac Games','USA'),
(825,'Resident Evil 2 (2019)','PS5','Capcom','Japan'),
(826,'Resident Evil 3 (2020)','PS5','Capcom','Japan'),
(827,'Resident Evil 7: Biohazard','PS5','Capcom','Japan'),
(828,'Resident Evil Village','PS5','Capcom','Japan'),
(829,'Returnal','PS5','Housemarque','Finland'),
(830,'Rogue Company','PS5','First Watch Games','USA'),
(831,'Rustler','PS5','Jutsu Games','Poland'),
(832,'Sackboy: A Big Adventure','PS5','Sumo Digital','England'),
(833,'Saints Row The Third: Remastered','PS5','Deep Silver Volition','USA'),
(834,'Shantae and The Pirate`s Curse','PS5','WayForward Technologies Inc','USA'),
(835,'Shing!','PS5','Mass Creation','Poland'),
(836,'Sir Lovelot','PS5','pixel.lu','Luxembourg'),
(837,'Sonic Origins','PS5','Sega','Japan'),
(838,'Spacebase Startopia','PS5','Realmforge Studios','Germany'),
(839,'Spirit of the North: Enhanced Edition','PS5','Infuse Studio','USA'),
(840,'Star Wars Jedi: Fallen Order','PS5','Respawn Entertainment','USA'),
(841,'Stray','PS5','BlueTwelve Studio','France'),
(842,'Subnautica','PS5','Unknown Worlds Entertainment','USA'),
(843,'Subnautica: Below Zero','PS5','Unknown Worlds Entertainment','USA'),
(844,'Sumatra: Fate of Yandi','PS5','Cloak and Dagger Games','England'),
(845,'Terminator: Resistance Enhanced','PS5','Teyon','Poland'),
(846,'The Darkside Detective','PS5','Spooky Doorway','Republic of Ireland'),
(847,'The Darkside Detective: A Fumble in the Dark','PS5','Spooky Doorway','Republic of Ireland'),
(848,'The Pedestrian','PS5','Skookum Arts','USA'),
(849,'The Persistence','PS5','Firesprite','England'),
(850,'The Sinking City','PS5','Frogwares','Ukraine'),
(851,'The Stanley Parable: Ultra Deluxe','PS5','Crows Crows Crows','Germany'),
(852,'The Witcher 3: Wild Hunt','PS5','CD Projekt Red','Poland'),
(853,'Tiny Tina`s Wonderlands: Chaotic Great Edition','PS5','Gearbox Software','USA'),
(854,'TOEM','PS5','Something We Made','Sweden'),
(855,'Tony Hawk`s Pro Skater 1 + 2 (2021)','PS5','Vicarious Visions','USA'),
(856,'Twin Robots: Ultimate Edition','PS5','Thinice Games','Spain'),
(857,'Warframe: The New War','PS5','Digital Extremes','Canada'),
(858,'Watch Dogs: Legion','PS5','Ubisoft Toronto','Canada'),
(859,'Worms Rumble','PS5','Team17','England'),
(860,'Wreckfest','PS5','Bugbear Entertainment','Finland'),
(861,'Yakuza: Like a Dragon','PS5','Ryu Ga Gotoku','Japan');