-- PS1, PS2, PSP, PS3, PSVITA, PS4, PSVR and PS5 GAMES
-- DEVELOPERS AND COUNTRIES FROM 23rd November 2009 to 25th December 2023

INSERT INTO Origins VALUES
('A Bugs Life','PS1','TT Games','England'),
('Beyblade: Let It Rip!','PS1','Crave','Japan'),
('Bishi Bashi Special','PS1','Konami','Japan'),
('Buzz Lightyear of Star Command','PS1','TT Games','England'),
('Cho Aniki','PS1','Masaya','Japan'),
('Colin McRae Rally','PS1','Codemasters','England'),
('Crash Bandicoot (1996)','PS1','Naughty Dog','USA'),
('Crash Bandicoot 2 (1997)','PS1','Naughty Dog','USA'),
('Crash Bandicoot 3 (1998)','PS1','Naughty Dog','USA'),
('Crash Team Racing (1999)','PS1','Naughty Dog','USA'),
('Crash Bash','PS1','Eurocom Entertainment Software','England'),
('Destruction Derby','PS1','Reflections Interactive','England'),
('Driver','PS1','Reflections Interactive','England'),
('Fear Effect','PS1','Kronos Digital Entertainment','USA'),
('Fear Effect 2: Retro Helix','PS1','Kronos Digital Entertainment','USA'),
('Final Fantasy V','PS1','Square Enix','Japan'),
('Final Fantasy VI','PS1','Square Enix','Japan'),
('Final Fantasy VII (1997)','PS1','Square Enix','Japan'),
('Final Fantasy VIII','PS1','Square Enix','Japan'),
('Final Fantasy IX','PS1','Square Enix','Japan'),
('Gex','PS1','Crystal Dynamics','USA'),
('Gex 3D: Enter the Gecko','PS1','Crystal Dynamics','USA'),
('Gex: Deep Cover Gecko','PS1','Crystal Dynamics','USA'),
('Hercules','PS1','Eurocom Entertainment Software','England'),
('Hogs of War','PS1','Infogrames Sheffield','England'),
('Jumping Flash','PS1','Team Asobi','Japan'),
('Klonoa: Door to Phantomile (1997)','PS1','Bandai Namco Studios','Japan'),
('Kula World','PS1','Game Design Sweden AB','Sweden'),
('Medievil (1998)','PS1','SCE Cambridge','England'),
('Metal Gear Solid','PS1','Kojima Productions','Japan'),
('Monsters Inc Scare Island','PS1','Artificial Mind and Movement','Canada'),
('Motor Toon Grand Prix 2','PS1','Polyphony Digital','Japan'),
('Oddworld: Abes Oddysee (1997)','PS1','Oddworld Inhabitants','USA'),
('Oddworld: Abes Exoddus (1998)','PS1','Oddworld Inhabitants','USA'),
('PONG','PS1','Supersonic Software','England'),
('Rally Cross','PS1','989 Studios','USA'),
('Rayman','PS1','Ubisoft Montpellier','France'),
('Rayman 2','PS1','Ubisoft Shanghai','China'),
('Resident Evil: Directors Cut (1997)','PS1','Capcom','Japan'),
('Resident Evil 2 (1998)','PS1','Capcom','Japan'),
('Resident Evil 3: Nemesis (1999)','PS1','Capcom','Japan'),
('Sheep Dog n Wolf','PS1','Infogrames Lyon House','France'),
('Silent Hill','PS1','Konami','Japan'),
('Spyro the Dragon (1998)','PS1','Insomniac Games','USA'),
('Spyro 2: Gateway to Glimmer (1999)','PS1','Insomniac Games','USA'),
('Spyro 3: Year of the Dragon (2000)','PS1','Insomniac Games','USA'),
('Suikoden','PS1','Konami','Japan'),
('Suikoden II','PS1','Konami','Japan'),
('Syphon Filter','PS1','Bend Studio','USA'),
('Tekken','PS1','Bandai Namco Studios','Japan'),
('Tekken 2','PS1','Bandai Namco Studios','Japan'),
('Theme Hospital','PS1','Krisalis Software','England'),
('Tomb Raider (1996)','PS1','Core Design','England'),
('Tomb Raider II','PS1','Core Design','England'),
('Tomb Raider III','PS1','Core Design','England'),
('Tomb Raider: Chronicles','PS1','Core Design','England'),
('Tomb Raider: The Last Revelation','PS1','Core Design','England'),
('Tombi!','PS1','Whoopee Camp','Japan'),
('Tombi 2!: The Evil Swine Return','PS1','Whoopee Camp','Japan'),
('Toy Story 2','PS1','TT Games','England'),
('Toy Story Racer','PS1','TT Games','England'),
('Twisted Metal (1995)','PS1','SingleTrac','USA'),
('UmJammer Lammy','PS1','NanaOn-Sha','Japan'),
('Vib-Ribbon','PS1','NanaOn-Sha','Japan'),
('Wipeout (1995)','PS1','Psygnosis','England'),
('WWF! Smackdown 2: Know Your Role','PS1','Yukes','Japan'),
('Deus Ex (2002)','PS2','Ion Storm','USA'),
('Sonic Heroes','PS2','Sega','Japan'),
('Stuntman: Ignition','PS2','Paradigm Entertainment','USA'),
('The Sims','PS2','Maxis','USA'),
('The Sims 2','PS2','Maxis','USA'),
('Ape Escape','PSP','Japan Studio','Japan'),
('Burnout Legends','PSP','Criterion Games','England'),
('Crazy Taxi: Fare Wars','PSP','Sniper Studios','USA'),
('Daxter','PSP','Ready At Dawn','USA'),
('Dead or Alive Paradise','PSP','Project Venus','Japan'),
('Everybody`s Golf 2','PSP','Clap Hanz','Japan'),
('Final Fantasy','PSP','Square Enix','Japan'),
('Final Fantasy II','PSP','Square Enix','Japan'),
('Final Fantasy III','PSP','Square Enix','Japan'),
('Final Fantasy IV','PSP','Square Enix','Japan'),
('Grand Theft Auto: Liberty City Stories','PSP','Rockstar Leeds','England'),
('Grand Theft Auto: Vice City Stories','PSP','Rockstar Leeds','England'),
('Grand Theft Auto: Chinatown Wars','PSP','Rockstar Leeds','England'),
('Gravity Crash','PSP','Just Add Water Ltd','England'),
('Jak and Daxter: The Lost Frontier','PSP','High Impact Games','USA'),
('LEGO Indiana Jones','PSP','TT Games','England'),
('LEGO Batman','PSP','TT Games','England'),
('LEGO Star Wars III: The Clone Wars','PSP','TT Games','England'),
('LEGO Pirates of the Caribbean','PSP','TT Games','England'),
('Prinny','PSP','Nippon Ichi Software','Japan'),
('Ratchet & Clank: Size Matters','PSP','High Impact Games','USA'),
('Resistance: Retribution','PSP','Bend Studio','USA'),
('Super Monkey Ball Adventure','PSP','TT Games','England'),
('Tomb Raider: Legend','PSP','Crystal Dynamics','USA'),
('Tomb Raider: Anniversary','PSP','Crystal Dynamics','USA'),
('Wipeout Pulse','PSP','Psygnosis','England'),
('Alice: Madness Returns','PS3','Spicy Horse','China'),
('Angry Birds Trilogy','PS3','Rovio Entertainment','Finland'),
('Army of Two','PS3','EA Montreal','Canada'),
('Bang Bang Racing','PS3','Playbox','Hungary'),
('Battlefield 3','PS3','DICE','Sweden'),
('Bayonetta','PS3','PlatinumGames','Japan'),
('Beat Hazard Ultra','PS3','Cold Beam Games','England'),
('Bentley`s Hackpack','PS3','Sanzaru Games','USA'),
('Beyond Good and Evil HD','PS3','Ubisoft Montpellier','France'),
('Blur','PS3','Bizarre Creations','England'),
('Brink','PS3','Splash Damage','England'),
('Buzz! Quiz World','PS3','Relentless Software','England'),
('Call of Duty: Modern Warfare 2 (2009)','PS3','Infinity Ward','USA'),
('Crazy Machines Elements','PS3','FAKT Software','Germany'),
('Daytona USA','PS3','Sega','Japan'),
('Dead Rising 2','PS3','Capcom Vancouver','Canada'),
('Dead Space (2008)','PS3','EA Redwood Shores','USA'),
('DeathSpank: The Baconing','PS3','Hothead Games','Canada'),
('Deus Ex: Human Revolution','PS3','Eidos Montreal','Canada'),
('Dishonored','PS3','Arkane Studios','France'),
('DJ Hero','PS3','Ubisoft Leamington','England'),
('DJ Hero 2','PS3','Ubisoft Leamington','England'),
('Duke Nukem Forever','PS3','3D Realms','Denmark'),
('Earthworm Jim HD','PS3','Gameloft','France'),
('F.E.A.R','PS3','Monolith Productions','USA'),
('F1 Race Stars','PS3','Codemasters','England'),
('Family Guy: Back to the Multiverse','PS3','Heavy Iron Studios','USA'),
('Far Cry Classic','PS3','Crytek','Germany'),
('Far Cry 2','PS3','Ubisoft Montreal','Canada'),
('Fat Princess','PS3','Titan Studios','USA'),
('FIFA Street (2012)','PS3','EA Vancouver','Canada'),
('Fight Night Champion','PS3','EA Vancouver','Canada'),
('Final Exam','PS3','Mighty Rocket Studio','France'),
('Final Fantasy XIII','PS3','Square Enix','Japan'),
('Girl Fight','PS3','Kung Fu Factory','USA'),
('God of War (2005)','PS3','Santa Monica Studio','USA'),
('God of War II (2007)','PS3','Santa Monica Studio','USA'),
('Gran Turismo 5','PS3','Polyphony Digital','Japan'),
('Grand Theft Auto IV: The Complete Collection','PS3','Rockstar North','Scotland'),
('Hitman: Absolution','PS3','IO Interactive','Denmark'),
('ICO Classics HD','PS3','Team Asobi','Japan'),
('inFamous','PS3','Sucker Punch Productions','USA'),
('inFamous 2','PS3','Sucker Punch Productions','USA'),
('inFamous: Festival of Blood','PS3','Sucker Punch Productions','USA'),
('Jet Car Stunts','PS3','Grip Games','Czech Republic'),
('Joe Danger 2: The Movie','PS3','Hello Games','England'),
('Kane and Lynch: Dead Men','PS3','IO Interactive','Denmark'),
('Kane and Lynch 2: Dog Days','PS3','IO Interactive','Denmark'),
('Killer is Dead','PS3','Grasshopper Manufacture','Japan'),
('Killzone','PS3','Guerrilla Games','Netherlands'),
('LA Noire','PS3','Team Bondi','Australia'),
('Lemmings (2007)','PS3','Team17','England'),
('LittleBigPlanet','PS3','Media Molecule','England'),
('LittleBigPlanet 2','PS3','Media Molecule','England'),
('LittleBigPlanet Karting','PS3','United Front Games','Canada'),
('Lollipop Chainsaw','PS3','Grasshopper Manufacture','Japan'),
('Lone Survivor: The Director`s Cut','PS3','Superflat Games','England'),
('Mafia II','PS3','2K Czech','Czech Republic'),
('Malicious','PS3','Alvion','Japan'),
('Mensa Academy','PS3','Silverball Studios','England'),
('Metal Gear Solid 2: Sons of Liberty','PS3','Kojima Productions','Japan'),
('Metal Gear Solid 3: Snake Eater','PS3','Kojima Productions','Japan'),
('Metal Gear Solid 4: Guns of the Patriots','PS3','Kojima Productions','Japan'),
('Metal Gear Solid: Peace Walker','PS3','Kojima Productions','Japan'),
('Modnation Racers','PS3','United Front Games','Canada'),
('Mortal Kombat Arcade Kollection','PS3','NetherRealm Studios','USA'),
('Mortal Kombat (2011)','PS3','NetherRealm Studios','USA'),
('Motorstorm: Pacific Rift','PS3','Evolution Studios','England'),
('Motorstorm Apocalypse','PS3','Evolution Studios','England'),
('Motorstorm RC','PS3','Evolution Studios','England'),
('Naughty Bear','PS3','Artificial Mind and Movement','Canada'),
('Need for Speed: Shift','PS3','Slightly Mad Studios','England'),
('Need for Speed: The Run','PS3','EA Black Box','Canada'),
('Need for Speed: Most Wanted (2012)','PS3','Criterion Games','England'),
('Oddworld: Munch`s Oddysee','PS3','Oddworld Inhabitants','USA'),
('Oddworld: Stranger`s Wrath','PS3','Oddworld Inhabitants','USA'),
('PAYDAY: The Heist','PS3','Overkill Software','Sweden'),
('PlayStation All-Stars Battle Royale','PS3','Superbot Entertainment','USA'),
('PlayStation Move Heroes','PS3','Nihilistic Software','USA'),
('Prince of Persia: The Sands of Time','PS3','Ubisoft Montreal','Canada'),
('Prince of Persia: The Two Thrones','PS3','Ubisoft Montreal','Canada'),
('Prince of Persia: Warrior Within','PS3','Ubisoft Montreal','Canada'),
('Pro Evolution Soccer 2010','PS3','Konami','Japan'),
('Quantum Conundrum','PS3','Airtight Games','USA'),
('Ratchet & Clank (2002)','PS3','Insomniac Games','USA'),
('Ratchet & Clank 2','PS3','Insomniac Games','USA'),
('Ratchet & Clank 3','PS3','Insomniac Games','USA'),
('Ratchet: Gladiator','PS3','Insomniac Games','USA'),
('Ratchet & Clank Future: Tools of Destruction','PS3','Insomniac Games','USA'),
('Ratchet & Clank Future: Quest for Booty','PS3','Insomniac Games','USA'),
('Ratchet & Clank Future: A Crack in Time','PS3','Insomniac Games','USA'),
('Ratchet & Clank: QForce','PS3','Insomniac Games','USA'),
('Ratchet & Clank: Nexus','PS3','Insomniac Games','USA'),
('Rayman 3: Hoodlum Havoc HD','PS3','Ubisoft Montpellier','France'),
('Rayman Origins','PS3','Ubisoft Montpellier','France'),
('Red Dead Redemption','PS3','Rockstar San Diego','USA'),
('Resistance: Fall of Man','PS3','Insomniac Games','USA'),
('Saints Row 2','PS3','Volition','USA'),
('Sam and Max Season 3: The Devil`s Playhouse TTG','PS3','Telltale Games','USA'),
('Shadow of the Colossus Classics HD','PS3','Team Asobi','Japan'),
('Silent Hill HD Collection','PS3','Konami','Japan'),
('Siren Blood Curse','PS3','Team Asobi','Japan'),
('Skate 2','PS3','EA Black Box','Canada'),
('Sly Cooper and the Thievius Raccoonus','PS3','Sucker Punch Productions','USA'),
('Sly 2: Band of Thieves','PS3','Sucker Punch Productions','USA'),
('Sly 3: Honour Among Thieves','PS3','Sucker Punch Productions','USA'),
('Sonic Generations','PS3','Sega','Japan'),
('Spec Ops: The Line','PS3','Yager Development','Germany'),
('Streets of Rage 2','PS3','Sega','Japan'),
('Super Rub a Dub','PS3','Sumo Digital','England'),
('Superfrog HD','PS3','Team17','England'),
('Syndicate','PS3','Starbreeze Studios','Sweden'),
('Tales of Graces f','PS3','Bandai Namco Studios','Japan'),
('Tales of Xillia','PS3','Bandai Namco Studios','Japan'),
('Tekken 5: Dark Resurrection','PS3','Bandai Namco Studios','Japan'),
('Tekken Revolution','PS3','Bandai Namco Studios','Japan'),
('The Amazing Spider-Man','PS3','Beenox','Canada'),
('The Cave','PS3','Double Fine Productions','USA'),
('The Cube','PS3','Funbox Media','England'),
('The Darkness','PS3','Starbreeze Studios','Sweden'),
('The Darkness 2','PS3','Digital Extremes','Canada'),
('The House of the Dead: Overkill','PS3','Sega','Japan'),
('The Secret of Monkey Island: Special Edition','PS3','LucasArts','USA'),
('The Simpsons Arcade Game','PS3','Konami','Japan'),
('The Simpsons Game','PS3','EA Redwood Shores','USA'),
('The Sims 3','PS3','Maxis','USA'),
('The Sims 3: Pets','PS3','Maxis','USA'),
('Tiger Woods PGA Tour 11','PS3','EA Tiburon','USA'),
('ToeJam and Earl (1991)','PS3','Johnson Voorsanger Productions','USA'),
('ToeJam and Earl: Panic on Funkotron','PS3','Johnson Voorsanger Productions','USA'),
('Tokyo Jungle','PS3','Team Asobi','Japan'),
('Tomb Raider (2013)','PS3','Crystal Dynamics','USA'),
('Tony Hawk`s Pro Skater HD','PS3','Robomodo','USA'),
('Twisted Metal (2012)','PS3','Eat Sleep Play','USA'),
('UFC 2009 Undisputed','PS3','Yuke`s','Japan'),
('Velocity Ultra','PS3','FuturLab','England'),
('When Vikings Attack','PS3','Clever Beans','England'),
('XCOM Enemy Unknown','PS3','Firaxis Games','USA'),
('Yakuza: Dead Souls','PS3','Ryu Ga Gotoku','Japan'),
('Zombie Tycoon II: Brainhov`s Revenge','PS3','Frima Studio','Canada'),
('Crazy Market','PSVITA','The Game Atelier','France'),
('Deathmatch Village','PSVITA','Bloober Team','Poland'),
('Fat Princess: Piece of Cake','PSVITA','One Loop Games','USA'),
('Flame Over','PSVITA','Laughing Jackal Ltd','England'),
('Football Manager Classic 2014','PSVITA','Sports Interactive','England'),
('Get Off My Lawn!','PSVITA','Digital Leisure Inc','Canada'),
('Gunslugs','PSVITA','Abstraction Games','Netherlands'),
('Jet Set Radio','PSVITA','Sega','Japan'),
('LEGO Batman 2: DC Super Heroes','PSVITA','TT Games','England'),
('ModNation Racers: Road Trip','PSVITA','San Diego Studio','USA'),
('No Heroes Allowed: No Puzzles Either!','PSVITA','ACQUIRE Corp','Japan'),
('Paint Park Plus','PSVITA','Sony Interactive Entertainment','Japan'),
('PlayStation VITA Pets','PSVITA','Spiral House','England'),
('Quell Memento','PSVITA','Fallen Tree Games','England'),
('Rocketbirds: Hardboiled Chicken','PSVITA','Ratloop','USA'),
('Silent Hill: Book of Memories','PSVITA','WayForward Technologies Inc','USA'),
('Skeleton Rider','PSVITA','iSquared Games','England'),
('Sly Cooper: Thieves in Time','PSVITA','Sanzaru Games','USA'),
('Spy Hunter (2012)','PSVITA','TT Games','England'),
('Street Fighter X Tekken','PSVITA','Sucker Punch Productions','USA'),
('SunFlowers','PSVITA','The Game Atelier','France'),
('Surge Deluxe','PSVITA','FuturLab','England'),
('Table Football','PSVITA','Sony Interactive Entertainment','Japan'),
('Table Top Racing','PSVITA','Playrise Digital Ltd','England'),
('TxK','PSVITA','Llamasoft','England'),
('Uncharted: Golden Abyss','PSVITA','Bend Studio','USA'),
('Uncharted: Fight for Fortune','PSVITA','Bend Studio','USA'),
('Wanderjahr','PSVITA','Workyrie Game Studio','Japan'),
('Worms Revolution Extreme','PSVITA','Team17','England'),
('Yomawari: Night Alone','PSVITA','Nippon Ichi Software','Japan'),
('Zero Escape: Virtue`s Last Reward','PSVITA','Spike Chunsoft','Japan'),
('[Prototype]','PS4','Radical Entertainment','Canada'),
('[Prototype 2]','PS4','Radical Entertainment','Canada'),
('101 Ways To Die','PS4','Four Door Lemon','England'),
('60 Seconds! Reatomized','PS4','Robot Gentleman','Poland'),
('A Boy And His Blob','PS4','WayForward Technologies Inc','USA'),
('Absolute Drift: Zen Edition','PS4','FlippFly','USA'),
('Abzu','PS4','Giant Squid Studios','USA'),
('Action Henk','PS4','RageSquid','Netherlands'),
('Active Soccer 2 DX','PS4','The Fox Software','Italy'),
('Amnesia: Collection','PS4','Frictional Games','Sweden'),
('Amplitude','PS4','Harmonix Music Systems','USA'),
('Another World','PS4','Delphine Software','France'),
('Ape Escape 2','PS4','Team Asobi','Japan'),
('ARK: Survival Evolved','PS4','Studio Wildcard','USA'),
('Armello','PS4','League of Geeks','Australia'),
('Armikrog','PS4','Pencil Test Studios','USA'),
('Art Of Balance','PS4','Shin`en Multimedia','Germany'),
('Assault Android Cactus','PS4','Witch Beam','Australia'),
('Aven Colony','PS4','Mothership Entertainment','USA'),
('Back To The Future TTG','PS4','Telltale Games','USA'),
('Badland','PS4','Frogmind Games','Finland'),
('Batman Season 1 TTG','PS4','Telltale Games','USA'),
('Batman Season 2 TTG','PS4','Telltale Games','USA'),
('Batman: Arkham Asylum','PS4','Rocksteady Studios','England'),
('Batman: Arkham City','PS4','Rocksteady Studios','England'),
('Batman: Arkham Knight','PS4','Rocksteady Studios','England'),
('Battlefield 1: Revolution','PS4','DICE','Sweden'),
('Bear With Me','PS4','Exordium Games','Croatia'),
('Beat Cop','PS4','Pixel Crow','Poland'),
('Beyond Eyes','PS4','Tiger & Squid','Netherlands'),
('Beyond Two Souls','PS4','Quantic Dream','France'),
('BioShock 1 & 2: The Collection','PS4','Blind Squirrel Games','USA'),
('BioShock Infinite: The Collection','PS4','Blind Squirrel Games','USA'),
('BLACKSAD: Under the Skin','PS4','Pendulo Studios','Spain'),
('Blood Bowl 2','PS4','Cyanide','France'),
('Bloodborne','PS4','FromSoftware','Japan'),
('Borderlands: Game of the Year Edition','PS4','Gearbox Software','USA'),
('Borderlands: The Handsome Collection','PS4','Gearbox Software','USA'),
('Breaking Enigma','PS4','Alphanu Game Studios','England'),
('Bridge Constructor','PS4','ClockStone Studios','Austria'),
('Broforce','PS4','Free Lives','South Africa'),
('Broken Age','PS4','Double Fine Productions','USA'),
('Brothers: A Tale of Two Sons','PS4','Starbreeze Studios','Sweden'),
('Bud Spencer & Terence Hill - Slaps and Beans','PS4','Trinity Team','Italy'),
('Burnout Paradise: Remastered','PS4','Criterion Games','England'),
('Call of Duty: Black Ops III','PS4','Treyarch','USA'),
('Canis Canem Edit (Bully)','PS4','Rockstar Vancouver','Canada'),
('Captain Tsubasa: Rise of New Champions','PS4','Tamsoft','Japan'),
('Castle Crashers: Remastered','PS4','The Behemoth','USA'),
('Castlevania Requiem: Symphony of the Night and Rondo of Blood','PS4','Konami','Japan'),
('Catherine: Full Body','PS4','Atlus','Japan'),
('Cel Damage HD','PS4','Finish Line Games','Canada'),
('Celeste','PS4','Extremely OK Games','Canada'),
('Child Of Light','PS4','Ubisoft Montreal','Canada'),
('Chime Sharp','PS4','Chilled Mouse','England'),
('Cities: Skylines','PS4','Colossal Order','Finland'),
('Claire','PS4','Hailstorm Games','USA'),
('ClusterTruck','PS4','Landfall Games','Sweden'),
('Code Vein','PS4','Bandai Namco Studios','Japan'),
('Color Slayer','PS4','The Domaginarium','El Salvador'),
('Concrete Genie','PS4','Pixelopus','USA'),
('Cosmophony','PS4','Bento Studio','France'),
('CounterSpy','PS4','Dynamighty','USA'),
('Crash Bandicoot: N Sane Trilogy (2017)','PS4','Vicarious Visions','USA'),
('Crash Team Racing: Nitro Fueled (2019)','PS4','Beenox','Canada'),
('Croixleur Sigma','PS4','souvenir circ','Japan'),
('Curse of the Dead Gods','PS4','Passtech Games','France'),
('Dangerous Golf','PS4','Three Fields Entertainment','England'),
('Danger Zone','PS4','Three Fields Entertainment','England'),
('Dangerous Driving','PS4','Three Fields Entertainment','England'),
('Dark Cloud','PS4','Level-5','Japan'),
('Dark Chronicle (Dark Cloud 2)','PS4','Level-5','Japan'),
('Dark Souls Remastered','PS4','FromSoftware','Japan'),
('Dark Souls II: Scholar of the First Sin','PS4','FromSoftware','Japan'),
('Dark Souls III','PS4','FromSoftware','Japan'),
('Day Of The Tentacle Remastered','PS4','LucasArts','USA'),
('Days Gone','PS4','Bend Studio','USA'),
('de Blob','PS4','Blue Tongue Entertainment','Australia'),
('Dead End Job','PS4','Ant Workshop','Scotland'),
('Dead Island: Retro Revenge','PS4','Empty Clip Studios','USA'),
('Dead or Alive 5: Last Round','PS4','Team Ninja','Japan'),
('Dead Rising','PS4','Capcom','Japan'),
('Deadpool','PS4','High Moon Studios','USA'),
('Death Squared','PS4','SMG Studio','Australia'),
('DEEEER Simulator: Your Average Everyday Deer Game','PS4','Gibier Games','Japan'),
('Descenders','PS4','RageSquid','Netherlands'),
('Destroy All Humans! (2005)','PS4','Pandemic Studios','USA'),
('Destroy All Humans! (2020)','PS4','Black Forest Games','Germany'),
('Destroy All Humans! 2 (2006)','PS4','Pandemic Studios','USA'),
('Detroit: Become Human','PS4','Quantic Dream','France'),
('Devil May Cry Trilogy HD Collection','PS4','Capcom','Japan'),
('Devil May Cry 4','PS4','Capcom','Japan'),
('Devil May Cry 5','PS4','Capcom','Japan'),
('Dex','PS4','Dreadlocks Ltd','Czech Republic'),
('Disney Classic Games: Aladdin & The Lion King','PS4','Digital Eclipse','USA'),
('Doki-Doki Universe','PS4','HumaNature Studios','USA'),
('Don`t Starve','PS4','Klei Entertainment','Canada'),
('Donut County','PS4','Ben Esposito','USA'),
('DOOM (1993)','PS4','id Software','USA'),
('DOOM II','PS4','id Software','USA'),
('DOOM 64','PS4','Midway Games','USA'),
('Downwell','PS4','Moppin','Japan'),
('DreamBall','PS4','Rampage Game Studio','Spain'),
('Dreams','PS4','Media Molecule','England'),
('Duke Nukem 3D','PS4','Gearbox Software','USA'),
('Empire of Sin: Deluxe Edition','PS4','Romero Games','Republic of Ireland'),
('Enter The Gungeon','PS4','Dodge Roll','USA'),
('Entwined','PS4','Pixelopus','USA'),
('Escape Plan','PS4','Fun Bits Interactive','USA'),
('Everybody`s Golf (2017)','PS4','Clap Hanz','Japan'),
('Exit the Gungeon','PS4','Dodge Roll','USA'),
('Fahrenheit (Indigo Prophecy)','PS4','Quantic Dream','France'),
('Fallout 4','PS4','Bethesda Game Studios','USA'),
('Far Cry 3','PS4','Ubisoft Montreal','Canada'),
('Far Cry 4','PS4','Ubisoft Montreal','Canada'),
('Far Cry: Primal','PS4','Ubisoft Montreal','Canada'),
('Far Cry 5','PS4','Ubisoft Montreal','Canada'),
('Far Cry: New Dawn','PS4','Ubisoft Montreal','Canada'),
('Fat Princess Adventures','PS4','Fun Bits Interactive','USA'),
('Fez','PS4','Polytron Corporation','Canada'),
('FIFA 18','PS4','EA Vancouver','Canada'),
('FIFA 19','PS4','EA Vancouver','Canada'),
('FIFA 20','PS4','EA Vancouver','Canada'),
('Final Fantasy X/X-2 HD Remaster','PS4','Square Enix','Japan'),
('Final Fantasy XV: Royal Edition','PS4','Square Enix','Japan'),
('Five Dates','PS4','Wales Interactive','Wales'),
('Flashback','PS4','Delphine Software International','France'),
('Flockers','PS4','Team17','England'),
('flOw','PS4','Thatgamecompany','USA'),
('Flower','PS4','Thatgamecompany','USA'),
('forma.8','PS4','MixedBag','Italy'),
('Formula Retro Racing','PS4','Repixel8','England'),
('Futuridium','PS4','MixedBag','Italy'),
('Game Of Thrones TTG','PS4','Telltale Games','USA'),
('Generation Zero','PS4','Systemic Reaction','Sweden'),
('Geometry Wars 3: Dimensions Evolved','PS4','Lucid Games','England'),
('Ghost Blade HD','PS4','Hucast Games','Germany'),
('Ghost of Tsushima','PS4','Sucker Punch Productions','USA'),
('Ghostbusters','PS4','FireForge Games','USA'),
('Goat Simulator','PS4','Coffee Stain Studios','Sweden'),
('God of War III Remastered','PS4','Santa Monica Studio','USA'),
('God of War (2018)','PS4','Santa Monica Studio','USA'),
('Godlike Burger','PS4','Liquid Pug','Belarus'),
('Going Under','PS4','Aggro Crab','USA'),
('Good Dog Bad Dog','PS4','Play Em','USA'),
('Granblue Fantasy: Versus','PS4','Arc System Works','Japan'),
('Grand Ages: Medieval','PS4','Gaming Minds Studios','Germany'),
('Grand Theft Auto III (2001)','PS4','Rockstar North','Scotland'),
('Grand Theft Auto: Vice City (2002)','PS4','Rockstar North','Scotland'),
('Grand Theft Auto: San Andreas (2004)','PS4','Rockstar North','Scotland'),
('Grim Fandango Remastered','PS4','LucasArts','USA'),
('Harvest Moon: A Wonderful Life','PS4','Marvelous Interactive','Japan'),
('Hatoful Boyfriend','PS4','Mediatonic','England'),
('Heart&Slash','PS4','aheartfulofgames','Spain'),
('Heavy Rain','PS4','Quantic Dream','France'),
('Helldivers','PS4','Arrowhead Game Studios','Sweden'),
('Hitman 2','PS4','IO Interactive','Denmark'),
('Hohokum','PS4','Honeyslug','England'),
('Hollow Knight: Voidheart Edition','PS4','Team Cherry','Australia'),
('Holy Potatoes! A Weapon Shop?!','PS4','Daylight Studios','Singapore'),
('Holy Potatoes! We`re in Space?!','PS4','Daylight Studios','Singapore'),
('Holy Potatoes! What the Hell?!','PS4','Daylight Studios','Singapore'),
('Home','PS4','Benjamin Rivers Inc','Canada'),
('HoPiKo','PS4','Laser Dog','England'),
('Horizon Zero Dawn','PS4','Guerrilla Games','Netherlands'),
('Hotline Miami','PS4','Dennaton Games','Sweden'),
('Hotline Miami 2: Wrong Number','PS4','Dennaton Games','Sweden'),
('Hue','PS4','Fiddlesticks','England'),
('I am Bread','PS4','Bossa Studios','England'),
('inFamous Second Son','PS4','Sucker Punch Productions','USA'),
('inFamous First Light','PS4','Sucker Punch Productions','USA'),
('Injustice: Gods Among Us','PS4','NetherRealm Studios','USA'),
('Injustice 2','PS4','NetherRealm Studios','USA'),
('Iris and the Giant','PS4','Louis Rigaud','France'),
('Jak and Daxter: The Precursor Legacy','PS4','Naughty Dog','USA'),
('Jak II: Renegade','PS4','Naughty Dog','USA'),
('Jak 3','PS4','Naughty Dog','USA'),
('Jak X: Combat Racing','PS4','Naughty Dog','USA'),
('Jazzpunk: Director`s Cut','PS4','Necrophone Games','Canada'),
('Jetpack Joyride','PS4','Halfbrick Studios','Australia'),
('Journey','PS4','thatgamecompany','USA'),
('Just Die Already','PS4','DoubleMoose Games','Sweden'),
('Kandagawa Jet Girls','PS4','Honey Parade Games','Japan'),
('Katamari Damacy: Reroll','PS4','Bandai Namco Studios','Japan'),
('Keep Talking and Nobody Explodes','PS4','Steel Crate Games','Canada'),
('Kingdom Hearts HD 1.5 & 2.5 Remix','PS4','Square Enix','Japan'),
('Kingdom Hearts HD 2.8 Final Chapter Prologue','PS4','Square Enix','Japan'),
('Kingdom Hearts III','PS4','Square Enix','Japan'),
('Kingdoms of Amalur: Re-Reckoning','PS4','Kaiko','Germany'),
('Knack','PS4','Team Asobi','Japan'),
('Knack 2','PS4','Team Asobi','Japan'),
('LA Cops','PS4','Modern Dream','England'),
('LEGO City Undercover','PS4','TT Games','England'),
('LEGO Marvel Super-Heroes','PS4','TT Games','England'),
('LEGO Harry Potter Collection','PS4','TT Games','England'),
('LEGO DC Super-Villains','PS4','TT Games','England'),
('Leisure Suit Larry: Wet Dreams Don`t Dry','PS4','CrazyBunch','Germany'),
('Leisure Suit Larry: Wet Dreams Dry Twice','PS4','CrazyBunch','Germany'),
('Lichtspeer','PS4','Lichthund','Poland'),
('Life Is Strange','PS4','Dontnod Entertainment','France'),
('Like a Dragon (Yakuza 0)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Like a Dragon Kiwami (Yakuza Kiwami)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Like a Dragon Kiwami 2 (Yakuza Kiwami 2)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Like a Dragon 3 (Yakuza 3 Remastered)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Like a Dragon 4 (Yakuza 4 Remastered)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Like a Dragon 5 (Yakuza 5 Remastered)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Like a Dragon 6 (Yakuza 6: The Song of Life)','PS4','Ryu Ga Gotoku Studio','Japan'),
('Little Nightmares','PS4','Tarsier Studios','Sweden'),
('LittleBigPlanet 3','PS4','Sumo Digital','England'),
('LocoRoco','PS4','Team Asobi','Japan'),
('Lovers In A Dangerous Spacetime','PS4','Asteroid Base','Canada'),
('LUMO','PS4','Just Add Water Ltd','England'),
('Mafia: Definitive Edition (2020)','PS4','Hangar 13','USA'),
('Mafia III','PS4','Hangar 13','USA'),
('Manhunt','PS4','Rockstar North','Scotland'),
('Manual Samuel','PS4','Perfectly Paranormal','Norway'),
('Marvel`s Guardians Of The Galaxy TTG','PS4','Telltale Games','USA'),
('Marvel`s Spider-Man','PS4','Insomniac Games','USA'),
('Mass Effect: Legendary Edition','PS4','Bioware','Canada'),
('Max Payne','PS4','Remedy Entertainment','Finland'),
('MediEvil (2019)','PS4','Other Ocean Emeryville','USA'),
('Mega Man Legacy Collection','PS4','Digital Eclipse','USA'),
('Mega Man Legacy Collection 2','PS4','Capcom','Japan'),
('Mega Man X Legacy Collection','PS4','Capcom','Japan'),
('Mega Man X Legacy Collection 2','PS4','Capcom','Japan'),
('Metal Gear Solid V: The Phantom Pain','PS4','Kojima Productions','Japan'),
('Metro Redux','PS4','4A Games','Ukraine'),
('Micro Machines World Series','PS4','Codemasters','England'),
('Minecraft Dungeons','PS4','Mojang Studios','Sweden'),
('Minutes','PS4','Red Phantom Games','England'),
('Monopoly Family Fun Pack','PS4','Asobo Studio','France'),
('Monster Hunter World: Iceborne','PS4','Capcom','Japan'),
('Monster Prom: XXL','PS4','Beautiful Glitch','Spain'),
('Mortal Kombat X','PS4','NetherRealm Studios','USA'),
('Mortal Shell','PS4','Cold Symmetry','USA'),
('Mother Russia Bleeds','PS4','Le Cartel Studio','France'),
('Need for Speed Heat','PS4','EA Gothenburg','Sweden'),
('Neon Chrome','PS4','10tons','Finland'),
('Neon Drive','PS4','Fraoula','Slovenia'),
('Ni No Kuni: Wrath of the White Witch','PS4','Level-5','Japan'),
('Ni No Kuni II: Revenant Kingdom','PS4','Level-5','Japan'),
('Night Book','PS4','Wales Interactive','Wales'),
('Ninja Senki DX','PS4','Tribute Games','Canada'),
('Nitroplus Blasterz: Heroines Infinite Duel','PS4','Team Arcana','Japan'),
('Octodad: Dadliest Catch','PS4','Young Horses','USA'),
('Oddworld: New n Tasty','PS4','Just Add Water Ltd','England'),
('Okami HD','PS4','Clover Studio','Japan'),
('OlliOlli: Epic Combo Edition','PS4','Roll7','England'),
('OlliOlli 2','PS4','Roll7','England'),
('One Piece Unlimited World Red','PS4','Ganbarion','Japan'),
('Onee Chanbara Origin','PS4','Tamsoft','Japan'),
('Outbreak: Epidemic','PS4','Dead Drop Studios LLC','USA'),
('Outlast','PS4','Red Barrels','Canada'),
('Oxenfree','PS4','Night School Studio','USA'),
('PAC-MAN 256','PS4','Hipster Whale','Australia'),
('PaRappa The Rapper Remastered','PS4','Team Asobi','Japan'),
('PaRappa The Rapper 2','PS4','NanaOn-Sha','Japan'),
('Party Hard','PS4','Pinokl Games','Ukraine'),
('Party Hard 2','PS4','Pinokl Games','Ukraine'),
('Persona 5','PS4','Atlus','Japan'),
('Persona 5 Strikers','PS4','Omega Force','Japan'),
('PGA Tour 2K21','PS4','HB Studios','Canada'),
('Pic-A-Pix Color','PS4','Lightwood Games','England'),
('PixelJunk Shooter Ultimate','PS4','Double Eleven','England'),
('Plants vs Zombies: Battle for Neighborville','PS4','PopCap Games','USA'),
('Please Don`t Touch Anything','PS4','Four Quarters','Russia'),
('Poltergeist: A Pixelated Horror','PS4','Glitchy Pixel','Colombia'),
('Polybius','PS4','Llamasoft','England'),
('PONG Quest','PS4','Chequered Ink Ltd','England'),
('Postal Redux','PS4','Running With Scissors','USA'),
('Primal','PS4','SCE Cambridge','England'),
('Psychonauts','PS4','Double Fine Productions','USA'),
('Psychonauts 2','PS4','Double Fine Productions','USA'),
('Pumped BMX+','PS4','Yeah, Us!','England'),
('Putty Squad','PS4','System 3 Software','England'),
('Quake','PS4','id Software','USA'),
('Quest Of Dungeons','PS4','Upfall Studios','Portugal'),
('Rally Copters','PS4','Depth First Games','USA'),
('Ratchet & Clank (2016)','PS4','Insomniac Games','USA'),
('Rayman Legends','PS4','Ubisoft Montpellier','France'),
('Red Dead Revolver','PS4','Rockstar San Diego','USA'),
('Red Dead Redemption 2','PS4','Rockstar San Diego','USA'),
('Resident Evil: Code Veronica X','PS4','Capcom','Japan'),
('Resident Evil 0','PS4','Capcom','Japan'),
('Resident Evil (2002)','PS4','Capcom','Japan'),
('Resident Evil 4 (2005)','PS4','Capcom','Japan'),
('Resident Evil 5','PS4','Capcom','Japan'),
('Resident Evil Revelations','PS4','Capcom','Japan'),
('Resident Evil 6','PS4','Capcom','Japan'),
('Resident Evil Revelations 2','PS4','Capcom','Japan'),
('Resident Evil: Resistance','PS4','Capcom','Japan'),
('Resident Evil: Re:Verse','PS4','Capcom','Japan'),
('RESOGUN','PS4','Housemarque','Finland'),
('Retro City Rampage DX','PS4','Vblank Entertainment','Canada'),
('Riptide GP: Renegade','PS4','Vector Unit','USA'),
('Rise Of The Tomb Raider','PS4','Crystal Dynamics','USA'),
('Risk Of Rain','PS4','Hopoo Games','USA'),
('Road Redemption','PS4','EQ-Games','USA'),
('Rock Boshers DX: Director`s Cut','PS4','Tikipod','England'),
('Rocket League','PS4','Psyonix','USA'),
('Rocketbirds 2: Evolution','PS4','Ratloop Asia','Singapore'),
('Rogue Legacy','PS4','Cellar Door Games','Canada'),
('Rollercoaster Dreams','PS4','Bimboosoft','Japan'),
('Run Sausage Run!','PS4','CrazyLabs','Israel'),
('Saban`s Mighty Morphin Power Rangers: Mega Battle','PS4','Bamtang Games','Peru'),
('Saints Row IV: Re-Elected','PS4','High Voltage Software','USA'),
('Saints Row IV: Gat out of Hell','PS4','High Voltage Software','USA'),
('Sam and Max Season 1: Save The World TTG','PS4','Telltale Games','USA'),
('Sam and Max Season 2: Beyond Time and Space TTG','PS4','Telltale Games','USA'),
('Scott Pilgrim vs The World: The Game','PS4','Ubisoft Montreal','Canada'),
('Scribblenauts Mega Pack','PS4','5th Cell','USA'),
('Sekiro: Shadows Die Twice','PS4','FromSoftware','Japan'),
('Shadow of the Tomb Raider','PS4','Eidos Montreal','Canada'),
('Shovel Knight: Treasure Trove','PS4','Yacht Club Games','USA'),
('Shovel Knight: Pocket Dungeon','PS4','Yacht Club Games','USA'),
('ShredIt','PS4','Extra Mile Studios','Scotland'),
('Slain: Back from Hell','PS4','Wolf Brew Games','USA'),
('Slay the Spire','PS4','Humble Bundle','USA'),
('Sleeping Dogs: Definitive Edition','PS4','United Front Games','Canada'),
('Slender: The Arrival','PS4','Blue Isle Studios','Canada'),
('Sniper Elite V2 Remastered','PS4','Rebellion Developments','England'),
('Sonic Mania','PS4','Christian Whitehead','Australia'),
('SoulCalibur VI','PS4','Bandai Namco Studios','Japan'),
('Sound Shapes','PS4','Queasy Games','Canada'),
('South Park: The Stick of Truth','PS4','Obsidian Entertainment','USA'),
('South Park: The Fractured But Whole','PS4','Ubisoft San Francisco','USA'),
('Spelunky','PS4','Mossmouth LLC','USA'),
('SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated','PS4','Purple Lamp Studios','Austria'),
('Spy Chameleon','PS4','Unfinished Pixel','Spain'),
('Spyro Reignited Trilogy (2018)','PS4','Toys for Bob','USA'),
('Star Wars Episode I: Pod Racer','PS4','LucasArts','USA'),
('Stardew Valley','PS4','ConcernedApe','USA'),
('Stealth Inc: A Clone In The Dark','PS4','Curve Studios','England'),
('Stealth Inc 2: A Game Of Clones','PS4','Curve Studios','England'),
('SteamWorld Dig','PS4','Image & Form','Sweden'),
('SteamWorld Heist','PS4','Image & Form','Sweden'),
('SteamWorld Dig 2','PS4','Image & Form','Sweden'),
('Stikbold! A Dodgeball Adventure','PS4','Game Swing','Denmark'),
('Stranded Deep','PS4','Beam Team Games','Australia'),
('Street Fighter 30th Anniversary Collection','PS4','Capcom','Japan'),
('Super Kickers League Ultimate','PS4','Xaloc Studios','Spain'),
('Super Meat Boy!','PS4','Team Meat','USA'),
('Super Monkey Ball: Banana Blitz HD','PS4','New Entertainment R&D Dept','Japan'),
('Super Stardust Ultra','PS4','Housemarque','Finland'),
('Superbeat: Xonic EX','PS4','Nurijoy','Korea Republic'),
('Supermarket Shriek','PS4','Billy Goat Entertainment Ltd','Northern Ireland'),
('Surgeon Simulator','PS4','Bossa Studios','England'),
('Switch Galaxy Ultra','PS4','Atomicom','England'),
('Syrup and the Ultimate Sweet','PS4','NomNomNami','USA'),
('Table Top Racing: World Tour','PS4','Playrise Digital Ltd','England'),
('Tales From The Borderlands','PS4','Telltale Games','USA'),
('Team Sonic Racing','PS4','Sumo Digital','England'),
('Tearaway Unfolded','PS4','Media Molecule','England'),
('Tekken 7','PS4','Bandai Namco Studios','Japan'),
('Tembo The Badass Elephant','PS4','Game Freak','Japan'),
('Tennis in the Face','PS4','10tons','Finland'),
('Tennis World Tour 2','PS4','Big Ant Studios','Australia'),
('Terraria','PS4','Re-Logic','USA'),
('Tethered','PS4','Secret Sorcery','England'),
('Tetris Ultimate','PS4','SoMa Play','USA'),
('That`s You!','PS4','Wish Studios','England'),
('The Amazing American Circus','PS4','Juggler Games','Poland'),
('The Binding of Isaac: Rebirth','PS4','Nicalis','USA'),
('The Bug Butcher','PS4','Awfully Nice Studios','Austria'),
('The Complex','PS4','Wales Interactive','Wales'),
('The Crew','PS4','Ivory Tower','France'),
('The Disney Afternoon Collection','PS4','Digital Eclipse','USA'),
('The Escapists','PS4','Mouldy Toof Studios','England'),
('The Evil Within','PS4','Tango Gameworks','Japan'),
('The Flame in the Flood','PS4','The Molasses Flood','USA'),
('The Last Guardian','PS4','Team Asobi','Japan'),
('The Last Of Us Remastered','PS4','Naughty Dog','USA'),
('The Last Of Us: Left Behind Remastered','PS4','Naughty Dog','USA'),
('The Last of Us Part II','PS4','Naughty Dog','USA'),
('The Outer Worlds','PS4','Obsidian Entertainment','USA'),
('The Sims 4','PS4','Maxis','USA'),
('The Swapper','PS4','Facepalm Games','Finland'),
('The Unfinished Swan','PS4','Giant Sparrow','USA'),
('The Walking Dead Season 1 TTG','PS4','Telltale Games','USA'),
('The Walking Dead Season 2 TTG','PS4','Telltale Games','USA'),
('The Walking Dead Season 3 TTG','PS4','Telltale Games','USA'),
('The Walking Dead: The Final Season TTG','PS4','Telltale Games','USA'),
('The Warriors','PS4','Rockstar Toronto','Canada'),
('The Witness','PS4','Thekla Inc','USA'),
('The Wolf Among Us Season 1 TTG','PS4','Telltale Games','USA'),
('Think of the Children','PS4','Jammed Up Studios','Australia'),
('This Is The Police','PS4','Weappy Studio','Belarus'),
('Thomas Was Alone','PS4','Mike Bithell','England'),
('Tiny Tina`s Assault on Dragon Keep: A Wonderlands One-Shot Adventure','PS4','Gearbox Software','USA'),
('Titan Attacks!','PS4','Puppy Games','England'),
('ToeJam & Earl: Back In The Groove (2019)','PS4','HumaNature Studios','USA'),
('Total Arcade Racing','PS4','Pretty Fly Studios','Sweden'),
('Touhou Double Focus','PS4','Aqua Style','Japan'),
('Trials Fusion: The Awesome MAX Edition','PS4','RedLynx','France'),
('Tribes of Midgard','PS4','Norsfell Games','Canada'),
('Tricky Towers','PS4','WeirdBeard','Netherlands'),
('Trine: Enchanted Edition','PS4','Frozenbyte','Finland'),
('Trine 2: Complete Story','PS4','Frozenbyte','Finland'),
('Trine 3: The Artifacts Of Power','PS4','Frozenbyte','Finland'),
('Tropico 5','PS4','Haemimont Games','Bulgaria'),
('Trover Saves The Universe','PS4','Squanch Games','USA'),
('Turnip Boy Commits Tax Evasion','PS4','Snoozy Kazoo','USA'),
('Twisted Metal: Black','PS4','Incognito Entertainment','USA'),
('Two Point Hospital','PS4','Two Point Studios','England'),
('Typoman','PS4','Brainseed Factory','Germany'),
('UFC 4','PS4','EA Vancouver','Canada'),
('Ultratron','PS4','Puppy Games','England'),
('Unbox: Newbie`s Adventure','PS4','Prospect Games','England'),
('Uncanny Valley','PS4','Cowardly Creations','USA'),
('Uncharted: Drake`s Fortune','PS4','Naughty Dog','USA'),
('Uncharted 2: Among Thieves','PS4','Naughty Dog','USA'),
('Uncharted 3: Drake`s Deception','PS4','Naughty Dog','USA'),
('Uncharted 4: A Thief`s End','PS4','Naughty Dog','USA'),
('Uncharted: The Lost Legacy','PS4','Naughty Dog','USA'),
('Undertale','PS4','tobyfox','USA'),
('UNO','PS4','Ubisoft Chengdu','China'),
('Unravel','PS4','Coldwood Interactive','Sweden'),
('Until Dawn','PS4','Supermassive Games','England'),
('Untitled Goose Game','PS4','House House','Australia'),
('Velocity 2X','PS4','FuturLab','England'),
('Viking Squad','PS4','Slick Entertainment','Canada'),
('Virtua Fighter 5: Ultimate Showdown','PS4','Sega','Japan'),
('Volume','PS4','Mike Bithell','England'),
('Watch_Dogs','PS4','Ubisoft Montreal','Canada'),
('Watch_Dogs 2','PS4','Ubisoft Montreal','Canada'),
('while true: learn( )','PS4','Luden.io','Russia'),
('Wipeout Omega Collection','PS4','XDev','England'),
('Wolfenstein: The New Order','PS4','MachineGames','Sweden'),
('Wolfenstein: The Old Blood','PS4','MachineGames','Sweden'),
('Wolfenstein II: The New Colossus','PS4','MachineGames','Sweden'),
('Wolfenstein: Youngblood','PS4','MachineGames','Sweden'),
('Worms Battlegrounds','PS4','Team17','England'),
('Worms WMD','PS4','Team17','England'),
('WRC 6','PS4','Kylotonn','France'),
('WWE 2K Battlegrounds','PS4','Saber Interactive','USA'),
('XCOM 2','PS4','Firaxis Games','USA'),
('Xenoraid','PS4','10tons','Finland'),
('Yomawari: Midnight Shadows','PS4','Nippon Ichi Software','Japan'),
('Yooka-Laylee','PS4','Playtonic Games','England'),
('Yooka-Laylee and the Impossible Lair','PS4','Playtonic Games','England'),
('Yu-Gi-Oh! Legacy of the Duelist','PS4','Other Ocean Interactive','Canada'),
('Accounting Plus','PSVR','Squanch Games','USA'),
('Animal Force','PSVR','ISVR','China'),
('Apex Construct','PSVR','Fast Travel Games','Sweden'),
('Apocalypse Rider','PSVR','VRMonkey','Brazil'),
('Arizona Sunshine','PSVR','Vertigo Games','Netherlands'),
('ASTRO BOT Rescue Mission','PSVR','Team Asobi','Japan'),
('Batman: Arkham VR','PSVR','Rocksteady Studios','England'),
('Beat Saber','PSVR','Beat Games','Czech Republic'),
('BoxVR','PSVR','FitXR','USA'),
('Budget Cuts','PSVR','Neat Corporation','Sweden'),
('Carnival Games VR','PSVR','Cat Daddy Games','USA'),
('Catch & Release','PSVR','metricminds','Germany'),
('CoolpaintrVR','PSVR','Wildbit Studios','Spain'),
('Creed: Rise To Glory','PSVR','Survios','USA'),
('Discovery','PSVR','Noowanda','Germany'),
('DOOM VFR','PSVR','id Software','USA'),
('Dream Match Tennis VR','PSVR','Bimboosoft','Japan'),
('DriveClub VR','PSVR','Evolution Studios','England'),
('Drunkn Bar Fight','PSVR','The Munky','USA'),
('Eagle Flight','PSVR','Ubisoft Montreal','Canada'),
('EVE: Valkyrie','PSVR','CCP Games','Iceland'),
('Everest VR','PSVR','Solfar Studios','Iceland'),
('Everybody`s Golf VR','PSVR','Clap Hanz','Japan'),
('Floor Plan','PSVR','Turbo Button','USA'),
('Fruit Ninja VR','PSVR','Halfbrick Studios','Australia'),
('Groundhog Day: Like Father Like Son','PSVR','Tequila Works','Spain'),
('Gun Club VR','PSVR','The Binary Mill','Australia'),
('Headmaster','PSVR','Frame Interactive','USA'),
('Homestar VR','PSVR','Pocket Ohira Tech','Japan'),
('Horror Bar VR','PSVR','VR Factory','Poland'),
('Hotel R n R','PSVR','Wolf & Wood Interactive Ltd','England'),
('Hustle Kings VR','PSVR','VooFoo Studios','England'),
('I Expect You To Die','PSVR','Schell Games','USA'),
('I Expect You to Die 2','PSVR','Schell Games','USA'),
('Job Simulator VR','PSVR','Owlchemy Labs','USA'),
('Kingdom Hearts: VR Experience','PSVR','Square Enix','Japan'),
('Knockout League','PSVR','Grab Games','USA'),
('Kona VR','PSVR','Parabole','Canada'),
('Lethal VR','PSVR','Three Fields Entertainment','England'),
('Marvel`s Iron Man VR','PSVR','Camouflaj','USA'),
('Mervils: A VR Adventure','PSVR','VitruviusVR','Canada'),
('Moss','PSVR','Polyarc','USA'),
('Penn & Teller VR','PSVR','Gearbox Software','USA'),
('Perfect VR','PSVR','nDreams','England'),
('PlayStation VR Worlds','PSVR','London Studio','England'),
('Psychonauts in the Rhombus Of Ruin VR','PSVR','Double Fine Productions','USA'),
('Rez Infinite VR','PSVR','Enhance Games','USA'),
('Rick & Morty: Virtual Rick-ality','PSVR','Owlchemy Labs','USA'),
('RIGS: Mechanized Combat League VR','PSVR','Guerrilla Cambridge','England'),
('Sam & Max: This Time It`s Virtual!','PSVR','HappyGiant','USA'),
('Shooty Fruity','PSVR','nDreams','England'),
('Skyrim VR','PSVR','Bethesda Game Studios','USA'),
('Sniper Elite VR','PSVR','Just Add Water Ltd','England'),
('Space Pirate Trainer VR','PSVR','I-Illusions','Belgium'),
('Sprint Vector','PSVR','Survios','USA'),
('Star Trek: Bridge Crew VR','PSVR','Red Storm Entertainment','USA'),
('Superhot VR','PSVR','Superhot Team','Poland'),
('Tetris Effect: Connected','PSVR','Monstars','Japan'),
('The American Dream','PSVR','Samurai Punk','Australia'),
('The Guy VR','PSVR','Chubby Pixel','Italy'),
('The Playroom VR','PSVR','Team Asobi','Japan'),
('The Walking Dead: Saints and Sinners','PSVR','Skydance Interactive','USA'),
('Tiny Trax','PSVR','FuturLab','England'),
('Track Lab','PSVR','Little Chicken','Netherlands'),
('Trackmania Turbo','PSVR','Nadeo','France'),
('Traffic Jams','PSVR','Little Chicken','Netherlands'),
('Tumble VR','PSVR','Supermassive Games','England'),
('Ultrawings','PSVR','Bit Planet Games','USA'),
('Until Dawn: Rush Of Blood','PSVR','Supermassive Games','England'),
('Until You Fall','PSVR','WayTooManyGames','USA'),
('VR Karts','PSVR','Viewpoint Games','England'),
('VR Ping Pong','PSVR','Reddoll Srl','Italy'),
('VR The Diner Duo','PSVR','Whirlybird Games','Sweden'),
('Wanderer','PSVR','Oddboy','New Zealand'),
('You Are Being Followed','PSVR','Uncommon Chocolate','Scotland'),
('A Plague Tale: Innocence','PS5','Asobo Studio','France'),
('A Plague Tale: Requiem','PS5','Asobo Studio','France'),
('Alan Wake Remastered','PS5','Remedy Entertainment','Finland'),
('Aliens: Fireteam Elite','PS5','Cold Iron Studios','USA'),
('Apex Legends','PS5','Respawn Entertainment','USA'),
('Art of Rally','PS5','Funselektor Labs Inc','Canada'),
('Assassin`s Creed Valhalla: Ultimate Edition','PS5','Ubisoft Montreal','Canada'),
('Astro`s Playroom','PS5','Team Asobi','Japan'),
('AWAY: The Survival Series','PS5','Breaking Walls','Canada'),
('Axiom Verge 2','PS5','Thomas Happ Games','USA'),
('Battlefield 2042','PS5','EA DICE','Sweden'),
('Biomutant','PS5','Experiment 101','Sweden'),
('BloodRayne: ReVamped','PS5','Terminal Reality','USA'),
('BloodRayne 2: ReVamped','PS5','Terminal Reality','USA'),
('Borderlands 3','PS5','Gearbox Software','USA'),
('Bugsnax','PS5','Young Horses','USA'),
('Call of Duty: Black Ops Cold War','PS5','Treyarch','USA'),
('Can`t Drive This','PS5','Pixel Maniacs','Germany'),
('Chicken Police: Paint It Red','PS5','The Wild Gentlemen','Hungary'),
('Chicory: A Colorful Tale','PS5','Greg Lobanov','USA'),
('Cloudpunk','PS5','Ion Lands','Germany'),
('Coffee Talk','PS5','Toge Productions','Indonesia'),
('Coffee Talk Episode 2: Hibiscus and Butterfly','PS5','Toge Productions','Indonesia'),
('Concept Destruction','PS5','Thinice Games','Spain'),
('Crash Bandicoot 4: It`s About Time','PS5','Toys For Bob','USA'),
('Cult of the Lamb','PS5','Massive Monster','Australia'),
('Cyberpunk 2077','PS5','CD Projekt Red','Poland'),
('Death`s Door','PS5','Acid Nerve','England'),
('Deep Rock Galactic','PS5','Ghost Ship Games','Denmark'),
('Destiny 2','PS5','Bungie','USA'),
('Destroy All Humans 2: Reprobed (2022)','PS5','Black Forest Games','Germany'),
('DIRT 5','PS5','Codemasters','England'),
('Disney Dreamlight Valley','PS5','Gameloft','France'),
('Dungeon Munchies','PS5','maJAJa','Taiwan'),
('Endling: Extinction is Forever','PS5','Herobeat Studios','Spain'),
('Evil Inside','PS5','JanduSoft SL','Spain'),
('F1 2021','PS5','Codemasters','England'),
('F1 Manager','PS5','Frontier Developments','England'),
('Fall Guys: Ultimate Knockout','PS5','Mediatonic','England'),
('Far Cry 6: Gold Edition','PS5','Ubisoft Toronto','Canada'),
('Farming Simulator 22','PS5','GIANTS Software','Switzerland'),
('FIFA 21','PS5','EA Vancouver','Canada'),
('FIFA 22','PS5','EA Vancouver','Canada'),
('FIFA 23','PS5','EA Vancouver','Canada'),
('Final Fantasy VII (2021)','PS5','Square Enix','Japan'),
('First Class Trouble','PS5','Invisible Walls','Denmark'),
('Fortnite','PS5','Epic Games','USA'),
('Genshin Impact','PS5','miHoYo','China'),
('Ghostrunner','PS5','Slipgate Ironworks','Denmark'),
('Ghostwire: Tokyo','PS5','Tango Gameworks','Japan'),
('Godfall','PS5','Counterplay Games','USA'),
('Grand Theft Auto V','PS5','Rockstar North','Scotland'),
('GRID Legends','PS5','Codemasters','England'),
('Grindstone','PS5','Capybara Games','Canada'),
('Heavenly Bodies','PS5','2pt Interactive','Australia'),
('Hell Let Loose','PS5','Black Matter Games','Australia'),
('Hogwarts Legacy','PS5','Avalanche Software','USA'),
('Horizon Forbidden West','PS5','Guerrilla Games','Netherlands'),
('Hot Wheels Unleashed','PS5','Milestone','Italy'),
('Human Fall Flat','PS5','No Brakes Games','Lithuania'),
('In Rays of the Light','PS5','Sergey Noskov','Russia'),
('Infliction: Extended Cut','PS5','Caustic Reality','Australia'),
('It Takes Two','PS5','Hazelight Studios','Sweden'),
('Judgment','PS5','Ryu Ga Gotoku','Japan'),
('Jurassic World Evolution 2','PS5','Frontier Developments','England'),
('Kena: Bridge of Spirits','PS5','Ember Lab','USA'),
('Kerbal Space Program: Enhanced Edition','PS5','Squad','Mexico'),
('Klonoa Phantasy Reverie Series (2022)','PS5','Bandai Namco Studios','Japan'),
('Knockout City','PS5','Velan Studios','USA'),
('LEGO 2K Drive','PS5','Visual Concepts','USA'),
('Like a Dragon 7 (Yakuza 7)','PS5','Ryu Ga Gotoku','Japan'),
('Like a Dragon: Ishin','PS5','Ryu Ga Gotoku','Japan'),
('Like a Dragon Gaiden: The Man Who Erased His Name','PS5','Ryu Ga Gotoku','Japan'),
('Lost Judgment: Ultimate Edition','PS5','Ryu Ga Gotoku','Japan'),
('Maneater','PS5','Tripwire Interactive','USA'),
('Maquette','PS5','Graceful Decay','USA'),
('Marvel`s Spider-Man: Miles Morales','PS5','Insomniac Games','USA'),
('Marvel`s Spider-Man 2: Digital Deluxe Edition','PS5','Insomniac Games','USA'),
('Meet Your Maker','PS5','Behaviour Interactive','Canada'),
('Metro Exodus','PS5','4A Games','Ukraine'),
('Music Racer: Ultimate','PS5','Sometimes You','Russia'),
('NBA 2K23','PS5','Visual Concepts','USA'),
('New Tales from the Borderlands','PS5','Gearbox Quebec','Canada'),
('Nickelodeon All Stars Brawl','PS5','Ludosity','Sweden'),
('Nioh 2','PS5','Team Ninja','Japan'),
('No Man`s Sky','PS5','Hello Games','England'),
('Nour: Play with your Food','PS5','Terrifying Jellyfish','USA'),
('Oddworld: Soulstorm (2021)','PS5','Oddworld Inhabitants','USA'),
('OlliOlli World','PS5','Roll7','England'),
('One Escape','PS5','BUG-Studio','Russia'),
('Overcooked: All You Can Eat Edition','PS5','Ghost Town Games','England'),
('Ovivo','PS5','IzHard','Russia'),
('Planet Coaster','PS5','Frontier Developments','England'),
('Postal 4: No Regerts','PS5','Running with Scissors','USA'),
('Potion Permit','PS5','MassHive Media','Indonesia'),
('PowerWash Simulator','PS5','FuturLab','England'),
('Ratchet & Clank: Rift Apart','PS5','Insomniac Games','USA'),
('Resident Evil 2 (2019)','PS5','Capcom','Japan'),
('Resident Evil 3 (2020)','PS5','Capcom','Japan'),
('Resident Evil 4 (2023)','PS5','Capcom','Japan'),
('Resident Evil VII: Biohazard','PS5','Capcom','Japan'),
('Resident Evil Village','PS5','Capcom','Japan'),
('Returnal','PS5','Housemarque','Finland'),
('Rogue Company','PS5','First Watch Games','USA'),
('Rustler','PS5','Jutsu Games','Poland'),
('Sable','PS5','Shedworks','England'),
('Sackboy: A Big Adventure','PS5','Sumo Digital','England'),
('Saints Row The Third: Remastered','PS5','Deep Silver Volition','USA'),
('Saints Row (2022)','PS5','Deep Silver Volition','USA'),
('Shantae and The Pirate`s Curse','PS5','WayForward Technologies Inc','USA'),
('Shing!','PS5','Mass Creation','Poland'),
('Sir Lovelot','PS5','pixel.lu','Luxembourg'),
('Sonic Origins','PS5','Sega','Japan'),
('Spacebase Startopia','PS5','Realmforge Studios','Germany'),
('Spirit of the North: Enhanced Edition','PS5','Infuse Studio','USA'),
('Star Wars Jedi: Fallen Order','PS5','Respawn Entertainment','USA'),
('Stray','PS5','BlueTwelve Studio','France'),
('Subnautica','PS5','Unknown Worlds Entertainment','USA'),
('Subnautica: Below Zero','PS5','Unknown Worlds Entertainment','USA'),
('Sumatra: Fate of Yandi','PS5','Cloak and Dagger Games','England'),
('Tails of Iron','PS5','Odd Bug Studios','England'),
('Tchia','PS5','Awaceb','France'),
('Terminator: Resistance Enhanced','PS5','Teyon','Poland'),
('The Callisto Protocol','PS5','Striking Distance Studios','USA'),
('The Darkside Detective','PS5','Spooky Doorway','Republic of Ireland'),
('The Darkside Detective: A Fumble in the Dark','PS5','Spooky Doorway','Republic of Ireland'),
('The Pedestrian','PS5','Skookum Arts','USA'),
('The Persistence','PS5','Firesprite','England'),
('The Sinking City','PS5','Frogwares','Ukraine'),
('The Stanley Parable: Ultra Deluxe','PS5','Crows Crows Crows','Germany'),
('The Witcher 3: Wild Hunt','PS5','CD Projekt Red','Poland'),
('Tiny Tina`s Wonderlands: Chaotic Great Edition','PS5','Gearbox Software','USA'),
('TOEM','PS5','Something We Made','Sweden'),
('Tony Hawk`s Pro Skater 1 + 2 (2021)','PS5','Vicarious Visions','USA'),
('Trek to Yomi','PS5','Flying Wild Hog','Poland'),
('Tunic','PS5','Isometricorp Games','Canada'),
('Twin Robots: Ultimate Edition','PS5','Thinice Games','Spain'),
('Two Point Campus','PS5','Two Point Studios','England'),
('Warframe: The New War','PS5','Digital Extremes','Canada'),
('Watch_Dogs: Legion','PS5','Ubisoft Toronto','Canada'),
('Wonder Boy: The Dragon`s Trap','PS5','Lizardcube','France'),
('Weird West: Definitive Edition','PS5','WolfEye Studios','France'),
('Worms Rumble','PS5','Team17','England'),
('Wreckfest','PS5','Bugbear Entertainment','Finland');