INSERT INTO playstation.dbo.Origins (Id,Game,Console,Developer,Country)
VALUES
   (71,'Ape Escape','PSP','Japan Studio','Japan'),
   (72,'Burnout Legends','PSP','Criterion Games','England'),
   (73,'Crazy Taxi: Fare Wars','PSP','Sniper Studios','USA'),
   (74,'Daxter','PSP','Ready At Dawn','USA'),
   (75,'Dead or Alive Paradise','PSP','Project Venus','Japan'),
   (76,'Everybody`s Golf 2','PSP','Clap Hanz','Japan'),
   (77,'Final Fantasy','PSP','Square Enix','Japan'),
   (78,'Final Fantasy II','PSP','Square Enix','Japan'),
   (79,'Final Fantasy III','PSP','Square Enix','Japan'),
   (80,'Final Fantasy IV','PSP','Square Enix','Japan'),
   (81,'Grand Theft Auto: Chinatown Wars','PSP','Rockstar Leeds','England'),
   (82,'Grand Theft Auto: Liberty City Stories','PSP','Rockstar Leeds','England'),
   (83,'Grand Theft Auto: Vice City Stories','PSP','Rockstar Leeds','England'),
   (84,'Gravity Crash','PSP','Just Add Water Ltd','England'),
   (85,'Jak and Daxter: The Lost Frontier','PSP','High Impact Games','USA'),
   (86,'LEGO Batman','PSP','TT Games','England'),
   (87,'LEGO Indiana Jones','PSP','TT Games','England'),
   (88,'LEGO Pirates of the Caribbean','PSP','TT Games','England'),
   (89,'LEGO Star Wars III: The Clone Wars','PSP','TT Games','England'),
   (90,'Prinny','PSP','Nippon Ichi Software','Japan'),
   (91,'Ratchet & Clank: Size Matters','PSP','High Impact Games','USA'),
   (92,'Resistance: Retribution','PSP','Bend Studio','USA'),
   (93,'Super Monkey Ball Adventure','PSP','TT Games','England'),
   (94,'Tomb Raider: Anniversary','PSP','Crystal Dynamics','USA'),
   (95,'Tomb Raider: Legend','PSP','Crystal Dynamics','USA'),
   (96,'Wipeout Pulse','PSP','Psygnosis','England');