INSERT INTO playstation.dbo.Origins (Id,Game,Console,Developer,Country)
VALUES
(236,'Crazy Market','PSVITA','The Game Atelier','France'),
(237,'Deathmatch Village','PSVITA','Bloober Team','Poland'),
(238,'Fat Princess: Piece of Cake','PSVITA','One Loop Games','USA'),
(239,'Flame Over','PSVITA','Laughing Jackal Ltd','England'),
(240,'Football Manager Classic 2014','PSVITA','Sports Interactive','England'),
(241,'Get Off My Lawn!','PSVITA','Digital Leisure Inc','Canada'),
(242,'Gunslugs','PSVITA','Abstraction Games','Netherlands'),
(243,'Jet Set Radio','PSVITA','Sega','Japan'),
(244,'LEGO Batman 2: DC Super Heroes','PSVITA','TT Games','England'),
(245,'ModNation Racers: Road Trip','PSVITA','San Diego Studio','USA'),
(246,'No Heroes Allowed: No Puzzles Either!','PSVITA','ACQUIRE Corp','Japan'),
(247,'Paint Park','PSVITA','Sony Interactive Entertainment','Japan'),
(248,'Paint Park Plus','PSVITA','Sony Interactive Entertainment','Japan'),
(249,'PlayStation Vita Pets','PSVITA','Spiral House','England'),
(250,'Quell Memento','PSVITA','Fallen Tree Games','England'),
(251,'Rocketbirds: Hardboiled Chicken','PSVITA','Ratloop','USA'),
(252,'Silent Hill: Book of Memories','PSVITA','WayForward Technologies Inc','USA'),
(253,'Skeleton Rider','PSVITA','iSquared Games','England'),
(254,'Sly Cooper: Thieves in Time','PSVITA','Sanzaru Games','USA'),
(255,'Spy Hunter (2012)','PSVITA','TT Games','England'),
(256,'Street Fighter X Tekken','PSVITA','Sucker Punch Productions','USA'),
(257,'SunFlowers','PSVITA','The Game Atelier','France'),
(258,'Surge Deluxe','PSVITA','FuturLab','England'),
(259,'Table Football','PSVITA','Sony Interactive Entertainment','Japan'),
(260,'Table Top Racing','PSVITA','Playrise Digital Ltd','England'),
(261,'TxK','PSVITA','Llamasoft','England'),
(262,'Uncharted: Fight for Fortune','PSVITA','Bend Studio','USA'),
(263,'Uncharted: Golden Abyss','PSVITA','Bend Studio','USA'),
(264,'Wanderjahr','PSVITA','Workyrie Game Studio','Japan'),
(265,'Worms Revolution Extreme','PSVITA','Team17','England'),
(266,'Yomawari: Night Alone','PSVITA','Nippon Ichi Software','Japan'),
(267,'Zero Escape: Virtue`s Last Reward','PSVITA','Spike Chunsoft','Japan');