INSERT INTO playstation.dbo.Origins (Id,Game,Console,Developer,Country)
VALUES
(682,'Accounting Plus','PSVR','Squanch Games','USA'),
(683,'Animal Force','PSVR','ISVR','China'),
(684,'Apex Construct','PSVR','Fast Travel Games','Sweden'),
(685,'Apocalypse Rider','PSVR','VRMonkey','Brazil'),
(686,'Arizona Sunshine','PSVR','Vertigo Games','Netherlands'),
(687,'ASTRO BOT Rescue Mission','PSVR','Team Asobi','Japan'),
(688,'Batman: Arkham VR','PSVR','Rocksteady Studios','England'),
(689,'Beat Saber','PSVR','Beat Games','Czech Republic'),
(690,'BoxVR','PSVR','FitXR','USA'),
(691,'Carnival Games VR','PSVR','Cat Daddy Games','USA'),
(692,'Catch & Release','PSVR','metricminds','Germany'),
(693,'CoolpaintrVR','PSVR','Wildbit Studios','Spain'),
(694,'Creed: Rise To Glory','PSVR','Survios','USA'),
(695,'Discovery','PSVR','Noowanda','Germany'),
(696,'DOOM VFR','PSVR','id Software','USA'),
(697,'Dream Match Tennis VR','PSVR','Bimboosoft','Japan'),
(698,'DriveClub VR','PSVR','Evolution Studios','England'),
(699,'Drunkn Bar Fight','PSVR','The Munky','USA'),
(700,'Eagle Flight','PSVR','Ubisoft Montreal','Canada'),
(701,'EVE: Valkyrie','PSVR','CCP Games','Iceland'),
(702,'Everest VR','PSVR','Solfar Studios','Iceland'),
(703,'Everybody`s Golf VR','PSVR','Clap Hanz','Japan'),
(704,'Floor Plan','PSVR','Turbo Button','USA'),
(705,'Fruit Ninja VR','PSVR','Halfbrick Studios','Australia'),
(706,'Groundhog Day: Like Father Like Son','PSVR','Tequila Works','Spain'),
(707,'Gun Club VR','PSVR','The Binary Mill','Australia'),
(708,'Headmaster','PSVR','Frame Interactive','USA'),
(709,'Homestar VR','PSVR','Pocket Ohira Tech','Japan'),
(710,'Hotel R n R','PSVR','Wolf & Wood Interactive Ltd','England'),
(711,'Hustle Kings VR','PSVR','VooFoo Studios','England'),
(712,'I Expect You To Die','PSVR','Schell Games','USA'),
(713,'I Expect You to Die 2','PSVR','Schell Games','USA'),
(714,'Job Simulator VR','PSVR','Owlchemy Labs','USA'),
(715,'Kingdom Hearts: VR Experience','PSVR','Square Enix','Japan'),
(716,'Knockout League','PSVR','Grab Games','USA'),
(717,'Kona VR','PSVR','Parabole','Canada'),
(718,'Lethal VR','PSVR','Three Fields Entertainment','England'),
(719,'Marvel`s Iron Man VR','PSVR','Camouflaj','USA'),
(720,'Mervils: A VR Adventure','PSVR','VitruviusVR','Canada'),
(721,'Moss','PSVR','Polyarc','USA'),
(722,'Penn & Teller VR','PSVR','Gearbox Software','USA'),
(723,'Perfect VR','PSVR','nDreams','England'),
(724,'PlayStation VR Worlds','PSVR','London Studio','England'),
(725,'Psychonauts in the Rhombus Of Ruin VR','PSVR','Double Fine Productions','USA'),
(726,'Rez Infinite VR','PSVR','Enhance Games','USA'),
(727,'Rick & Morty: Virtual Rick-ality','PSVR','Owlchemy Labs','USA'),
(728,'RIGS: Mechanized Combat League VR','PSVR','Guerrilla Cambridge','England'),
(729,'Sam & Max: This Time It`s Virtual!','PSVR','HappyGiant','USA'),
(730,'Shooty Fruity','PSVR','nDreams','England'),
(731,'Skyrim VR','PSVR','Bethesda Game Studios','USA'),
(732,'Sniper Elite VR','PSVR','Just Add Water Ltd','England'),
(733,'Space Pirate Trainer VR','PSVR','I-Illusions','Belgium'),
(734,'Sprint Vector','PSVR','Survios','USA'),
(735,'Star Trek: Bridge Crew VR','PSVR','Red Storm Entertainment','USA'),
(736,'Superhot VR','PSVR','Superhot Team','Poland'),
(737,'Tetris Effect: Connected','PSVR','Monstars','Japan'),
(738,'The American Dream','PSVR','Samurai Punk','Australia'),
(739,'The Guy VR','PSVR','Chubby Pixel','Italy'),
(740,'The Playroom VR','PSVR','Team Asobi','Japan'),
(741,'The Walking Dead: Saints and Sinners','PSVR','Skydance Interactive','USA'),
(742,'Tiny Trax','PSVR','FuturLab','England'),
(743,'Track Lab','PSVR','Little Chicken','Netherlands'),
(744,'Trackmania Turbo','PSVR','Nadeo','France'),
(745,'Traffic Jams','PSVR','Little Chicken','Netherlands'),
(746,'Tumble VR','PSVR','Supermassive Games','England'),
(747,'Ultrawings','PSVR','Bit Planet Games','USA'),
(748,'Until Dawn: Rush Of Blood','PSVR','Supermassive Games','England'),
(749,'Until You Fall','PSVR','WayTooManyGames','USA'),
(750,'VR Karts','PSVR','Viewpoint Games','England'),
(751,'VR Ping Pong','PSVR','Reddoll Srl','Italy'),
(752,'VR The Diner Duo','PSVR','Whirlybird Games','Sweden'),
(753,'Wanderer','PSVR','Oddboy','New Zealand'),
(754,'You Are Being Followed','PSVR','Uncommon Chocolate','Scotland');