-- CREATE DATABASE Nintendo

CREATE TABLE Games
(
	ID SMALLINT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
    Game VARCHAR(50) NOT NULL, 
    Main_Console VARCHAR(10) NOT NULL,
    Alt_Console VARCHAR(12) NULL,
    ReleaseDateEUR DATE NOT NULL
)